// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: servicebridge/v1/call.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export interface CallRequest {
  method: string;
  payload: Buffer;
  callerService: string;
  requestId: string;
  idempotencyKey: string;
  /**
   * X-SB-Trace propagation: trace_id and parent_op_id are carried via gRPC
   * metadata under "x-sb-trace" key (T-017). Not in the wire message itself.
   */
  xSbTrace: string;
}

export interface CallResponse {
  payload: Buffer;
  errorCode: string;
  errorMessage: string;
}

/** StreamChunk — один элемент server-streaming ответа. */
export interface StreamChunk {
  payload: Buffer;
  errorCode: string;
  errorMessage: string;
}

function createBaseCallRequest(): CallRequest {
  return { method: "", payload: Buffer.alloc(0), callerService: "", requestId: "", idempotencyKey: "", xSbTrace: "" };
}

export const CallRequest: MessageFns<CallRequest> = {
  encode(message: CallRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.method !== "") {
      writer.uint32(10).string(message.method);
    }
    if (message.payload.length !== 0) {
      writer.uint32(18).bytes(message.payload);
    }
    if (message.callerService !== "") {
      writer.uint32(26).string(message.callerService);
    }
    if (message.requestId !== "") {
      writer.uint32(34).string(message.requestId);
    }
    if (message.idempotencyKey !== "") {
      writer.uint32(42).string(message.idempotencyKey);
    }
    if (message.xSbTrace !== "") {
      writer.uint32(50).string(message.xSbTrace);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.callerService = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.requestId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.xSbTrace = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CallRequest>, I>>(base?: I): CallRequest {
    return CallRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallRequest>, I>>(object: I): CallRequest {
    const message = createBaseCallRequest();
    message.method = object.method ?? "";
    message.payload = object.payload ?? Buffer.alloc(0);
    message.callerService = object.callerService ?? "";
    message.requestId = object.requestId ?? "";
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.xSbTrace = object.xSbTrace ?? "";
    return message;
  },
};

function createBaseCallResponse(): CallResponse {
  return { payload: Buffer.alloc(0), errorCode: "", errorMessage: "" };
}

export const CallResponse: MessageFns<CallResponse> = {
  encode(message: CallResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.payload.length !== 0) {
      writer.uint32(10).bytes(message.payload);
    }
    if (message.errorCode !== "") {
      writer.uint32(18).string(message.errorCode);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.payload = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.errorCode = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CallResponse>, I>>(base?: I): CallResponse {
    return CallResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallResponse>, I>>(object: I): CallResponse {
    const message = createBaseCallResponse();
    message.payload = object.payload ?? Buffer.alloc(0);
    message.errorCode = object.errorCode ?? "";
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseStreamChunk(): StreamChunk {
  return { payload: Buffer.alloc(0), errorCode: "", errorMessage: "" };
}

export const StreamChunk: MessageFns<StreamChunk> = {
  encode(message: StreamChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.payload.length !== 0) {
      writer.uint32(10).bytes(message.payload);
    }
    if (message.errorCode !== "") {
      writer.uint32(18).string(message.errorCode);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.payload = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.errorCode = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StreamChunk>, I>>(base?: I): StreamChunk {
    return StreamChunk.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamChunk>, I>>(object: I): StreamChunk {
    const message = createBaseStreamChunk();
    message.payload = object.payload ?? Buffer.alloc(0);
    message.errorCode = object.errorCode ?? "";
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

/**
 * Call — inbound RPC сервер SDK-инстанса.
 * Используется и в direct-режиме (caller → callee), и в proxy-режиме (runtime → callee).
 */
export type CallService = typeof CallService;
export const CallService = {
  unary: {
    path: "/servicebridge.v1.Call/Unary" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CallRequest): Buffer => Buffer.from(CallRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CallRequest => CallRequest.decode(value),
    responseSerialize: (value: CallResponse): Buffer => Buffer.from(CallResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CallResponse => CallResponse.decode(value),
  },
  /**
   * Stream — server-side streaming: каллер шлёт один запрос, callee стримит
   * chunks (например, LLM token streaming). Bidirectional streaming не в scope.
   */
  stream: {
    path: "/servicebridge.v1.Call/Stream" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: CallRequest): Buffer => Buffer.from(CallRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CallRequest => CallRequest.decode(value),
    responseSerialize: (value: StreamChunk): Buffer => Buffer.from(StreamChunk.encode(value).finish()),
    responseDeserialize: (value: Buffer): StreamChunk => StreamChunk.decode(value),
  },
} as const;

export interface CallServer extends UntypedServiceImplementation {
  unary: handleUnaryCall<CallRequest, CallResponse>;
  /**
   * Stream — server-side streaming: каллер шлёт один запрос, callee стримит
   * chunks (например, LLM token streaming). Bidirectional streaming не в scope.
   */
  stream: handleServerStreamingCall<CallRequest, StreamChunk>;
}

export interface CallClient extends Client {
  unary(request: CallRequest, callback: (error: ServiceError | null, response: CallResponse) => void): ClientUnaryCall;
  unary(
    request: CallRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CallResponse) => void,
  ): ClientUnaryCall;
  unary(
    request: CallRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CallResponse) => void,
  ): ClientUnaryCall;
  /**
   * Stream — server-side streaming: каллер шлёт один запрос, callee стримит
   * chunks (например, LLM token streaming). Bidirectional streaming не в scope.
   */
  stream(request: CallRequest, options?: Partial<CallOptions>): ClientReadableStream<StreamChunk>;
  stream(request: CallRequest, metadata?: Metadata, options?: Partial<CallOptions>): ClientReadableStream<StreamChunk>;
}

export const CallClient = makeGenericClientConstructor(CallService, "servicebridge.v1.Call") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): CallClient;
  service: typeof CallService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
