// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.13.0
//   protoc               unknown
// source: servicebridge/v1/control.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

/**
 * Handshake identity of the SDK opening the control stream. The runtime
 * rejects a protocol_version it does not support with FAILED_PRECONDITION.
 */
export interface OpenRequest {
  /**
   * Wire contract revision the SDK was generated against (see
   * PROTOCOL_VERSION in the SDKs). 0 = not sent.
   */
  protocolVersion: number;
  /** "node" | "go" | … — for diagnostics and the console. */
  sdkLanguage: string;
  /** SDK package version, e.g. "2.0.0-alpha.15". */
  sdkVersion: string;
}

export interface RefreshCertRequest {
  csrDer: Buffer;
}

export interface RefreshCertResponse {
  certDer: Buffer;
  caChainDer: Buffer;
  notAfterUnixMs: number;
  instanceId: string;
}

export interface ServerControl {
  welcome?: Welcome | undefined;
  drain?: Drain | undefined;
}

export interface Welcome {
  sessionId: string;
  serviceId: string;
  serviceName: string;
  /** Build version of the runtime binary. */
  runtimeVersion: string;
  /** Wire contract revision the runtime speaks. */
  protocolVersion: number;
}

export interface Drain {
  reason: string;
}

function createBaseOpenRequest(): OpenRequest {
  return { protocolVersion: 0, sdkLanguage: "", sdkVersion: "" };
}

export const OpenRequest: MessageFns<OpenRequest> = {
  encode(message: OpenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.protocolVersion !== 0) {
      writer.uint32(8).uint32(message.protocolVersion);
    }
    if (message.sdkLanguage !== "") {
      writer.uint32(18).string(message.sdkLanguage);
    }
    if (message.sdkVersion !== "") {
      writer.uint32(26).string(message.sdkVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOpenRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.protocolVersion = reader.uint32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.sdkLanguage = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.sdkVersion = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<OpenRequest>, I>>(base?: I): OpenRequest {
    return OpenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OpenRequest>, I>>(object: I): OpenRequest {
    const message = createBaseOpenRequest();
    message.protocolVersion = object.protocolVersion ?? 0;
    message.sdkLanguage = object.sdkLanguage ?? "";
    message.sdkVersion = object.sdkVersion ?? "";
    return message;
  },
};

function createBaseRefreshCertRequest(): RefreshCertRequest {
  return { csrDer: Buffer.alloc(0) };
}

export const RefreshCertRequest: MessageFns<RefreshCertRequest> = {
  encode(message: RefreshCertRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.csrDer.length !== 0) {
      writer.uint32(10).bytes(message.csrDer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshCertRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRefreshCertRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.csrDer = Buffer.from(reader.bytes());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RefreshCertRequest>, I>>(base?: I): RefreshCertRequest {
    return RefreshCertRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshCertRequest>, I>>(object: I): RefreshCertRequest {
    const message = createBaseRefreshCertRequest();
    message.csrDer = object.csrDer ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseRefreshCertResponse(): RefreshCertResponse {
  return { certDer: Buffer.alloc(0), caChainDer: Buffer.alloc(0), notAfterUnixMs: 0, instanceId: "" };
}

export const RefreshCertResponse: MessageFns<RefreshCertResponse> = {
  encode(message: RefreshCertResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.certDer.length !== 0) {
      writer.uint32(10).bytes(message.certDer);
    }
    if (message.caChainDer.length !== 0) {
      writer.uint32(18).bytes(message.caChainDer);
    }
    if (message.notAfterUnixMs !== 0) {
      writer.uint32(24).int64(message.notAfterUnixMs);
    }
    if (message.instanceId !== "") {
      writer.uint32(34).string(message.instanceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshCertResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseRefreshCertResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.certDer = Buffer.from(reader.bytes());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.caChainDer = Buffer.from(reader.bytes());
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.notAfterUnixMs = longToNumber(reader.int64());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.instanceId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<RefreshCertResponse>, I>>(base?: I): RefreshCertResponse {
    return RefreshCertResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshCertResponse>, I>>(object: I): RefreshCertResponse {
    const message = createBaseRefreshCertResponse();
    message.certDer = object.certDer ?? Buffer.alloc(0);
    message.caChainDer = object.caChainDer ?? Buffer.alloc(0);
    message.notAfterUnixMs = object.notAfterUnixMs ?? 0;
    message.instanceId = object.instanceId ?? "";
    return message;
  },
};

function createBaseServerControl(): ServerControl {
  return { welcome: undefined, drain: undefined };
}

export const ServerControl: MessageFns<ServerControl> = {
  encode(message: ServerControl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.welcome !== undefined) {
      Welcome.encode(message.welcome, writer.uint32(10).fork()).join();
    }
    if (message.drain !== undefined) {
      Drain.encode(message.drain, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerControl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseServerControl();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.welcome = Welcome.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.drain = Drain.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<ServerControl>, I>>(base?: I): ServerControl {
    return ServerControl.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerControl>, I>>(object: I): ServerControl {
    const message = createBaseServerControl();
    message.welcome = (object.welcome !== undefined && object.welcome !== null)
      ? Welcome.fromPartial(object.welcome)
      : undefined;
    message.drain = (object.drain !== undefined && object.drain !== null) ? Drain.fromPartial(object.drain) : undefined;
    return message;
  },
};

function createBaseWelcome(): Welcome {
  return { sessionId: "", serviceId: "", serviceName: "", runtimeVersion: "", protocolVersion: 0 };
}

export const Welcome: MessageFns<Welcome> = {
  encode(message: Welcome, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.serviceId !== "") {
      writer.uint32(18).string(message.serviceId);
    }
    if (message.serviceName !== "") {
      writer.uint32(26).string(message.serviceName);
    }
    if (message.runtimeVersion !== "") {
      writer.uint32(34).string(message.runtimeVersion);
    }
    if (message.protocolVersion !== 0) {
      writer.uint32(40).uint32(message.protocolVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Welcome {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseWelcome();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.sessionId = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.serviceId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.serviceName = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.runtimeVersion = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.protocolVersion = reader.uint32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Welcome>, I>>(base?: I): Welcome {
    return Welcome.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Welcome>, I>>(object: I): Welcome {
    const message = createBaseWelcome();
    message.sessionId = object.sessionId ?? "";
    message.serviceId = object.serviceId ?? "";
    message.serviceName = object.serviceName ?? "";
    message.runtimeVersion = object.runtimeVersion ?? "";
    message.protocolVersion = object.protocolVersion ?? 0;
    return message;
  },
};

function createBaseDrain(): Drain {
  return { reason: "" };
}

export const Drain: MessageFns<Drain> = {
  encode(message: Drain, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reason !== "") {
      writer.uint32(10).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Drain {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseDrain();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.reason = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  create<I extends Exact<DeepPartial<Drain>, I>>(base?: I): Drain {
    return Drain.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Drain>, I>>(object: I): Drain {
    const message = createBaseDrain();
    message.reason = object.reason ?? "";
    return message;
  },
};

/**
 * Control plane stream. After Telemetry feature heartbeat moved out — Control
 * несёт только server-driven signalling: Welcome (один раз) и Drain (при
 * shutdown). Cert refresh — отдельным unary RPC.
 */
export type ControlService = typeof ControlService;
export const ControlService = {
  open: {
    path: "/servicebridge.v1.Control/Open" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: OpenRequest): Buffer => Buffer.from(OpenRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): OpenRequest => OpenRequest.decode(value),
    responseSerialize: (value: ServerControl): Buffer => Buffer.from(ServerControl.encode(value).finish()),
    responseDeserialize: (value: Buffer): ServerControl => ServerControl.decode(value),
  },
  /**
   * RefreshCert reissues the caller's leaf cert via the existing mTLS
   * session (SPIFFE from cert == source of truth, no argon2).
   */
  refreshCert: {
    path: "/servicebridge.v1.Control/RefreshCert" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RefreshCertRequest): Buffer => Buffer.from(RefreshCertRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RefreshCertRequest => RefreshCertRequest.decode(value),
    responseSerialize: (value: RefreshCertResponse): Buffer => Buffer.from(RefreshCertResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RefreshCertResponse => RefreshCertResponse.decode(value),
  },
} as const;

export interface ControlServer extends UntypedServiceImplementation {
  open: handleServerStreamingCall<OpenRequest, ServerControl>;
  /**
   * RefreshCert reissues the caller's leaf cert via the existing mTLS
   * session (SPIFFE from cert == source of truth, no argon2).
   */
  refreshCert: handleUnaryCall<RefreshCertRequest, RefreshCertResponse>;
}

export interface ControlClient extends Client {
  open(request: OpenRequest, options?: Partial<CallOptions>): ClientReadableStream<ServerControl>;
  open(request: OpenRequest, metadata?: Metadata, options?: Partial<CallOptions>): ClientReadableStream<ServerControl>;
  /**
   * RefreshCert reissues the caller's leaf cert via the existing mTLS
   * session (SPIFFE from cert == source of truth, no argon2).
   */
  refreshCert(
    request: RefreshCertRequest,
    callback: (error: ServiceError | null, response: RefreshCertResponse) => void,
  ): ClientUnaryCall;
  refreshCert(
    request: RefreshCertRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RefreshCertResponse) => void,
  ): ClientUnaryCall;
  refreshCert(
    request: RefreshCertRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RefreshCertResponse) => void,
  ): ClientUnaryCall;
}

export const ControlClient = makeGenericClientConstructor(ControlService, "servicebridge.v1.Control") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ControlClient;
  service: typeof ControlService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
