// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: servicebridge/v1/events.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type ClientUnaryCall,
  type handleBidiStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export enum PublishStatus {
  PUBLISH_STATUS_UNSPECIFIED = 0,
  PUBLISH_STATUS_ACCEPTED = 1,
  PUBLISH_STATUS_REJECTED_DUPLICATE = 3,
  PUBLISH_STATUS_REJECTED_INVALID_NAME = 5,
  /**
   * PUBLISH_STATUS_REJECTED_FORBIDDEN - ADR-0014: publisher does not have event.publish action rule matching this
   * event name (or its capability is disabled). Per-envelope reject — other
   * events in the batch proceed.
   */
  PUBLISH_STATUS_REJECTED_FORBIDDEN = 6,
  UNRECOGNIZED = -1,
}

export interface EventEnvelope {
  id: string;
  name: string;
  payload: Buffer;
  contractHash: string;
  partitionKey: string;
  idempotencyKey: string;
  fireAndForget: boolean;
  headers: { [key: string]: string };
  occurredAtUnixMs: number;
  /** X-SB-Trace propagation: carried in EventEnvelope for publisher→consumer. */
  xSbTrace: string;
  /**
   * payload_json — JSON-encoded view of the same payload, populated by the
   * publisher SDK alongside the canonical protobuf `payload`. Used by the
   * workflow signal router to evaluate JSON-path `wait_event` filters
   * without decoding the protobuf form (runtime treats payload as opaque
   * bytes per ADR-0013). Empty when publisher cannot produce JSON.
   */
  payloadJson: Buffer;
}

export interface EventEnvelope_HeadersEntry {
  key: string;
  value: string;
}

export interface PublishRequest {
  publisherServiceId: string;
  publisherInstanceId: string;
  events: EventEnvelope[];
}

export interface PublishStatusEntry {
  eventId: string;
  status: PublishStatus;
  message: string;
}

export interface PublishResponse {
  results: PublishStatusEntry[];
}

export interface SubscribeInit {
  subscriberServiceId: string;
  subscriberInstanceId: string;
  maxInFlight: number;
}

export interface Ack {
  deliveryId: string;
  eventId: Buffer;
}

export interface Nack {
  deliveryId: string;
  errorMessage: string;
  eventId: Buffer;
}

export interface SubscribeClientMessage {
  init?: SubscribeInit | undefined;
  ack?: Ack | undefined;
  nack?: Nack | undefined;
}

export interface EventDelivery {
  deliveryId: string;
  envelope?: EventEnvelope | undefined;
  attempt: number;
}

export interface SubscribeServerMessage {
  delivery?: EventDelivery | undefined;
}

export interface ReplayDlqRequest {
  eventId: string;
}

export interface ReplayDlqResponse {
  eventId: string;
}

export interface ListDlqRequest {
  limit: number;
  cursor: string;
}

export interface DlqEntry {
  eventId: string;
  eventName: string;
  consumerService: string;
  lastError: string;
  dlqAtUnixMs: number;
  replayCount: number;
  totalAttempts: number;
}

export interface ListDlqResponse {
  entries: DlqEntry[];
  nextCursor: string;
}

function createBaseEventEnvelope(): EventEnvelope {
  return {
    id: "",
    name: "",
    payload: Buffer.alloc(0),
    contractHash: "",
    partitionKey: "",
    idempotencyKey: "",
    fireAndForget: false,
    headers: {},
    occurredAtUnixMs: 0,
    xSbTrace: "",
    payloadJson: Buffer.alloc(0),
  };
}

export const EventEnvelope: MessageFns<EventEnvelope> = {
  encode(message: EventEnvelope, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.payload.length !== 0) {
      writer.uint32(26).bytes(message.payload);
    }
    if (message.contractHash !== "") {
      writer.uint32(34).string(message.contractHash);
    }
    if (message.partitionKey !== "") {
      writer.uint32(42).string(message.partitionKey);
    }
    if (message.idempotencyKey !== "") {
      writer.uint32(50).string(message.idempotencyKey);
    }
    if (message.fireAndForget !== false) {
      writer.uint32(56).bool(message.fireAndForget);
    }
    globalThis.Object.entries(message.headers).forEach(([key, value]: [string, string]) => {
      EventEnvelope_HeadersEntry.encode({ key: key as any, value }, writer.uint32(66).fork()).join();
    });
    if (message.occurredAtUnixMs !== 0) {
      writer.uint32(72).int64(message.occurredAtUnixMs);
    }
    if (message.xSbTrace !== "") {
      writer.uint32(82).string(message.xSbTrace);
    }
    if (message.payloadJson.length !== 0) {
      writer.uint32(90).bytes(message.payloadJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventEnvelope {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventEnvelope();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload = Buffer.from(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contractHash = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.partitionKey = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.fireAndForget = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          const entry8 = EventEnvelope_HeadersEntry.decode(reader, reader.uint32());
          if (entry8.value !== undefined) {
            message.headers[entry8.key] = entry8.value;
          }
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.occurredAtUnixMs = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.xSbTrace = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.payloadJson = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EventEnvelope>, I>>(base?: I): EventEnvelope {
    return EventEnvelope.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventEnvelope>, I>>(object: I): EventEnvelope {
    const message = createBaseEventEnvelope();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.payload = object.payload ?? Buffer.alloc(0);
    message.contractHash = object.contractHash ?? "";
    message.partitionKey = object.partitionKey ?? "";
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.fireAndForget = object.fireAndForget ?? false;
    message.headers = (globalThis.Object.entries(object.headers ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.occurredAtUnixMs = object.occurredAtUnixMs ?? 0;
    message.xSbTrace = object.xSbTrace ?? "";
    message.payloadJson = object.payloadJson ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseEventEnvelope_HeadersEntry(): EventEnvelope_HeadersEntry {
  return { key: "", value: "" };
}

export const EventEnvelope_HeadersEntry: MessageFns<EventEnvelope_HeadersEntry> = {
  encode(message: EventEnvelope_HeadersEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventEnvelope_HeadersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventEnvelope_HeadersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EventEnvelope_HeadersEntry>, I>>(base?: I): EventEnvelope_HeadersEntry {
    return EventEnvelope_HeadersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventEnvelope_HeadersEntry>, I>>(object: I): EventEnvelope_HeadersEntry {
    const message = createBaseEventEnvelope_HeadersEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBasePublishRequest(): PublishRequest {
  return { publisherServiceId: "", publisherInstanceId: "", events: [] };
}

export const PublishRequest: MessageFns<PublishRequest> = {
  encode(message: PublishRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.publisherServiceId !== "") {
      writer.uint32(10).string(message.publisherServiceId);
    }
    if (message.publisherInstanceId !== "") {
      writer.uint32(18).string(message.publisherInstanceId);
    }
    for (const v of message.events) {
      EventEnvelope.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PublishRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublishRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.publisherServiceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.publisherInstanceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.events.push(EventEnvelope.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PublishRequest>, I>>(base?: I): PublishRequest {
    return PublishRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PublishRequest>, I>>(object: I): PublishRequest {
    const message = createBasePublishRequest();
    message.publisherServiceId = object.publisherServiceId ?? "";
    message.publisherInstanceId = object.publisherInstanceId ?? "";
    message.events = object.events?.map((e) => EventEnvelope.fromPartial(e)) || [];
    return message;
  },
};

function createBasePublishStatusEntry(): PublishStatusEntry {
  return { eventId: "", status: 0, message: "" };
}

export const PublishStatusEntry: MessageFns<PublishStatusEntry> = {
  encode(message: PublishStatusEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PublishStatusEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublishStatusEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PublishStatusEntry>, I>>(base?: I): PublishStatusEntry {
    return PublishStatusEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PublishStatusEntry>, I>>(object: I): PublishStatusEntry {
    const message = createBasePublishStatusEntry();
    message.eventId = object.eventId ?? "";
    message.status = object.status ?? 0;
    message.message = object.message ?? "";
    return message;
  },
};

function createBasePublishResponse(): PublishResponse {
  return { results: [] };
}

export const PublishResponse: MessageFns<PublishResponse> = {
  encode(message: PublishResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.results) {
      PublishStatusEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PublishResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublishResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.results.push(PublishStatusEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PublishResponse>, I>>(base?: I): PublishResponse {
    return PublishResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PublishResponse>, I>>(object: I): PublishResponse {
    const message = createBasePublishResponse();
    message.results = object.results?.map((e) => PublishStatusEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSubscribeInit(): SubscribeInit {
  return { subscriberServiceId: "", subscriberInstanceId: "", maxInFlight: 0 };
}

export const SubscribeInit: MessageFns<SubscribeInit> = {
  encode(message: SubscribeInit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subscriberServiceId !== "") {
      writer.uint32(10).string(message.subscriberServiceId);
    }
    if (message.subscriberInstanceId !== "") {
      writer.uint32(18).string(message.subscriberInstanceId);
    }
    if (message.maxInFlight !== 0) {
      writer.uint32(24).int32(message.maxInFlight);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeInit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeInit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subscriberServiceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subscriberInstanceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxInFlight = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SubscribeInit>, I>>(base?: I): SubscribeInit {
    return SubscribeInit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeInit>, I>>(object: I): SubscribeInit {
    const message = createBaseSubscribeInit();
    message.subscriberServiceId = object.subscriberServiceId ?? "";
    message.subscriberInstanceId = object.subscriberInstanceId ?? "";
    message.maxInFlight = object.maxInFlight ?? 0;
    return message;
  },
};

function createBaseAck(): Ack {
  return { deliveryId: "", eventId: Buffer.alloc(0) };
}

export const Ack: MessageFns<Ack> = {
  encode(message: Ack, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deliveryId !== "") {
      writer.uint32(10).string(message.deliveryId);
    }
    if (message.eventId.length !== 0) {
      writer.uint32(18).bytes(message.eventId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Ack {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deliveryId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.eventId = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Ack>, I>>(base?: I): Ack {
    return Ack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ack>, I>>(object: I): Ack {
    const message = createBaseAck();
    message.deliveryId = object.deliveryId ?? "";
    message.eventId = object.eventId ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseNack(): Nack {
  return { deliveryId: "", errorMessage: "", eventId: Buffer.alloc(0) };
}

export const Nack: MessageFns<Nack> = {
  encode(message: Nack, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deliveryId !== "") {
      writer.uint32(10).string(message.deliveryId);
    }
    if (message.errorMessage !== "") {
      writer.uint32(18).string(message.errorMessage);
    }
    if (message.eventId.length !== 0) {
      writer.uint32(26).bytes(message.eventId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Nack {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNack();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deliveryId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.eventId = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<Nack>, I>>(base?: I): Nack {
    return Nack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Nack>, I>>(object: I): Nack {
    const message = createBaseNack();
    message.deliveryId = object.deliveryId ?? "";
    message.errorMessage = object.errorMessage ?? "";
    message.eventId = object.eventId ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseSubscribeClientMessage(): SubscribeClientMessage {
  return { init: undefined, ack: undefined, nack: undefined };
}

export const SubscribeClientMessage: MessageFns<SubscribeClientMessage> = {
  encode(message: SubscribeClientMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.init !== undefined) {
      SubscribeInit.encode(message.init, writer.uint32(10).fork()).join();
    }
    if (message.ack !== undefined) {
      Ack.encode(message.ack, writer.uint32(18).fork()).join();
    }
    if (message.nack !== undefined) {
      Nack.encode(message.nack, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeClientMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeClientMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.init = SubscribeInit.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ack = Ack.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nack = Nack.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SubscribeClientMessage>, I>>(base?: I): SubscribeClientMessage {
    return SubscribeClientMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeClientMessage>, I>>(object: I): SubscribeClientMessage {
    const message = createBaseSubscribeClientMessage();
    message.init = (object.init !== undefined && object.init !== null)
      ? SubscribeInit.fromPartial(object.init)
      : undefined;
    message.ack = (object.ack !== undefined && object.ack !== null) ? Ack.fromPartial(object.ack) : undefined;
    message.nack = (object.nack !== undefined && object.nack !== null) ? Nack.fromPartial(object.nack) : undefined;
    return message;
  },
};

function createBaseEventDelivery(): EventDelivery {
  return { deliveryId: "", envelope: undefined, attempt: 0 };
}

export const EventDelivery: MessageFns<EventDelivery> = {
  encode(message: EventDelivery, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.deliveryId !== "") {
      writer.uint32(10).string(message.deliveryId);
    }
    if (message.envelope !== undefined) {
      EventEnvelope.encode(message.envelope, writer.uint32(18).fork()).join();
    }
    if (message.attempt !== 0) {
      writer.uint32(24).int32(message.attempt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventDelivery {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventDelivery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.deliveryId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.envelope = EventEnvelope.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.attempt = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EventDelivery>, I>>(base?: I): EventDelivery {
    return EventDelivery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventDelivery>, I>>(object: I): EventDelivery {
    const message = createBaseEventDelivery();
    message.deliveryId = object.deliveryId ?? "";
    message.envelope = (object.envelope !== undefined && object.envelope !== null)
      ? EventEnvelope.fromPartial(object.envelope)
      : undefined;
    message.attempt = object.attempt ?? 0;
    return message;
  },
};

function createBaseSubscribeServerMessage(): SubscribeServerMessage {
  return { delivery: undefined };
}

export const SubscribeServerMessage: MessageFns<SubscribeServerMessage> = {
  encode(message: SubscribeServerMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.delivery !== undefined) {
      EventDelivery.encode(message.delivery, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeServerMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeServerMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.delivery = EventDelivery.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SubscribeServerMessage>, I>>(base?: I): SubscribeServerMessage {
    return SubscribeServerMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeServerMessage>, I>>(object: I): SubscribeServerMessage {
    const message = createBaseSubscribeServerMessage();
    message.delivery = (object.delivery !== undefined && object.delivery !== null)
      ? EventDelivery.fromPartial(object.delivery)
      : undefined;
    return message;
  },
};

function createBaseReplayDlqRequest(): ReplayDlqRequest {
  return { eventId: "" };
}

export const ReplayDlqRequest: MessageFns<ReplayDlqRequest> = {
  encode(message: ReplayDlqRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReplayDlqRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReplayDlqRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ReplayDlqRequest>, I>>(base?: I): ReplayDlqRequest {
    return ReplayDlqRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReplayDlqRequest>, I>>(object: I): ReplayDlqRequest {
    const message = createBaseReplayDlqRequest();
    message.eventId = object.eventId ?? "";
    return message;
  },
};

function createBaseReplayDlqResponse(): ReplayDlqResponse {
  return { eventId: "" };
}

export const ReplayDlqResponse: MessageFns<ReplayDlqResponse> = {
  encode(message: ReplayDlqResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReplayDlqResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReplayDlqResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ReplayDlqResponse>, I>>(base?: I): ReplayDlqResponse {
    return ReplayDlqResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReplayDlqResponse>, I>>(object: I): ReplayDlqResponse {
    const message = createBaseReplayDlqResponse();
    message.eventId = object.eventId ?? "";
    return message;
  },
};

function createBaseListDlqRequest(): ListDlqRequest {
  return { limit: 0, cursor: "" };
}

export const ListDlqRequest: MessageFns<ListDlqRequest> = {
  encode(message: ListDlqRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.limit !== 0) {
      writer.uint32(8).int32(message.limit);
    }
    if (message.cursor !== "") {
      writer.uint32(18).string(message.cursor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListDlqRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDlqRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.cursor = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ListDlqRequest>, I>>(base?: I): ListDlqRequest {
    return ListDlqRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListDlqRequest>, I>>(object: I): ListDlqRequest {
    const message = createBaseListDlqRequest();
    message.limit = object.limit ?? 0;
    message.cursor = object.cursor ?? "";
    return message;
  },
};

function createBaseDlqEntry(): DlqEntry {
  return {
    eventId: "",
    eventName: "",
    consumerService: "",
    lastError: "",
    dlqAtUnixMs: 0,
    replayCount: 0,
    totalAttempts: 0,
  };
}

export const DlqEntry: MessageFns<DlqEntry> = {
  encode(message: DlqEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.eventName !== "") {
      writer.uint32(18).string(message.eventName);
    }
    if (message.consumerService !== "") {
      writer.uint32(26).string(message.consumerService);
    }
    if (message.lastError !== "") {
      writer.uint32(34).string(message.lastError);
    }
    if (message.dlqAtUnixMs !== 0) {
      writer.uint32(40).int64(message.dlqAtUnixMs);
    }
    if (message.replayCount !== 0) {
      writer.uint32(48).int32(message.replayCount);
    }
    if (message.totalAttempts !== 0) {
      writer.uint32(56).int32(message.totalAttempts);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DlqEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDlqEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.eventName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.consumerService = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lastError = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.dlqAtUnixMs = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.replayCount = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.totalAttempts = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<DlqEntry>, I>>(base?: I): DlqEntry {
    return DlqEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DlqEntry>, I>>(object: I): DlqEntry {
    const message = createBaseDlqEntry();
    message.eventId = object.eventId ?? "";
    message.eventName = object.eventName ?? "";
    message.consumerService = object.consumerService ?? "";
    message.lastError = object.lastError ?? "";
    message.dlqAtUnixMs = object.dlqAtUnixMs ?? 0;
    message.replayCount = object.replayCount ?? 0;
    message.totalAttempts = object.totalAttempts ?? 0;
    return message;
  },
};

function createBaseListDlqResponse(): ListDlqResponse {
  return { entries: [], nextCursor: "" };
}

export const ListDlqResponse: MessageFns<ListDlqResponse> = {
  encode(message: ListDlqResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entries) {
      DlqEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextCursor !== "") {
      writer.uint32(18).string(message.nextCursor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListDlqResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListDlqResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entries.push(DlqEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nextCursor = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ListDlqResponse>, I>>(base?: I): ListDlqResponse {
    return ListDlqResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListDlqResponse>, I>>(object: I): ListDlqResponse {
    const message = createBaseListDlqResponse();
    message.entries = object.entries?.map((e) => DlqEntry.fromPartial(e)) || [];
    message.nextCursor = object.nextCursor ?? "";
    return message;
  },
};

export type EventsService = typeof EventsService;
export const EventsService = {
  publish: {
    path: "/servicebridge.v1.Events/Publish" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: PublishRequest): Buffer => Buffer.from(PublishRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PublishRequest => PublishRequest.decode(value),
    responseSerialize: (value: PublishResponse): Buffer => Buffer.from(PublishResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PublishResponse => PublishResponse.decode(value),
  },
  subscribe: {
    path: "/servicebridge.v1.Events/Subscribe" as const,
    requestStream: true as const,
    responseStream: true as const,
    requestSerialize: (value: SubscribeClientMessage): Buffer =>
      Buffer.from(SubscribeClientMessage.encode(value).finish()),
    requestDeserialize: (value: Buffer): SubscribeClientMessage => SubscribeClientMessage.decode(value),
    responseSerialize: (value: SubscribeServerMessage): Buffer =>
      Buffer.from(SubscribeServerMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer): SubscribeServerMessage => SubscribeServerMessage.decode(value),
  },
  replayDlq: {
    path: "/servicebridge.v1.Events/ReplayDlq" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ReplayDlqRequest): Buffer => Buffer.from(ReplayDlqRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ReplayDlqRequest => ReplayDlqRequest.decode(value),
    responseSerialize: (value: ReplayDlqResponse): Buffer => Buffer.from(ReplayDlqResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ReplayDlqResponse => ReplayDlqResponse.decode(value),
  },
  listDlq: {
    path: "/servicebridge.v1.Events/ListDlq" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListDlqRequest): Buffer => Buffer.from(ListDlqRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListDlqRequest => ListDlqRequest.decode(value),
    responseSerialize: (value: ListDlqResponse): Buffer => Buffer.from(ListDlqResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListDlqResponse => ListDlqResponse.decode(value),
  },
} as const;

export interface EventsServer extends UntypedServiceImplementation {
  publish: handleUnaryCall<PublishRequest, PublishResponse>;
  subscribe: handleBidiStreamingCall<SubscribeClientMessage, SubscribeServerMessage>;
  replayDlq: handleUnaryCall<ReplayDlqRequest, ReplayDlqResponse>;
  listDlq: handleUnaryCall<ListDlqRequest, ListDlqResponse>;
}

export interface EventsClient extends Client {
  publish(
    request: PublishRequest,
    callback: (error: ServiceError | null, response: PublishResponse) => void,
  ): ClientUnaryCall;
  publish(
    request: PublishRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PublishResponse) => void,
  ): ClientUnaryCall;
  publish(
    request: PublishRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PublishResponse) => void,
  ): ClientUnaryCall;
  subscribe(): ClientDuplexStream<SubscribeClientMessage, SubscribeServerMessage>;
  subscribe(options: Partial<CallOptions>): ClientDuplexStream<SubscribeClientMessage, SubscribeServerMessage>;
  subscribe(
    metadata: Metadata,
    options?: Partial<CallOptions>,
  ): ClientDuplexStream<SubscribeClientMessage, SubscribeServerMessage>;
  replayDlq(
    request: ReplayDlqRequest,
    callback: (error: ServiceError | null, response: ReplayDlqResponse) => void,
  ): ClientUnaryCall;
  replayDlq(
    request: ReplayDlqRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ReplayDlqResponse) => void,
  ): ClientUnaryCall;
  replayDlq(
    request: ReplayDlqRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ReplayDlqResponse) => void,
  ): ClientUnaryCall;
  listDlq(
    request: ListDlqRequest,
    callback: (error: ServiceError | null, response: ListDlqResponse) => void,
  ): ClientUnaryCall;
  listDlq(
    request: ListDlqRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListDlqResponse) => void,
  ): ClientUnaryCall;
  listDlq(
    request: ListDlqRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListDlqResponse) => void,
  ): ClientUnaryCall;
}

export const EventsClient = makeGenericClientConstructor(EventsService, "servicebridge.v1.Events") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): EventsClient;
  service: typeof EventsService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
