// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: servicebridge/v1/jobs.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export interface JobsSubscribeRequest {
  serviceId: string;
  instanceId: string;
}

export interface JobExecution {
  executionId: string;
  jobDefinitionId: string;
  jobName: string;
  scheduledAtUnixMs: number;
  localScheduledAtUnixMs: number;
  attempt: number;
  leaseEpoch: number;
  idempotencyKey: string;
  /** "traceID-parentOpID" canonical format (ADR 0006 §3) */
  xSbTrace: string;
}

export interface JobResultRequest {
  executionId: string;
  instanceId: string;
  leaseEpoch: number;
  success?: JobSuccess | undefined;
  failure?: JobFailure | undefined;
}

export interface JobSuccess {
}

export interface JobFailure {
  errorMessage: string;
  retryable: boolean;
}

export interface JobResultResponse {
  accepted: boolean;
}

export interface JobsHeartbeatRequest {
  serviceId: string;
  instanceId: string;
}

export interface JobsHeartbeatResponse {
}

function createBaseJobsSubscribeRequest(): JobsSubscribeRequest {
  return { serviceId: "", instanceId: "" };
}

export const JobsSubscribeRequest: MessageFns<JobsSubscribeRequest> = {
  encode(message: JobsSubscribeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serviceId !== "") {
      writer.uint32(10).string(message.serviceId);
    }
    if (message.instanceId !== "") {
      writer.uint32(18).string(message.instanceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobsSubscribeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobsSubscribeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<JobsSubscribeRequest>, I>>(base?: I): JobsSubscribeRequest {
    return JobsSubscribeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobsSubscribeRequest>, I>>(object: I): JobsSubscribeRequest {
    const message = createBaseJobsSubscribeRequest();
    message.serviceId = object.serviceId ?? "";
    message.instanceId = object.instanceId ?? "";
    return message;
  },
};

function createBaseJobExecution(): JobExecution {
  return {
    executionId: "",
    jobDefinitionId: "",
    jobName: "",
    scheduledAtUnixMs: 0,
    localScheduledAtUnixMs: 0,
    attempt: 0,
    leaseEpoch: 0,
    idempotencyKey: "",
    xSbTrace: "",
  };
}

export const JobExecution: MessageFns<JobExecution> = {
  encode(message: JobExecution, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.executionId !== "") {
      writer.uint32(10).string(message.executionId);
    }
    if (message.jobDefinitionId !== "") {
      writer.uint32(18).string(message.jobDefinitionId);
    }
    if (message.jobName !== "") {
      writer.uint32(26).string(message.jobName);
    }
    if (message.scheduledAtUnixMs !== 0) {
      writer.uint32(32).int64(message.scheduledAtUnixMs);
    }
    if (message.localScheduledAtUnixMs !== 0) {
      writer.uint32(40).int64(message.localScheduledAtUnixMs);
    }
    if (message.attempt !== 0) {
      writer.uint32(48).uint32(message.attempt);
    }
    if (message.leaseEpoch !== 0) {
      writer.uint32(56).uint64(message.leaseEpoch);
    }
    if (message.idempotencyKey !== "") {
      writer.uint32(66).string(message.idempotencyKey);
    }
    if (message.xSbTrace !== "") {
      writer.uint32(74).string(message.xSbTrace);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobExecution {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobExecution();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.executionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.jobDefinitionId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.jobName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.scheduledAtUnixMs = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.localScheduledAtUnixMs = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.attempt = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.leaseEpoch = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.xSbTrace = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<JobExecution>, I>>(base?: I): JobExecution {
    return JobExecution.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobExecution>, I>>(object: I): JobExecution {
    const message = createBaseJobExecution();
    message.executionId = object.executionId ?? "";
    message.jobDefinitionId = object.jobDefinitionId ?? "";
    message.jobName = object.jobName ?? "";
    message.scheduledAtUnixMs = object.scheduledAtUnixMs ?? 0;
    message.localScheduledAtUnixMs = object.localScheduledAtUnixMs ?? 0;
    message.attempt = object.attempt ?? 0;
    message.leaseEpoch = object.leaseEpoch ?? 0;
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.xSbTrace = object.xSbTrace ?? "";
    return message;
  },
};

function createBaseJobResultRequest(): JobResultRequest {
  return { executionId: "", instanceId: "", leaseEpoch: 0, success: undefined, failure: undefined };
}

export const JobResultRequest: MessageFns<JobResultRequest> = {
  encode(message: JobResultRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.executionId !== "") {
      writer.uint32(10).string(message.executionId);
    }
    if (message.instanceId !== "") {
      writer.uint32(18).string(message.instanceId);
    }
    if (message.leaseEpoch !== 0) {
      writer.uint32(24).uint64(message.leaseEpoch);
    }
    if (message.success !== undefined) {
      JobSuccess.encode(message.success, writer.uint32(34).fork()).join();
    }
    if (message.failure !== undefined) {
      JobFailure.encode(message.failure, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobResultRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobResultRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.executionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.leaseEpoch = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.success = JobSuccess.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.failure = JobFailure.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<JobResultRequest>, I>>(base?: I): JobResultRequest {
    return JobResultRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobResultRequest>, I>>(object: I): JobResultRequest {
    const message = createBaseJobResultRequest();
    message.executionId = object.executionId ?? "";
    message.instanceId = object.instanceId ?? "";
    message.leaseEpoch = object.leaseEpoch ?? 0;
    message.success = (object.success !== undefined && object.success !== null)
      ? JobSuccess.fromPartial(object.success)
      : undefined;
    message.failure = (object.failure !== undefined && object.failure !== null)
      ? JobFailure.fromPartial(object.failure)
      : undefined;
    return message;
  },
};

function createBaseJobSuccess(): JobSuccess {
  return {};
}

export const JobSuccess: MessageFns<JobSuccess> = {
  encode(_: JobSuccess, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobSuccess {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobSuccess();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<JobSuccess>, I>>(base?: I): JobSuccess {
    return JobSuccess.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobSuccess>, I>>(_: I): JobSuccess {
    const message = createBaseJobSuccess();
    return message;
  },
};

function createBaseJobFailure(): JobFailure {
  return { errorMessage: "", retryable: false };
}

export const JobFailure: MessageFns<JobFailure> = {
  encode(message: JobFailure, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.errorMessage !== "") {
      writer.uint32(10).string(message.errorMessage);
    }
    if (message.retryable !== false) {
      writer.uint32(16).bool(message.retryable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobFailure {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobFailure();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.retryable = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<JobFailure>, I>>(base?: I): JobFailure {
    return JobFailure.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobFailure>, I>>(object: I): JobFailure {
    const message = createBaseJobFailure();
    message.errorMessage = object.errorMessage ?? "";
    message.retryable = object.retryable ?? false;
    return message;
  },
};

function createBaseJobResultResponse(): JobResultResponse {
  return { accepted: false };
}

export const JobResultResponse: MessageFns<JobResultResponse> = {
  encode(message: JobResultResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accepted !== false) {
      writer.uint32(8).bool(message.accepted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobResultResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobResultResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.accepted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<JobResultResponse>, I>>(base?: I): JobResultResponse {
    return JobResultResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobResultResponse>, I>>(object: I): JobResultResponse {
    const message = createBaseJobResultResponse();
    message.accepted = object.accepted ?? false;
    return message;
  },
};

function createBaseJobsHeartbeatRequest(): JobsHeartbeatRequest {
  return { serviceId: "", instanceId: "" };
}

export const JobsHeartbeatRequest: MessageFns<JobsHeartbeatRequest> = {
  encode(message: JobsHeartbeatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serviceId !== "") {
      writer.uint32(10).string(message.serviceId);
    }
    if (message.instanceId !== "") {
      writer.uint32(18).string(message.instanceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobsHeartbeatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobsHeartbeatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<JobsHeartbeatRequest>, I>>(base?: I): JobsHeartbeatRequest {
    return JobsHeartbeatRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobsHeartbeatRequest>, I>>(object: I): JobsHeartbeatRequest {
    const message = createBaseJobsHeartbeatRequest();
    message.serviceId = object.serviceId ?? "";
    message.instanceId = object.instanceId ?? "";
    return message;
  },
};

function createBaseJobsHeartbeatResponse(): JobsHeartbeatResponse {
  return {};
}

export const JobsHeartbeatResponse: MessageFns<JobsHeartbeatResponse> = {
  encode(_: JobsHeartbeatResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobsHeartbeatResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobsHeartbeatResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<JobsHeartbeatResponse>, I>>(base?: I): JobsHeartbeatResponse {
    return JobsHeartbeatResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobsHeartbeatResponse>, I>>(_: I): JobsHeartbeatResponse {
    const message = createBaseJobsHeartbeatResponse();
    return message;
  },
};

/**
 * Jobs — data-plane RPCs for runtime-triggered scheduled tasks.
 *
 * Registration is NOT here: it flows through Registry.RegisterAndWatch as
 * IncomingMethod{type=METHOD_TYPE_JOB, ...} just like RPC / Event / Workflow.
 * The canonical job spec (trigger, catchup, overlap, deps, retry policy)
 * travels in IncomingMethod.input_schema_json. Mirrors workflow's pattern.
 */
export type JobsService = typeof JobsService;
export const JobsService = {
  /** Owner-side: server-stream of JobExecution pushes for this instance. */
  subscribe: {
    path: "/servicebridge.v1.Jobs/Subscribe" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: JobsSubscribeRequest): Buffer => Buffer.from(JobsSubscribeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JobsSubscribeRequest => JobsSubscribeRequest.decode(value),
    responseSerialize: (value: JobExecution): Buffer => Buffer.from(JobExecution.encode(value).finish()),
    responseDeserialize: (value: Buffer): JobExecution => JobExecution.decode(value),
  },
  /** Owner-side: report execution outcome. Stale ACK is silently dropped. */
  jobResult: {
    path: "/servicebridge.v1.Jobs/JobResult" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JobResultRequest): Buffer => Buffer.from(JobResultRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JobResultRequest => JobResultRequest.decode(value),
    responseSerialize: (value: JobResultResponse): Buffer => Buffer.from(JobResultResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): JobResultResponse => JobResultResponse.decode(value),
  },
  /** Owner-side: application-level heartbeat. */
  heartbeat: {
    path: "/servicebridge.v1.Jobs/Heartbeat" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JobsHeartbeatRequest): Buffer => Buffer.from(JobsHeartbeatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JobsHeartbeatRequest => JobsHeartbeatRequest.decode(value),
    responseSerialize: (value: JobsHeartbeatResponse): Buffer =>
      Buffer.from(JobsHeartbeatResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): JobsHeartbeatResponse => JobsHeartbeatResponse.decode(value),
  },
} as const;

export interface JobsServer extends UntypedServiceImplementation {
  /** Owner-side: server-stream of JobExecution pushes for this instance. */
  subscribe: handleServerStreamingCall<JobsSubscribeRequest, JobExecution>;
  /** Owner-side: report execution outcome. Stale ACK is silently dropped. */
  jobResult: handleUnaryCall<JobResultRequest, JobResultResponse>;
  /** Owner-side: application-level heartbeat. */
  heartbeat: handleUnaryCall<JobsHeartbeatRequest, JobsHeartbeatResponse>;
}

export interface JobsClient extends Client {
  /** Owner-side: server-stream of JobExecution pushes for this instance. */
  subscribe(request: JobsSubscribeRequest, options?: Partial<CallOptions>): ClientReadableStream<JobExecution>;
  subscribe(
    request: JobsSubscribeRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<JobExecution>;
  /** Owner-side: report execution outcome. Stale ACK is silently dropped. */
  jobResult(
    request: JobResultRequest,
    callback: (error: ServiceError | null, response: JobResultResponse) => void,
  ): ClientUnaryCall;
  jobResult(
    request: JobResultRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: JobResultResponse) => void,
  ): ClientUnaryCall;
  jobResult(
    request: JobResultRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: JobResultResponse) => void,
  ): ClientUnaryCall;
  /** Owner-side: application-level heartbeat. */
  heartbeat(
    request: JobsHeartbeatRequest,
    callback: (error: ServiceError | null, response: JobsHeartbeatResponse) => void,
  ): ClientUnaryCall;
  heartbeat(
    request: JobsHeartbeatRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: JobsHeartbeatResponse) => void,
  ): ClientUnaryCall;
  heartbeat(
    request: JobsHeartbeatRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: JobsHeartbeatResponse) => void,
  ): ClientUnaryCall;
}

export const JobsClient = makeGenericClientConstructor(JobsService, "servicebridge.v1.Jobs") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): JobsClient;
  service: typeof JobsService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
