// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: servicebridge/v1/registry.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type handleServerStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export enum MethodType {
  METHOD_TYPE_UNSPECIFIED = 0,
  METHOD_TYPE_RPC = 1,
  METHOD_TYPE_EVENT = 2,
  METHOD_TYPE_WORKFLOW = 3,
  METHOD_TYPE_JOB = 4,
  METHOD_TYPE_HTTP = 5,
  UNRECOGNIZED = -1,
}

/**
 * CaptureMode is one channel's payload capture policy. The runtime is the
 * single authority: it resolves each channel's mode from runtime settings and
 * pushes the whole CaptureModes set to every SDK over RegisterAndWatch. SDKs
 * apply the mode for an op's channel as its effective capture mode; a per-handler
 * override may only narrow it (privacy ordering NONE < ERRORS < ALL), never
 * widen it.
 */
export enum CaptureMode {
  CAPTURE_MODE_UNSPECIFIED = 0,
  CAPTURE_MODE_ALL = 1,
  CAPTURE_MODE_ERRORS = 2,
  CAPTURE_MODE_NONE = 3,
  UNRECOGNIZED = -1,
}

/**
 * CaptureModes carries the per-channel payload capture policy pushed to SDKs.
 * One CaptureMode per op channel; the runtime resolves each from its matching
 * <channel>.payload_capture setting. The SDK picks the mode for an op's channel.
 * Jobs carry no input/output payload (JobExecution has no args, the handler
 * returns void), so the job channel has no capture mode — field 5 is reserved.
 */
export interface CaptureModes {
  rpc: CaptureMode;
  http: CaptureMode;
  event: CaptureMode;
  workflow: CaptureMode;
  /**
   * telemetry_enabled gates the telemetry transport on the SDK side. Resolved
   * from the telemetry.enable runtime setting. SDK stops/skips the transport
   * when false; default fail-safe before first snapshot is enabled=true.
   */
  telemetryEnabled: boolean;
  /**
   * payload_max_bytes is the per-direction byte cap for captured payloads,
   * resolved from telemetry.payload_max_bytes. SDK uses this instead of any
   * constructor-provided value. Fallback before first snapshot: 65536.
   */
  payloadMaxBytes: number;
}

export interface IncomingMethod {
  type: MethodType;
  name: string;
  inputSchemaJson: Buffer;
  outputSchemaJson: Buffer;
  streaming: boolean;
  /**
   * SDK-supplied contract hash (hex SHA-256). Runtime stores opaque,
   * does not recompute. Empty for non-RPC method types (event/workflow/job/http).
   */
  contractHash: string;
}

export interface PublishedEvent {
  name: string;
  schemaJson: Buffer;
  /**
   * SDK-supplied contract hash (hex SHA-256) of the Protobuf descriptor for
   * this event's payload schema. Empty when the publisher declared the event
   * without a schema. Runtime stores opaque, does not recompute (ADR-0001).
   */
  contractHash: string;
}

export interface OutgoingDep {
  serviceName: string;
  methodName: string;
  type: MethodType;
}

export interface EventSubscription {
  pattern: string;
  durable: boolean;
}

export interface RegisterRequest {
  incoming: IncomingMethod[];
  published: PublishedEvent[];
  outgoing: OutgoingDep[];
  callEndpoint: string;
  eventSubscriptions: EventSubscription[];
  /**
   * Public HTTP host:port of this SDK instance (ADR 0001 — HTTP lives in user
   * app). Used only by Service Map / Discovery; runtime does not proxy HTTP.
   * Empty when SDK has no HTTP integration registered.
   */
  httpEndpoint: string;
}

export interface MethodDescriptor {
  serviceName: string;
  serviceId: string;
  instanceId: string;
  type: MethodType;
  name: string;
  contractHash: string;
  published: boolean;
  inputSchema: Buffer;
  outputSchema: Buffer;
  streaming: boolean;
}

export interface ServiceInstanceInfo {
  instanceId: string;
  serviceId: string;
  serviceName: string;
  callEndpoint: string;
  status: string;
  /**
   * Public HTTP host:port of this instance (ADR 0001). Empty when instance has
   * no HTTP integration or after disconnect.
   */
  httpEndpoint: string;
  /**
   * Start of the current unhealthy window for this instance (ADR-0007).
   * Unix-ms timestamp; 0 when the instance is healthy. SDK-side LB treats it as a hint.
   */
  isUnhealthySinceUnixMs: number;
}

export interface RegistrySnapshot {
  methods: MethodDescriptor[];
  instances: ServiceInstanceInfo[];
  /**
   * ── Service-map enrichment (ADR-0004) ────────────────────────────────────
   * Per-service event subscriptions visible to the caller. Combined with
   * event publishers from `methods` (METHOD_TYPE_EVENT + published=true) this
   * lets UI / SDK draw the full pub/sub graph including wildcards.
   */
  eventSubscriptions: EventSubscriptionDescriptor[];
  /**
   * Per-service outgoing call declarations from sb.service(...). One row per
   * (caller_service, target_service, target_method, target_type) tuple.
   */
  outgoingCalls: OutgoingCallDescriptor[];
  /**
   * Policy evaluation for the caller of this RegisterAndWatch stream — the
   * caller's effective capabilities + rules + per-declaration warnings.
   */
  policy?:
    | PolicyEvaluation
    | undefined;
  /**
   * Per-channel payload capture modes. Always stamped on the snapshot so the
   * SDK has an effective mode per channel from the first frame (before any
   * update).
   */
  captureModes?: CaptureModes | undefined;
}

export interface RegistryUpdate {
  added: MethodDescriptor[];
  removed: MethodDescriptor[];
  addedInstances: ServiceInstanceInfo[];
  removedInstances: ServiceInstanceInfo[];
  /** Same enrichment as RegistrySnapshot.* but incremental. */
  addedEventSubscriptions: EventSubscriptionDescriptor[];
  removedEventSubscriptions: EventSubscriptionDescriptor[];
  addedOutgoingCalls: OutgoingCallDescriptor[];
  removedOutgoingCalls: OutgoingCallDescriptor[];
  /**
   * When policy changes (NOTIFY policy_changed touches caller), runtime
   * re-emits the full PolicyEvaluation. Not incremental on purpose: policy
   * edits are rare and the evaluation is small.
   */
  policy?:
    | PolicyEvaluation
    | undefined;
  /**
   * Derived from per-field diff after a policy push. peer_id is in
   * added_peers when it first appears in the caller's scope; in removed_peers
   * when the last method/instance/subscription from that peer disappears from
   * scope. SDK uses these to update serviceMap and close stale direct-conns.
   */
  addedPeers: string[];
  removedPeers: string[];
  /**
   * Re-emitted full per-channel capture modes when any channel's mode changes.
   * Like policy, not incremental: the whole set is sent on change.
   */
  captureModes?: CaptureModes | undefined;
}

export interface RegistryEvent {
  snapshot?: RegistrySnapshot | undefined;
  update?: RegistryUpdate | undefined;
}

export interface EventSubscriptionDescriptor {
  serviceId: string;
  serviceName: string;
  /** AMQP pattern, supports * and # */
  pattern: string;
  durable: boolean;
}

export interface OutgoingCallDescriptor {
  callerServiceId: string;
  callerServiceName: string;
  targetServiceId: string;
  targetServiceName: string;
  targetMethod: string;
  /** RPC, WORKFLOW, HTTP */
  targetType: MethodType;
}

export interface PolicyEvaluation {
  /**
   * Capability flags currently enabled for the caller — names of the four
   * booleans on services that are TRUE: "rpc.handle", "event.handle",
   * "workflow.handle", "job.handle".
   */
  capabilities: string[];
  /** The caller's effective egress rules. */
  egress: PolicyRule[];
  /** The caller's effective acceptance rules. */
  acceptance: PolicyRule[];
  /** Per-declaration violations from the most recent registration. */
  warnings: PolicyViolation[];
}

export interface PolicyRule {
  /**
   * 'rpc.call' | 'workflow.run' | 'event.publish' for egress;
   * 'rpc.handle' | 'workflow.handle' | 'event.handle' for acceptance.
   */
  action: string;
  /**
   * For rpc.* /workflow.*: peer service UUID (target for egress, caller for
   * acceptance). Empty string for event.* (no per-service routing).
   */
  peerServiceId: string;
  /** Human-readable peer service name (for UI / sb-policy show). */
  peerServiceName: string;
  /**
   * Method name pattern (literal or '*') for rpc.* /workflow.*; AMQP pattern
   * for event.*.
   */
  targetName: string;
}

export interface PolicyViolation {
  /**
   * Declaration type, e.g. 'rpc.call', 'event.handle', 'event.publish',
   * 'rpc.handle' (capability), etc.
   */
  declaration: string;
  /** Concrete value, e.g. 'payments/charge', 'orders.*'. */
  value: string;
  /** 'capability' | 'self_egress' | 'self_acceptance' | 'peer_acceptance'. */
  denySide: string;
  /** Human-readable explanation. */
  reason: string;
}

function createBaseCaptureModes(): CaptureModes {
  return { rpc: 0, http: 0, event: 0, workflow: 0, telemetryEnabled: false, payloadMaxBytes: 0 };
}

export const CaptureModes: MessageFns<CaptureModes> = {
  encode(message: CaptureModes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rpc !== 0) {
      writer.uint32(8).int32(message.rpc);
    }
    if (message.http !== 0) {
      writer.uint32(16).int32(message.http);
    }
    if (message.event !== 0) {
      writer.uint32(24).int32(message.event);
    }
    if (message.workflow !== 0) {
      writer.uint32(32).int32(message.workflow);
    }
    if (message.telemetryEnabled !== false) {
      writer.uint32(48).bool(message.telemetryEnabled);
    }
    if (message.payloadMaxBytes !== 0) {
      writer.uint32(56).int32(message.payloadMaxBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CaptureModes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCaptureModes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.rpc = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.http = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.event = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.workflow = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.telemetryEnabled = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.payloadMaxBytes = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CaptureModes>, I>>(base?: I): CaptureModes {
    return CaptureModes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CaptureModes>, I>>(object: I): CaptureModes {
    const message = createBaseCaptureModes();
    message.rpc = object.rpc ?? 0;
    message.http = object.http ?? 0;
    message.event = object.event ?? 0;
    message.workflow = object.workflow ?? 0;
    message.telemetryEnabled = object.telemetryEnabled ?? false;
    message.payloadMaxBytes = object.payloadMaxBytes ?? 0;
    return message;
  },
};

function createBaseIncomingMethod(): IncomingMethod {
  return {
    type: 0,
    name: "",
    inputSchemaJson: Buffer.alloc(0),
    outputSchemaJson: Buffer.alloc(0),
    streaming: false,
    contractHash: "",
  };
}

export const IncomingMethod: MessageFns<IncomingMethod> = {
  encode(message: IncomingMethod, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.inputSchemaJson.length !== 0) {
      writer.uint32(26).bytes(message.inputSchemaJson);
    }
    if (message.outputSchemaJson.length !== 0) {
      writer.uint32(34).bytes(message.outputSchemaJson);
    }
    if (message.streaming !== false) {
      writer.uint32(40).bool(message.streaming);
    }
    if (message.contractHash !== "") {
      writer.uint32(50).string(message.contractHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IncomingMethod {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIncomingMethod();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.inputSchemaJson = Buffer.from(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.outputSchemaJson = Buffer.from(reader.bytes());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.streaming = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.contractHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<IncomingMethod>, I>>(base?: I): IncomingMethod {
    return IncomingMethod.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IncomingMethod>, I>>(object: I): IncomingMethod {
    const message = createBaseIncomingMethod();
    message.type = object.type ?? 0;
    message.name = object.name ?? "";
    message.inputSchemaJson = object.inputSchemaJson ?? Buffer.alloc(0);
    message.outputSchemaJson = object.outputSchemaJson ?? Buffer.alloc(0);
    message.streaming = object.streaming ?? false;
    message.contractHash = object.contractHash ?? "";
    return message;
  },
};

function createBasePublishedEvent(): PublishedEvent {
  return { name: "", schemaJson: Buffer.alloc(0), contractHash: "" };
}

export const PublishedEvent: MessageFns<PublishedEvent> = {
  encode(message: PublishedEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.schemaJson.length !== 0) {
      writer.uint32(18).bytes(message.schemaJson);
    }
    if (message.contractHash !== "") {
      writer.uint32(26).string(message.contractHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PublishedEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublishedEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.schemaJson = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contractHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PublishedEvent>, I>>(base?: I): PublishedEvent {
    return PublishedEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PublishedEvent>, I>>(object: I): PublishedEvent {
    const message = createBasePublishedEvent();
    message.name = object.name ?? "";
    message.schemaJson = object.schemaJson ?? Buffer.alloc(0);
    message.contractHash = object.contractHash ?? "";
    return message;
  },
};

function createBaseOutgoingDep(): OutgoingDep {
  return { serviceName: "", methodName: "", type: 0 };
}

export const OutgoingDep: MessageFns<OutgoingDep> = {
  encode(message: OutgoingDep, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serviceName !== "") {
      writer.uint32(10).string(message.serviceName);
    }
    if (message.methodName !== "") {
      writer.uint32(18).string(message.methodName);
    }
    if (message.type !== 0) {
      writer.uint32(24).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutgoingDep {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutgoingDep();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serviceName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.methodName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OutgoingDep>, I>>(base?: I): OutgoingDep {
    return OutgoingDep.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OutgoingDep>, I>>(object: I): OutgoingDep {
    const message = createBaseOutgoingDep();
    message.serviceName = object.serviceName ?? "";
    message.methodName = object.methodName ?? "";
    message.type = object.type ?? 0;
    return message;
  },
};

function createBaseEventSubscription(): EventSubscription {
  return { pattern: "", durable: false };
}

export const EventSubscription: MessageFns<EventSubscription> = {
  encode(message: EventSubscription, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pattern !== "") {
      writer.uint32(10).string(message.pattern);
    }
    if (message.durable !== false) {
      writer.uint32(16).bool(message.durable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventSubscription {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventSubscription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pattern = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.durable = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EventSubscription>, I>>(base?: I): EventSubscription {
    return EventSubscription.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventSubscription>, I>>(object: I): EventSubscription {
    const message = createBaseEventSubscription();
    message.pattern = object.pattern ?? "";
    message.durable = object.durable ?? false;
    return message;
  },
};

function createBaseRegisterRequest(): RegisterRequest {
  return { incoming: [], published: [], outgoing: [], callEndpoint: "", eventSubscriptions: [], httpEndpoint: "" };
}

export const RegisterRequest: MessageFns<RegisterRequest> = {
  encode(message: RegisterRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.incoming) {
      IncomingMethod.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.published) {
      PublishedEvent.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.outgoing) {
      OutgoingDep.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.callEndpoint !== "") {
      writer.uint32(34).string(message.callEndpoint);
    }
    for (const v of message.eventSubscriptions) {
      EventSubscription.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.httpEndpoint !== "") {
      writer.uint32(50).string(message.httpEndpoint);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.incoming.push(IncomingMethod.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.published.push(PublishedEvent.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.outgoing.push(OutgoingDep.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.callEndpoint = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.eventSubscriptions.push(EventSubscription.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.httpEndpoint = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RegisterRequest>, I>>(base?: I): RegisterRequest {
    return RegisterRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterRequest>, I>>(object: I): RegisterRequest {
    const message = createBaseRegisterRequest();
    message.incoming = object.incoming?.map((e) => IncomingMethod.fromPartial(e)) || [];
    message.published = object.published?.map((e) => PublishedEvent.fromPartial(e)) || [];
    message.outgoing = object.outgoing?.map((e) => OutgoingDep.fromPartial(e)) || [];
    message.callEndpoint = object.callEndpoint ?? "";
    message.eventSubscriptions = object.eventSubscriptions?.map((e) => EventSubscription.fromPartial(e)) || [];
    message.httpEndpoint = object.httpEndpoint ?? "";
    return message;
  },
};

function createBaseMethodDescriptor(): MethodDescriptor {
  return {
    serviceName: "",
    serviceId: "",
    instanceId: "",
    type: 0,
    name: "",
    contractHash: "",
    published: false,
    inputSchema: Buffer.alloc(0),
    outputSchema: Buffer.alloc(0),
    streaming: false,
  };
}

export const MethodDescriptor: MessageFns<MethodDescriptor> = {
  encode(message: MethodDescriptor, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serviceName !== "") {
      writer.uint32(10).string(message.serviceName);
    }
    if (message.serviceId !== "") {
      writer.uint32(18).string(message.serviceId);
    }
    if (message.instanceId !== "") {
      writer.uint32(26).string(message.instanceId);
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    if (message.name !== "") {
      writer.uint32(42).string(message.name);
    }
    if (message.contractHash !== "") {
      writer.uint32(50).string(message.contractHash);
    }
    if (message.published !== false) {
      writer.uint32(56).bool(message.published);
    }
    if (message.inputSchema.length !== 0) {
      writer.uint32(66).bytes(message.inputSchema);
    }
    if (message.outputSchema.length !== 0) {
      writer.uint32(74).bytes(message.outputSchema);
    }
    if (message.streaming !== false) {
      writer.uint32(80).bool(message.streaming);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MethodDescriptor {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMethodDescriptor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serviceName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.contractHash = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.published = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.inputSchema = Buffer.from(reader.bytes());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.outputSchema = Buffer.from(reader.bytes());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.streaming = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<MethodDescriptor>, I>>(base?: I): MethodDescriptor {
    return MethodDescriptor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MethodDescriptor>, I>>(object: I): MethodDescriptor {
    const message = createBaseMethodDescriptor();
    message.serviceName = object.serviceName ?? "";
    message.serviceId = object.serviceId ?? "";
    message.instanceId = object.instanceId ?? "";
    message.type = object.type ?? 0;
    message.name = object.name ?? "";
    message.contractHash = object.contractHash ?? "";
    message.published = object.published ?? false;
    message.inputSchema = object.inputSchema ?? Buffer.alloc(0);
    message.outputSchema = object.outputSchema ?? Buffer.alloc(0);
    message.streaming = object.streaming ?? false;
    return message;
  },
};

function createBaseServiceInstanceInfo(): ServiceInstanceInfo {
  return {
    instanceId: "",
    serviceId: "",
    serviceName: "",
    callEndpoint: "",
    status: "",
    httpEndpoint: "",
    isUnhealthySinceUnixMs: 0,
  };
}

export const ServiceInstanceInfo: MessageFns<ServiceInstanceInfo> = {
  encode(message: ServiceInstanceInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instanceId !== "") {
      writer.uint32(10).string(message.instanceId);
    }
    if (message.serviceId !== "") {
      writer.uint32(18).string(message.serviceId);
    }
    if (message.serviceName !== "") {
      writer.uint32(26).string(message.serviceName);
    }
    if (message.callEndpoint !== "") {
      writer.uint32(34).string(message.callEndpoint);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    if (message.httpEndpoint !== "") {
      writer.uint32(50).string(message.httpEndpoint);
    }
    if (message.isUnhealthySinceUnixMs !== 0) {
      writer.uint32(56).int64(message.isUnhealthySinceUnixMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServiceInstanceInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceInstanceInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.serviceName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.callEndpoint = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.httpEndpoint = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isUnhealthySinceUnixMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ServiceInstanceInfo>, I>>(base?: I): ServiceInstanceInfo {
    return ServiceInstanceInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceInstanceInfo>, I>>(object: I): ServiceInstanceInfo {
    const message = createBaseServiceInstanceInfo();
    message.instanceId = object.instanceId ?? "";
    message.serviceId = object.serviceId ?? "";
    message.serviceName = object.serviceName ?? "";
    message.callEndpoint = object.callEndpoint ?? "";
    message.status = object.status ?? "";
    message.httpEndpoint = object.httpEndpoint ?? "";
    message.isUnhealthySinceUnixMs = object.isUnhealthySinceUnixMs ?? 0;
    return message;
  },
};

function createBaseRegistrySnapshot(): RegistrySnapshot {
  return {
    methods: [],
    instances: [],
    eventSubscriptions: [],
    outgoingCalls: [],
    policy: undefined,
    captureModes: undefined,
  };
}

export const RegistrySnapshot: MessageFns<RegistrySnapshot> = {
  encode(message: RegistrySnapshot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.methods) {
      MethodDescriptor.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.instances) {
      ServiceInstanceInfo.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.eventSubscriptions) {
      EventSubscriptionDescriptor.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.outgoingCalls) {
      OutgoingCallDescriptor.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.policy !== undefined) {
      PolicyEvaluation.encode(message.policy, writer.uint32(42).fork()).join();
    }
    if (message.captureModes !== undefined) {
      CaptureModes.encode(message.captureModes, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegistrySnapshot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegistrySnapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.methods.push(MethodDescriptor.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instances.push(ServiceInstanceInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.eventSubscriptions.push(EventSubscriptionDescriptor.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.outgoingCalls.push(OutgoingCallDescriptor.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.policy = PolicyEvaluation.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.captureModes = CaptureModes.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RegistrySnapshot>, I>>(base?: I): RegistrySnapshot {
    return RegistrySnapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegistrySnapshot>, I>>(object: I): RegistrySnapshot {
    const message = createBaseRegistrySnapshot();
    message.methods = object.methods?.map((e) => MethodDescriptor.fromPartial(e)) || [];
    message.instances = object.instances?.map((e) => ServiceInstanceInfo.fromPartial(e)) || [];
    message.eventSubscriptions = object.eventSubscriptions?.map((e) => EventSubscriptionDescriptor.fromPartial(e)) ||
      [];
    message.outgoingCalls = object.outgoingCalls?.map((e) => OutgoingCallDescriptor.fromPartial(e)) || [];
    message.policy = (object.policy !== undefined && object.policy !== null)
      ? PolicyEvaluation.fromPartial(object.policy)
      : undefined;
    message.captureModes = (object.captureModes !== undefined && object.captureModes !== null)
      ? CaptureModes.fromPartial(object.captureModes)
      : undefined;
    return message;
  },
};

function createBaseRegistryUpdate(): RegistryUpdate {
  return {
    added: [],
    removed: [],
    addedInstances: [],
    removedInstances: [],
    addedEventSubscriptions: [],
    removedEventSubscriptions: [],
    addedOutgoingCalls: [],
    removedOutgoingCalls: [],
    policy: undefined,
    addedPeers: [],
    removedPeers: [],
    captureModes: undefined,
  };
}

export const RegistryUpdate: MessageFns<RegistryUpdate> = {
  encode(message: RegistryUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.added) {
      MethodDescriptor.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.removed) {
      MethodDescriptor.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.addedInstances) {
      ServiceInstanceInfo.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.removedInstances) {
      ServiceInstanceInfo.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.addedEventSubscriptions) {
      EventSubscriptionDescriptor.encode(v!, writer.uint32(42).fork()).join();
    }
    for (const v of message.removedEventSubscriptions) {
      EventSubscriptionDescriptor.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.addedOutgoingCalls) {
      OutgoingCallDescriptor.encode(v!, writer.uint32(58).fork()).join();
    }
    for (const v of message.removedOutgoingCalls) {
      OutgoingCallDescriptor.encode(v!, writer.uint32(66).fork()).join();
    }
    if (message.policy !== undefined) {
      PolicyEvaluation.encode(message.policy, writer.uint32(74).fork()).join();
    }
    for (const v of message.addedPeers) {
      writer.uint32(82).string(v!);
    }
    for (const v of message.removedPeers) {
      writer.uint32(90).string(v!);
    }
    if (message.captureModes !== undefined) {
      CaptureModes.encode(message.captureModes, writer.uint32(106).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegistryUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegistryUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.added.push(MethodDescriptor.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.removed.push(MethodDescriptor.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.addedInstances.push(ServiceInstanceInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.removedInstances.push(ServiceInstanceInfo.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.addedEventSubscriptions.push(EventSubscriptionDescriptor.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.removedEventSubscriptions.push(EventSubscriptionDescriptor.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.addedOutgoingCalls.push(OutgoingCallDescriptor.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.removedOutgoingCalls.push(OutgoingCallDescriptor.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.policy = PolicyEvaluation.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.addedPeers.push(reader.string());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.removedPeers.push(reader.string());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.captureModes = CaptureModes.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RegistryUpdate>, I>>(base?: I): RegistryUpdate {
    return RegistryUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegistryUpdate>, I>>(object: I): RegistryUpdate {
    const message = createBaseRegistryUpdate();
    message.added = object.added?.map((e) => MethodDescriptor.fromPartial(e)) || [];
    message.removed = object.removed?.map((e) => MethodDescriptor.fromPartial(e)) || [];
    message.addedInstances = object.addedInstances?.map((e) => ServiceInstanceInfo.fromPartial(e)) || [];
    message.removedInstances = object.removedInstances?.map((e) => ServiceInstanceInfo.fromPartial(e)) || [];
    message.addedEventSubscriptions =
      object.addedEventSubscriptions?.map((e) => EventSubscriptionDescriptor.fromPartial(e)) || [];
    message.removedEventSubscriptions =
      object.removedEventSubscriptions?.map((e) => EventSubscriptionDescriptor.fromPartial(e)) || [];
    message.addedOutgoingCalls = object.addedOutgoingCalls?.map((e) => OutgoingCallDescriptor.fromPartial(e)) || [];
    message.removedOutgoingCalls = object.removedOutgoingCalls?.map((e) => OutgoingCallDescriptor.fromPartial(e)) || [];
    message.policy = (object.policy !== undefined && object.policy !== null)
      ? PolicyEvaluation.fromPartial(object.policy)
      : undefined;
    message.addedPeers = object.addedPeers?.map((e) => e) || [];
    message.removedPeers = object.removedPeers?.map((e) => e) || [];
    message.captureModes = (object.captureModes !== undefined && object.captureModes !== null)
      ? CaptureModes.fromPartial(object.captureModes)
      : undefined;
    return message;
  },
};

function createBaseRegistryEvent(): RegistryEvent {
  return { snapshot: undefined, update: undefined };
}

export const RegistryEvent: MessageFns<RegistryEvent> = {
  encode(message: RegistryEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.snapshot !== undefined) {
      RegistrySnapshot.encode(message.snapshot, writer.uint32(10).fork()).join();
    }
    if (message.update !== undefined) {
      RegistryUpdate.encode(message.update, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegistryEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegistryEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.snapshot = RegistrySnapshot.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.update = RegistryUpdate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RegistryEvent>, I>>(base?: I): RegistryEvent {
    return RegistryEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegistryEvent>, I>>(object: I): RegistryEvent {
    const message = createBaseRegistryEvent();
    message.snapshot = (object.snapshot !== undefined && object.snapshot !== null)
      ? RegistrySnapshot.fromPartial(object.snapshot)
      : undefined;
    message.update = (object.update !== undefined && object.update !== null)
      ? RegistryUpdate.fromPartial(object.update)
      : undefined;
    return message;
  },
};

function createBaseEventSubscriptionDescriptor(): EventSubscriptionDescriptor {
  return { serviceId: "", serviceName: "", pattern: "", durable: false };
}

export const EventSubscriptionDescriptor: MessageFns<EventSubscriptionDescriptor> = {
  encode(message: EventSubscriptionDescriptor, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serviceId !== "") {
      writer.uint32(10).string(message.serviceId);
    }
    if (message.serviceName !== "") {
      writer.uint32(18).string(message.serviceName);
    }
    if (message.pattern !== "") {
      writer.uint32(26).string(message.pattern);
    }
    if (message.durable !== false) {
      writer.uint32(32).bool(message.durable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventSubscriptionDescriptor {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventSubscriptionDescriptor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serviceName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pattern = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.durable = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EventSubscriptionDescriptor>, I>>(base?: I): EventSubscriptionDescriptor {
    return EventSubscriptionDescriptor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventSubscriptionDescriptor>, I>>(object: I): EventSubscriptionDescriptor {
    const message = createBaseEventSubscriptionDescriptor();
    message.serviceId = object.serviceId ?? "";
    message.serviceName = object.serviceName ?? "";
    message.pattern = object.pattern ?? "";
    message.durable = object.durable ?? false;
    return message;
  },
};

function createBaseOutgoingCallDescriptor(): OutgoingCallDescriptor {
  return {
    callerServiceId: "",
    callerServiceName: "",
    targetServiceId: "",
    targetServiceName: "",
    targetMethod: "",
    targetType: 0,
  };
}

export const OutgoingCallDescriptor: MessageFns<OutgoingCallDescriptor> = {
  encode(message: OutgoingCallDescriptor, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callerServiceId !== "") {
      writer.uint32(10).string(message.callerServiceId);
    }
    if (message.callerServiceName !== "") {
      writer.uint32(18).string(message.callerServiceName);
    }
    if (message.targetServiceId !== "") {
      writer.uint32(26).string(message.targetServiceId);
    }
    if (message.targetServiceName !== "") {
      writer.uint32(34).string(message.targetServiceName);
    }
    if (message.targetMethod !== "") {
      writer.uint32(42).string(message.targetMethod);
    }
    if (message.targetType !== 0) {
      writer.uint32(48).int32(message.targetType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutgoingCallDescriptor {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutgoingCallDescriptor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callerServiceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.callerServiceName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.targetServiceId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.targetServiceName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.targetMethod = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.targetType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<OutgoingCallDescriptor>, I>>(base?: I): OutgoingCallDescriptor {
    return OutgoingCallDescriptor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OutgoingCallDescriptor>, I>>(object: I): OutgoingCallDescriptor {
    const message = createBaseOutgoingCallDescriptor();
    message.callerServiceId = object.callerServiceId ?? "";
    message.callerServiceName = object.callerServiceName ?? "";
    message.targetServiceId = object.targetServiceId ?? "";
    message.targetServiceName = object.targetServiceName ?? "";
    message.targetMethod = object.targetMethod ?? "";
    message.targetType = object.targetType ?? 0;
    return message;
  },
};

function createBasePolicyEvaluation(): PolicyEvaluation {
  return { capabilities: [], egress: [], acceptance: [], warnings: [] };
}

export const PolicyEvaluation: MessageFns<PolicyEvaluation> = {
  encode(message: PolicyEvaluation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.capabilities) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.egress) {
      PolicyRule.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.acceptance) {
      PolicyRule.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.warnings) {
      PolicyViolation.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PolicyEvaluation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePolicyEvaluation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.capabilities.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.egress.push(PolicyRule.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.acceptance.push(PolicyRule.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.warnings.push(PolicyViolation.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PolicyEvaluation>, I>>(base?: I): PolicyEvaluation {
    return PolicyEvaluation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PolicyEvaluation>, I>>(object: I): PolicyEvaluation {
    const message = createBasePolicyEvaluation();
    message.capabilities = object.capabilities?.map((e) => e) || [];
    message.egress = object.egress?.map((e) => PolicyRule.fromPartial(e)) || [];
    message.acceptance = object.acceptance?.map((e) => PolicyRule.fromPartial(e)) || [];
    message.warnings = object.warnings?.map((e) => PolicyViolation.fromPartial(e)) || [];
    return message;
  },
};

function createBasePolicyRule(): PolicyRule {
  return { action: "", peerServiceId: "", peerServiceName: "", targetName: "" };
}

export const PolicyRule: MessageFns<PolicyRule> = {
  encode(message: PolicyRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.action !== "") {
      writer.uint32(10).string(message.action);
    }
    if (message.peerServiceId !== "") {
      writer.uint32(18).string(message.peerServiceId);
    }
    if (message.peerServiceName !== "") {
      writer.uint32(26).string(message.peerServiceName);
    }
    if (message.targetName !== "") {
      writer.uint32(34).string(message.targetName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PolicyRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePolicyRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.peerServiceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.peerServiceName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.targetName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PolicyRule>, I>>(base?: I): PolicyRule {
    return PolicyRule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PolicyRule>, I>>(object: I): PolicyRule {
    const message = createBasePolicyRule();
    message.action = object.action ?? "";
    message.peerServiceId = object.peerServiceId ?? "";
    message.peerServiceName = object.peerServiceName ?? "";
    message.targetName = object.targetName ?? "";
    return message;
  },
};

function createBasePolicyViolation(): PolicyViolation {
  return { declaration: "", value: "", denySide: "", reason: "" };
}

export const PolicyViolation: MessageFns<PolicyViolation> = {
  encode(message: PolicyViolation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.declaration !== "") {
      writer.uint32(10).string(message.declaration);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    if (message.denySide !== "") {
      writer.uint32(26).string(message.denySide);
    }
    if (message.reason !== "") {
      writer.uint32(34).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PolicyViolation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePolicyViolation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.declaration = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.denySide = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<PolicyViolation>, I>>(base?: I): PolicyViolation {
    return PolicyViolation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PolicyViolation>, I>>(object: I): PolicyViolation {
    const message = createBasePolicyViolation();
    message.declaration = object.declaration ?? "";
    message.value = object.value ?? "";
    message.denySide = object.denySide ?? "";
    message.reason = object.reason ?? "";
    return message;
  },
};

export type RegistryService = typeof RegistryService;
export const RegistryService = {
  registerAndWatch: {
    path: "/servicebridge.v1.Registry/RegisterAndWatch" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: RegisterRequest): Buffer => Buffer.from(RegisterRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RegisterRequest => RegisterRequest.decode(value),
    responseSerialize: (value: RegistryEvent): Buffer => Buffer.from(RegistryEvent.encode(value).finish()),
    responseDeserialize: (value: Buffer): RegistryEvent => RegistryEvent.decode(value),
  },
} as const;

export interface RegistryServer extends UntypedServiceImplementation {
  registerAndWatch: handleServerStreamingCall<RegisterRequest, RegistryEvent>;
}

export interface RegistryClient extends Client {
  registerAndWatch(request: RegisterRequest, options?: Partial<CallOptions>): ClientReadableStream<RegistryEvent>;
  registerAndWatch(
    request: RegisterRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<RegistryEvent>;
}

export const RegistryClient = makeGenericClientConstructor(RegistryService, "servicebridge.v1.Registry") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): RegistryClient;
  service: typeof RegistryService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
