// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: servicebridge/v1/ui.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

/** Reserved for future filters (per-status, since-time, etc.). Empty for v1. */
export interface GetServiceGraphRequest {
}

export interface ServiceGraph {
  services: ServiceNode[];
}

export interface ServiceNode {
  serviceId: string;
  serviceName: string;
  /** 'active' | 'revoked' */
  serviceStatus: string;
  /** Capability flags (TRUE means service may register that handler type). */
  capRpcHandle: boolean;
  capEventHandle: boolean;
  capWorkflowHandle: boolean;
  capJobHandle: boolean;
  /** Registered handlers. */
  methods: UIMethod[];
  /** Live instances. */
  instances: UIInstance[];
  /** Outgoing calls declared by this service (sb.service deps). */
  outgoingCalls: UIOutgoing[];
  /** Durable event subscriptions of this service (may include wildcards). */
  eventSubscriptions: UIEventSubscription[];
  /** Policy rules attached to this service. Direction is 'E' or 'A'. */
  policyRules: UIPolicyRule[];
}

export interface UIMethod {
  name: string;
  /** 'rpc' | 'event' | 'workflow' | 'job' | 'http' */
  type: string;
  contractHash: string;
  streaming: boolean;
  /** true for events declared as publisher */
  published: boolean;
}

export interface UIInstance {
  instanceId: string;
  status: string;
  callEndpoint: string;
  httpEndpoint: string;
}

export interface UIOutgoing {
  targetServiceId: string;
  targetMethod: string;
  /** 'rpc' | 'workflow' | 'http' */
  targetType: string;
}

export interface UIEventSubscription {
  pattern: string;
  durable: boolean;
}

export interface UIPolicyRule {
  /** 'E' | 'A' */
  direction: string;
  /** rpc.call | rpc.handle | event.publish | ... */
  action: string;
  /** empty for event.* (no per-service routing) */
  analyticsPeerServiceId: string;
  targetName: string;
}

function createBaseGetServiceGraphRequest(): GetServiceGraphRequest {
  return {};
}

export const GetServiceGraphRequest: MessageFns<GetServiceGraphRequest> = {
  encode(_: GetServiceGraphRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetServiceGraphRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetServiceGraphRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<GetServiceGraphRequest>, I>>(base?: I): GetServiceGraphRequest {
    return GetServiceGraphRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetServiceGraphRequest>, I>>(_: I): GetServiceGraphRequest {
    const message = createBaseGetServiceGraphRequest();
    return message;
  },
};

function createBaseServiceGraph(): ServiceGraph {
  return { services: [] };
}

export const ServiceGraph: MessageFns<ServiceGraph> = {
  encode(message: ServiceGraph, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.services) {
      ServiceNode.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServiceGraph {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceGraph();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.services.push(ServiceNode.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ServiceGraph>, I>>(base?: I): ServiceGraph {
    return ServiceGraph.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceGraph>, I>>(object: I): ServiceGraph {
    const message = createBaseServiceGraph();
    message.services = object.services?.map((e) => ServiceNode.fromPartial(e)) || [];
    return message;
  },
};

function createBaseServiceNode(): ServiceNode {
  return {
    serviceId: "",
    serviceName: "",
    serviceStatus: "",
    capRpcHandle: false,
    capEventHandle: false,
    capWorkflowHandle: false,
    capJobHandle: false,
    methods: [],
    instances: [],
    outgoingCalls: [],
    eventSubscriptions: [],
    policyRules: [],
  };
}

export const ServiceNode: MessageFns<ServiceNode> = {
  encode(message: ServiceNode, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serviceId !== "") {
      writer.uint32(10).string(message.serviceId);
    }
    if (message.serviceName !== "") {
      writer.uint32(18).string(message.serviceName);
    }
    if (message.serviceStatus !== "") {
      writer.uint32(26).string(message.serviceStatus);
    }
    if (message.capRpcHandle !== false) {
      writer.uint32(32).bool(message.capRpcHandle);
    }
    if (message.capEventHandle !== false) {
      writer.uint32(40).bool(message.capEventHandle);
    }
    if (message.capWorkflowHandle !== false) {
      writer.uint32(48).bool(message.capWorkflowHandle);
    }
    if (message.capJobHandle !== false) {
      writer.uint32(56).bool(message.capJobHandle);
    }
    for (const v of message.methods) {
      UIMethod.encode(v!, writer.uint32(66).fork()).join();
    }
    for (const v of message.instances) {
      UIInstance.encode(v!, writer.uint32(74).fork()).join();
    }
    for (const v of message.outgoingCalls) {
      UIOutgoing.encode(v!, writer.uint32(82).fork()).join();
    }
    for (const v of message.eventSubscriptions) {
      UIEventSubscription.encode(v!, writer.uint32(90).fork()).join();
    }
    for (const v of message.policyRules) {
      UIPolicyRule.encode(v!, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServiceNode {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServiceNode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serviceName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.serviceStatus = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.capRpcHandle = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.capEventHandle = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.capWorkflowHandle = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.capJobHandle = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.methods.push(UIMethod.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.instances.push(UIInstance.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.outgoingCalls.push(UIOutgoing.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.eventSubscriptions.push(UIEventSubscription.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.policyRules.push(UIPolicyRule.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ServiceNode>, I>>(base?: I): ServiceNode {
    return ServiceNode.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServiceNode>, I>>(object: I): ServiceNode {
    const message = createBaseServiceNode();
    message.serviceId = object.serviceId ?? "";
    message.serviceName = object.serviceName ?? "";
    message.serviceStatus = object.serviceStatus ?? "";
    message.capRpcHandle = object.capRpcHandle ?? false;
    message.capEventHandle = object.capEventHandle ?? false;
    message.capWorkflowHandle = object.capWorkflowHandle ?? false;
    message.capJobHandle = object.capJobHandle ?? false;
    message.methods = object.methods?.map((e) => UIMethod.fromPartial(e)) || [];
    message.instances = object.instances?.map((e) => UIInstance.fromPartial(e)) || [];
    message.outgoingCalls = object.outgoingCalls?.map((e) => UIOutgoing.fromPartial(e)) || [];
    message.eventSubscriptions = object.eventSubscriptions?.map((e) => UIEventSubscription.fromPartial(e)) || [];
    message.policyRules = object.policyRules?.map((e) => UIPolicyRule.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUIMethod(): UIMethod {
  return { name: "", type: "", contractHash: "", streaming: false, published: false };
}

export const UIMethod: MessageFns<UIMethod> = {
  encode(message: UIMethod, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.contractHash !== "") {
      writer.uint32(26).string(message.contractHash);
    }
    if (message.streaming !== false) {
      writer.uint32(32).bool(message.streaming);
    }
    if (message.published !== false) {
      writer.uint32(40).bool(message.published);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UIMethod {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUIMethod();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contractHash = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.streaming = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.published = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<UIMethod>, I>>(base?: I): UIMethod {
    return UIMethod.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UIMethod>, I>>(object: I): UIMethod {
    const message = createBaseUIMethod();
    message.name = object.name ?? "";
    message.type = object.type ?? "";
    message.contractHash = object.contractHash ?? "";
    message.streaming = object.streaming ?? false;
    message.published = object.published ?? false;
    return message;
  },
};

function createBaseUIInstance(): UIInstance {
  return { instanceId: "", status: "", callEndpoint: "", httpEndpoint: "" };
}

export const UIInstance: MessageFns<UIInstance> = {
  encode(message: UIInstance, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instanceId !== "") {
      writer.uint32(10).string(message.instanceId);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.callEndpoint !== "") {
      writer.uint32(26).string(message.callEndpoint);
    }
    if (message.httpEndpoint !== "") {
      writer.uint32(34).string(message.httpEndpoint);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UIInstance {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUIInstance();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.callEndpoint = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.httpEndpoint = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<UIInstance>, I>>(base?: I): UIInstance {
    return UIInstance.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UIInstance>, I>>(object: I): UIInstance {
    const message = createBaseUIInstance();
    message.instanceId = object.instanceId ?? "";
    message.status = object.status ?? "";
    message.callEndpoint = object.callEndpoint ?? "";
    message.httpEndpoint = object.httpEndpoint ?? "";
    return message;
  },
};

function createBaseUIOutgoing(): UIOutgoing {
  return { targetServiceId: "", targetMethod: "", targetType: "" };
}

export const UIOutgoing: MessageFns<UIOutgoing> = {
  encode(message: UIOutgoing, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.targetServiceId !== "") {
      writer.uint32(10).string(message.targetServiceId);
    }
    if (message.targetMethod !== "") {
      writer.uint32(18).string(message.targetMethod);
    }
    if (message.targetType !== "") {
      writer.uint32(26).string(message.targetType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UIOutgoing {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUIOutgoing();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.targetServiceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.targetMethod = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.targetType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<UIOutgoing>, I>>(base?: I): UIOutgoing {
    return UIOutgoing.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UIOutgoing>, I>>(object: I): UIOutgoing {
    const message = createBaseUIOutgoing();
    message.targetServiceId = object.targetServiceId ?? "";
    message.targetMethod = object.targetMethod ?? "";
    message.targetType = object.targetType ?? "";
    return message;
  },
};

function createBaseUIEventSubscription(): UIEventSubscription {
  return { pattern: "", durable: false };
}

export const UIEventSubscription: MessageFns<UIEventSubscription> = {
  encode(message: UIEventSubscription, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pattern !== "") {
      writer.uint32(10).string(message.pattern);
    }
    if (message.durable !== false) {
      writer.uint32(16).bool(message.durable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UIEventSubscription {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUIEventSubscription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pattern = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.durable = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<UIEventSubscription>, I>>(base?: I): UIEventSubscription {
    return UIEventSubscription.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UIEventSubscription>, I>>(object: I): UIEventSubscription {
    const message = createBaseUIEventSubscription();
    message.pattern = object.pattern ?? "";
    message.durable = object.durable ?? false;
    return message;
  },
};

function createBaseUIPolicyRule(): UIPolicyRule {
  return { direction: "", action: "", analyticsPeerServiceId: "", targetName: "" };
}

export const UIPolicyRule: MessageFns<UIPolicyRule> = {
  encode(message: UIPolicyRule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.direction !== "") {
      writer.uint32(10).string(message.direction);
    }
    if (message.action !== "") {
      writer.uint32(18).string(message.action);
    }
    if (message.analyticsPeerServiceId !== "") {
      writer.uint32(26).string(message.analyticsPeerServiceId);
    }
    if (message.targetName !== "") {
      writer.uint32(34).string(message.targetName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UIPolicyRule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUIPolicyRule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.direction = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.analyticsPeerServiceId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.targetName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<UIPolicyRule>, I>>(base?: I): UIPolicyRule {
    return UIPolicyRule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UIPolicyRule>, I>>(object: I): UIPolicyRule {
    const message = createBaseUIPolicyRule();
    message.direction = object.direction ?? "";
    message.action = object.action ?? "";
    message.analyticsPeerServiceId = object.analyticsPeerServiceId ?? "";
    message.targetName = object.targetName ?? "";
    return message;
  },
};

/**
 * UI exposes the runtime's global topology view for the dashboard. NOT
 * reachable through the regular SDK API on purpose — only a dedicated UI
 * consumer (separate mTLS identity / SPIFFE role 'ui-dashboard' once roles
 * land) calls into this service.
 */
export type UIService = typeof UIService;
export const UIService = {
  /**
   * GetServiceGraph returns the full service topology in one shot: every
   * active service with its handlers, instances, outgoing declarations,
   * event subscriptions and policy rules. UI computes edges client-side from
   * these nodes (rpc.call <-> rpc.handle by name; event.publish <->
   * event.handle by topic-pattern).
   */
  getServiceGraph: {
    path: "/servicebridge.v1.UI/GetServiceGraph" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetServiceGraphRequest): Buffer =>
      Buffer.from(GetServiceGraphRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetServiceGraphRequest => GetServiceGraphRequest.decode(value),
    responseSerialize: (value: ServiceGraph): Buffer => Buffer.from(ServiceGraph.encode(value).finish()),
    responseDeserialize: (value: Buffer): ServiceGraph => ServiceGraph.decode(value),
  },
} as const;

export interface UIServer extends UntypedServiceImplementation {
  /**
   * GetServiceGraph returns the full service topology in one shot: every
   * active service with its handlers, instances, outgoing declarations,
   * event subscriptions and policy rules. UI computes edges client-side from
   * these nodes (rpc.call <-> rpc.handle by name; event.publish <->
   * event.handle by topic-pattern).
   */
  getServiceGraph: handleUnaryCall<GetServiceGraphRequest, ServiceGraph>;
}

export interface UIClient extends Client {
  /**
   * GetServiceGraph returns the full service topology in one shot: every
   * active service with its handlers, instances, outgoing declarations,
   * event subscriptions and policy rules. UI computes edges client-side from
   * these nodes (rpc.call <-> rpc.handle by name; event.publish <->
   * event.handle by topic-pattern).
   */
  getServiceGraph(
    request: GetServiceGraphRequest,
    callback: (error: ServiceError | null, response: ServiceGraph) => void,
  ): ClientUnaryCall;
  getServiceGraph(
    request: GetServiceGraphRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ServiceGraph) => void,
  ): ClientUnaryCall;
  getServiceGraph(
    request: GetServiceGraphRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ServiceGraph) => void,
  ): ClientUnaryCall;
}

export const UIClient = makeGenericClientConstructor(UIService, "servicebridge.v1.UI") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UIClient;
  service: typeof UIService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
