// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: servicebridge/v1/workflows.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "../../google/protobuf/empty";

export interface StartRunRequest {
  workflowName: string;
  /** JSON-encoded workflow input */
  input: Buffer;
  idempotencyKey: string;
  /** 0 = no global timeout override */
  timeoutSec: number;
  /** X-SB-Trace propagation from caller. */
  xSbTrace: string;
  /**
   * parent_run_id — when non-empty, the request originates from a workflow
   * step on an in-flight parent run. Runtime enforces dynamic cycle
   * detection (ADR-W-019) by walking the ancestor chain via this id.
   * Empty for top-level starts initiated by external callers.
   */
  parentRunId: string;
}

export interface StartRunResponse {
  runId: string;
}

export interface CancelRunRequest {
  runId: string;
}

export interface SignalRunRequest {
  runId: string;
  signalName: string;
  payload: Buffer;
}

export interface QueryRunRequest {
  runId: string;
}

export interface QueryRunResponse {
  runId: string;
  status: string;
  /** JSON-encoded run state map */
  state: Buffer;
  steps: StepInfo[];
}

export interface StepInfo {
  stepId: string;
  status: string;
  output: Buffer;
  lastError: string;
  /** step_id of the compensation step, if compensated */
  compensatedBy: string;
}

export interface AwaitRunRequest {
  runId: string;
}

export interface RunStatusUpdate {
  runId: string;
  status: string;
  /** JSON-encoded final state; non-empty only on terminal status */
  state: Buffer;
}

export interface ReplayRunRequest {
  runId: string;
  fromStepId: string;
}

export interface ReplayRunResponse {
  /** new run id */
  runId: string;
}

export interface SubscribeRequest {
  /** UUID */
  serviceId: string;
  /** UUID */
  instanceId: string;
}

export interface RunAssignment {
  runId: string;
  workflowName: string;
  fingerprint: string;
  /** canonical JSON graph */
  frozenPlan: Buffer;
  /** JSON-encoded workflow input */
  input: Buffer;
  /** JSON-encoded current state (checkpointed outputs) */
  state: Buffer;
  leaseEpoch: number;
  maxParallelism: number;
  /** X-SB-Trace propagation — workflow root op. */
  xSbTrace: string;
  /** Compensation: if set, SDK must execute compensation steps. */
  compensating: boolean;
  /** cancel_reason mirrors workflow_runs.cancel_reason. Values: '' | 'user_cancel' | 'step_failure'. */
  cancelReason: string;
}

export interface BeginStepRequest {
  runId: string;
  stepId: string;
  /** empty for top-level steps */
  parentStepId: string;
  /** call|publish|sleep|wait_event|wait_signal|workflow|parallel|sequence|local */
  kind: string;
  /** JSON-encoded resolved inputs */
  inputSnapshot: Buffer;
  leaseEpoch: number;
  /** UUID of the claiming SDK instance */
  instanceId: string;
}

export interface BeginStepResponse {
  /**
   * If the step was already completed (idempotent replay), cached_output is
   * non-nil and the SDK must use it without re-executing.
   */
  cachedOutput: Buffer;
  alreadyDone: boolean;
  leaseEpoch: number;
}

export interface CompleteStepRequest {
  runId: string;
  stepId: string;
  /** JSON-encoded step output */
  output: Buffer;
  leaseEpoch: number;
}

export interface FailStepRequest {
  runId: string;
  stepId: string;
  errorCode: string;
  errorMessage: string;
  leaseEpoch: number;
  retriable: boolean;
}

export interface FailStepResponse {
  /** Runtime's decision after the failure. */
  nextAction: string;
  retryDelaySec: number;
}

export interface ParkRequest {
  runId: string;
  stepId: string;
  leaseEpoch: number;
  sleep?: SleepSpec | undefined;
  eventWait?: EventWaitSpec | undefined;
  signalWait?: SignalWaitSpec | undefined;
  nestedRun?: NestedRunSpec | undefined;
}

export interface SleepSpec {
  durationSec: number;
}

export interface EventWaitSpec {
  event: string;
  /** JSON-encoded {"$.path": "expected"} filter; empty = match all */
  filterJson: string;
  /** 0 = no timeout */
  timeoutSec: number;
}

export interface SignalWaitSpec {
  signal: string;
  /** 0 = no timeout */
  timeoutSec: number;
}

export interface NestedRunSpec {
  childRunId: string;
}

export interface CompleteRunRequest {
  runId: string;
  /** JSON-encoded final state map (output of last step) */
  finalState: Buffer;
  leaseEpoch: number;
  /**
   * terminal_status: 'success' | 'failed_compensated' | 'cancelled'.
   * If empty, defaults to 'success'.
   */
  terminalStatus: string;
}

export interface HeartbeatRequest {
  runId: string;
  /** UUID */
  instanceId: string;
  leaseEpoch: number;
}

function createBaseStartRunRequest(): StartRunRequest {
  return { workflowName: "", input: Buffer.alloc(0), idempotencyKey: "", timeoutSec: 0, xSbTrace: "", parentRunId: "" };
}

export const StartRunRequest: MessageFns<StartRunRequest> = {
  encode(message: StartRunRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workflowName !== "") {
      writer.uint32(10).string(message.workflowName);
    }
    if (message.input.length !== 0) {
      writer.uint32(18).bytes(message.input);
    }
    if (message.idempotencyKey !== "") {
      writer.uint32(26).string(message.idempotencyKey);
    }
    if (message.timeoutSec !== 0) {
      writer.uint32(32).uint32(message.timeoutSec);
    }
    if (message.xSbTrace !== "") {
      writer.uint32(42).string(message.xSbTrace);
    }
    if (message.parentRunId !== "") {
      writer.uint32(66).string(message.parentRunId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartRunRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartRunRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.workflowName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.input = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timeoutSec = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.xSbTrace = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.parentRunId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StartRunRequest>, I>>(base?: I): StartRunRequest {
    return StartRunRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StartRunRequest>, I>>(object: I): StartRunRequest {
    const message = createBaseStartRunRequest();
    message.workflowName = object.workflowName ?? "";
    message.input = object.input ?? Buffer.alloc(0);
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.timeoutSec = object.timeoutSec ?? 0;
    message.xSbTrace = object.xSbTrace ?? "";
    message.parentRunId = object.parentRunId ?? "";
    return message;
  },
};

function createBaseStartRunResponse(): StartRunResponse {
  return { runId: "" };
}

export const StartRunResponse: MessageFns<StartRunResponse> = {
  encode(message: StartRunResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartRunResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartRunResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StartRunResponse>, I>>(base?: I): StartRunResponse {
    return StartRunResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StartRunResponse>, I>>(object: I): StartRunResponse {
    const message = createBaseStartRunResponse();
    message.runId = object.runId ?? "";
    return message;
  },
};

function createBaseCancelRunRequest(): CancelRunRequest {
  return { runId: "" };
}

export const CancelRunRequest: MessageFns<CancelRunRequest> = {
  encode(message: CancelRunRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelRunRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelRunRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CancelRunRequest>, I>>(base?: I): CancelRunRequest {
    return CancelRunRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelRunRequest>, I>>(object: I): CancelRunRequest {
    const message = createBaseCancelRunRequest();
    message.runId = object.runId ?? "";
    return message;
  },
};

function createBaseSignalRunRequest(): SignalRunRequest {
  return { runId: "", signalName: "", payload: Buffer.alloc(0) };
}

export const SignalRunRequest: MessageFns<SignalRunRequest> = {
  encode(message: SignalRunRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    if (message.signalName !== "") {
      writer.uint32(18).string(message.signalName);
    }
    if (message.payload.length !== 0) {
      writer.uint32(26).bytes(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalRunRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalRunRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.signalName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SignalRunRequest>, I>>(base?: I): SignalRunRequest {
    return SignalRunRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignalRunRequest>, I>>(object: I): SignalRunRequest {
    const message = createBaseSignalRunRequest();
    message.runId = object.runId ?? "";
    message.signalName = object.signalName ?? "";
    message.payload = object.payload ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseQueryRunRequest(): QueryRunRequest {
  return { runId: "" };
}

export const QueryRunRequest: MessageFns<QueryRunRequest> = {
  encode(message: QueryRunRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryRunRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryRunRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<QueryRunRequest>, I>>(base?: I): QueryRunRequest {
    return QueryRunRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryRunRequest>, I>>(object: I): QueryRunRequest {
    const message = createBaseQueryRunRequest();
    message.runId = object.runId ?? "";
    return message;
  },
};

function createBaseQueryRunResponse(): QueryRunResponse {
  return { runId: "", status: "", state: Buffer.alloc(0), steps: [] };
}

export const QueryRunResponse: MessageFns<QueryRunResponse> = {
  encode(message: QueryRunResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.state.length !== 0) {
      writer.uint32(26).bytes(message.state);
    }
    for (const v of message.steps) {
      StepInfo.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryRunResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryRunResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.state = Buffer.from(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.steps.push(StepInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<QueryRunResponse>, I>>(base?: I): QueryRunResponse {
    return QueryRunResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryRunResponse>, I>>(object: I): QueryRunResponse {
    const message = createBaseQueryRunResponse();
    message.runId = object.runId ?? "";
    message.status = object.status ?? "";
    message.state = object.state ?? Buffer.alloc(0);
    message.steps = object.steps?.map((e) => StepInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStepInfo(): StepInfo {
  return { stepId: "", status: "", output: Buffer.alloc(0), lastError: "", compensatedBy: "" };
}

export const StepInfo: MessageFns<StepInfo> = {
  encode(message: StepInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stepId !== "") {
      writer.uint32(10).string(message.stepId);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.output.length !== 0) {
      writer.uint32(26).bytes(message.output);
    }
    if (message.lastError !== "") {
      writer.uint32(34).string(message.lastError);
    }
    if (message.compensatedBy !== "") {
      writer.uint32(42).string(message.compensatedBy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StepInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStepInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stepId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.output = Buffer.from(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lastError = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.compensatedBy = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<StepInfo>, I>>(base?: I): StepInfo {
    return StepInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StepInfo>, I>>(object: I): StepInfo {
    const message = createBaseStepInfo();
    message.stepId = object.stepId ?? "";
    message.status = object.status ?? "";
    message.output = object.output ?? Buffer.alloc(0);
    message.lastError = object.lastError ?? "";
    message.compensatedBy = object.compensatedBy ?? "";
    return message;
  },
};

function createBaseAwaitRunRequest(): AwaitRunRequest {
  return { runId: "" };
}

export const AwaitRunRequest: MessageFns<AwaitRunRequest> = {
  encode(message: AwaitRunRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AwaitRunRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAwaitRunRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<AwaitRunRequest>, I>>(base?: I): AwaitRunRequest {
    return AwaitRunRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AwaitRunRequest>, I>>(object: I): AwaitRunRequest {
    const message = createBaseAwaitRunRequest();
    message.runId = object.runId ?? "";
    return message;
  },
};

function createBaseRunStatusUpdate(): RunStatusUpdate {
  return { runId: "", status: "", state: Buffer.alloc(0) };
}

export const RunStatusUpdate: MessageFns<RunStatusUpdate> = {
  encode(message: RunStatusUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.state.length !== 0) {
      writer.uint32(26).bytes(message.state);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunStatusUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunStatusUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.state = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RunStatusUpdate>, I>>(base?: I): RunStatusUpdate {
    return RunStatusUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RunStatusUpdate>, I>>(object: I): RunStatusUpdate {
    const message = createBaseRunStatusUpdate();
    message.runId = object.runId ?? "";
    message.status = object.status ?? "";
    message.state = object.state ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseReplayRunRequest(): ReplayRunRequest {
  return { runId: "", fromStepId: "" };
}

export const ReplayRunRequest: MessageFns<ReplayRunRequest> = {
  encode(message: ReplayRunRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    if (message.fromStepId !== "") {
      writer.uint32(18).string(message.fromStepId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReplayRunRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReplayRunRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fromStepId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ReplayRunRequest>, I>>(base?: I): ReplayRunRequest {
    return ReplayRunRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReplayRunRequest>, I>>(object: I): ReplayRunRequest {
    const message = createBaseReplayRunRequest();
    message.runId = object.runId ?? "";
    message.fromStepId = object.fromStepId ?? "";
    return message;
  },
};

function createBaseReplayRunResponse(): ReplayRunResponse {
  return { runId: "" };
}

export const ReplayRunResponse: MessageFns<ReplayRunResponse> = {
  encode(message: ReplayRunResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReplayRunResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReplayRunResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ReplayRunResponse>, I>>(base?: I): ReplayRunResponse {
    return ReplayRunResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReplayRunResponse>, I>>(object: I): ReplayRunResponse {
    const message = createBaseReplayRunResponse();
    message.runId = object.runId ?? "";
    return message;
  },
};

function createBaseSubscribeRequest(): SubscribeRequest {
  return { serviceId: "", instanceId: "" };
}

export const SubscribeRequest: MessageFns<SubscribeRequest> = {
  encode(message: SubscribeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serviceId !== "") {
      writer.uint32(10).string(message.serviceId);
    }
    if (message.instanceId !== "") {
      writer.uint32(18).string(message.instanceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serviceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SubscribeRequest>, I>>(base?: I): SubscribeRequest {
    return SubscribeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeRequest>, I>>(object: I): SubscribeRequest {
    const message = createBaseSubscribeRequest();
    message.serviceId = object.serviceId ?? "";
    message.instanceId = object.instanceId ?? "";
    return message;
  },
};

function createBaseRunAssignment(): RunAssignment {
  return {
    runId: "",
    workflowName: "",
    fingerprint: "",
    frozenPlan: Buffer.alloc(0),
    input: Buffer.alloc(0),
    state: Buffer.alloc(0),
    leaseEpoch: 0,
    maxParallelism: 0,
    xSbTrace: "",
    compensating: false,
    cancelReason: "",
  };
}

export const RunAssignment: MessageFns<RunAssignment> = {
  encode(message: RunAssignment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    if (message.workflowName !== "") {
      writer.uint32(18).string(message.workflowName);
    }
    if (message.fingerprint !== "") {
      writer.uint32(26).string(message.fingerprint);
    }
    if (message.frozenPlan.length !== 0) {
      writer.uint32(34).bytes(message.frozenPlan);
    }
    if (message.input.length !== 0) {
      writer.uint32(42).bytes(message.input);
    }
    if (message.state.length !== 0) {
      writer.uint32(50).bytes(message.state);
    }
    if (message.leaseEpoch !== 0) {
      writer.uint32(56).uint64(message.leaseEpoch);
    }
    if (message.maxParallelism !== 0) {
      writer.uint32(64).uint32(message.maxParallelism);
    }
    if (message.xSbTrace !== "") {
      writer.uint32(74).string(message.xSbTrace);
    }
    if (message.compensating !== false) {
      writer.uint32(96).bool(message.compensating);
    }
    if (message.cancelReason !== "") {
      writer.uint32(106).string(message.cancelReason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RunAssignment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRunAssignment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workflowName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.fingerprint = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.frozenPlan = Buffer.from(reader.bytes());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.input = Buffer.from(reader.bytes());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.state = Buffer.from(reader.bytes());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.leaseEpoch = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.maxParallelism = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.xSbTrace = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.compensating = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.cancelReason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<RunAssignment>, I>>(base?: I): RunAssignment {
    return RunAssignment.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RunAssignment>, I>>(object: I): RunAssignment {
    const message = createBaseRunAssignment();
    message.runId = object.runId ?? "";
    message.workflowName = object.workflowName ?? "";
    message.fingerprint = object.fingerprint ?? "";
    message.frozenPlan = object.frozenPlan ?? Buffer.alloc(0);
    message.input = object.input ?? Buffer.alloc(0);
    message.state = object.state ?? Buffer.alloc(0);
    message.leaseEpoch = object.leaseEpoch ?? 0;
    message.maxParallelism = object.maxParallelism ?? 0;
    message.xSbTrace = object.xSbTrace ?? "";
    message.compensating = object.compensating ?? false;
    message.cancelReason = object.cancelReason ?? "";
    return message;
  },
};

function createBaseBeginStepRequest(): BeginStepRequest {
  return {
    runId: "",
    stepId: "",
    parentStepId: "",
    kind: "",
    inputSnapshot: Buffer.alloc(0),
    leaseEpoch: 0,
    instanceId: "",
  };
}

export const BeginStepRequest: MessageFns<BeginStepRequest> = {
  encode(message: BeginStepRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    if (message.stepId !== "") {
      writer.uint32(18).string(message.stepId);
    }
    if (message.parentStepId !== "") {
      writer.uint32(26).string(message.parentStepId);
    }
    if (message.kind !== "") {
      writer.uint32(34).string(message.kind);
    }
    if (message.inputSnapshot.length !== 0) {
      writer.uint32(42).bytes(message.inputSnapshot);
    }
    if (message.leaseEpoch !== 0) {
      writer.uint32(48).uint64(message.leaseEpoch);
    }
    if (message.instanceId !== "") {
      writer.uint32(58).string(message.instanceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BeginStepRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBeginStepRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stepId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.parentStepId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.kind = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.inputSnapshot = Buffer.from(reader.bytes());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.leaseEpoch = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<BeginStepRequest>, I>>(base?: I): BeginStepRequest {
    return BeginStepRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BeginStepRequest>, I>>(object: I): BeginStepRequest {
    const message = createBaseBeginStepRequest();
    message.runId = object.runId ?? "";
    message.stepId = object.stepId ?? "";
    message.parentStepId = object.parentStepId ?? "";
    message.kind = object.kind ?? "";
    message.inputSnapshot = object.inputSnapshot ?? Buffer.alloc(0);
    message.leaseEpoch = object.leaseEpoch ?? 0;
    message.instanceId = object.instanceId ?? "";
    return message;
  },
};

function createBaseBeginStepResponse(): BeginStepResponse {
  return { cachedOutput: Buffer.alloc(0), alreadyDone: false, leaseEpoch: 0 };
}

export const BeginStepResponse: MessageFns<BeginStepResponse> = {
  encode(message: BeginStepResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cachedOutput.length !== 0) {
      writer.uint32(10).bytes(message.cachedOutput);
    }
    if (message.alreadyDone !== false) {
      writer.uint32(16).bool(message.alreadyDone);
    }
    if (message.leaseEpoch !== 0) {
      writer.uint32(24).uint64(message.leaseEpoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BeginStepResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBeginStepResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cachedOutput = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.alreadyDone = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.leaseEpoch = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<BeginStepResponse>, I>>(base?: I): BeginStepResponse {
    return BeginStepResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BeginStepResponse>, I>>(object: I): BeginStepResponse {
    const message = createBaseBeginStepResponse();
    message.cachedOutput = object.cachedOutput ?? Buffer.alloc(0);
    message.alreadyDone = object.alreadyDone ?? false;
    message.leaseEpoch = object.leaseEpoch ?? 0;
    return message;
  },
};

function createBaseCompleteStepRequest(): CompleteStepRequest {
  return { runId: "", stepId: "", output: Buffer.alloc(0), leaseEpoch: 0 };
}

export const CompleteStepRequest: MessageFns<CompleteStepRequest> = {
  encode(message: CompleteStepRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    if (message.stepId !== "") {
      writer.uint32(18).string(message.stepId);
    }
    if (message.output.length !== 0) {
      writer.uint32(26).bytes(message.output);
    }
    if (message.leaseEpoch !== 0) {
      writer.uint32(32).uint64(message.leaseEpoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteStepRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteStepRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stepId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.output = Buffer.from(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.leaseEpoch = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CompleteStepRequest>, I>>(base?: I): CompleteStepRequest {
    return CompleteStepRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CompleteStepRequest>, I>>(object: I): CompleteStepRequest {
    const message = createBaseCompleteStepRequest();
    message.runId = object.runId ?? "";
    message.stepId = object.stepId ?? "";
    message.output = object.output ?? Buffer.alloc(0);
    message.leaseEpoch = object.leaseEpoch ?? 0;
    return message;
  },
};

function createBaseFailStepRequest(): FailStepRequest {
  return { runId: "", stepId: "", errorCode: "", errorMessage: "", leaseEpoch: 0, retriable: false };
}

export const FailStepRequest: MessageFns<FailStepRequest> = {
  encode(message: FailStepRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    if (message.stepId !== "") {
      writer.uint32(18).string(message.stepId);
    }
    if (message.errorCode !== "") {
      writer.uint32(26).string(message.errorCode);
    }
    if (message.errorMessage !== "") {
      writer.uint32(34).string(message.errorMessage);
    }
    if (message.leaseEpoch !== 0) {
      writer.uint32(40).uint64(message.leaseEpoch);
    }
    if (message.retriable !== false) {
      writer.uint32(48).bool(message.retriable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FailStepRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFailStepRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stepId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorCode = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.leaseEpoch = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.retriable = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<FailStepRequest>, I>>(base?: I): FailStepRequest {
    return FailStepRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FailStepRequest>, I>>(object: I): FailStepRequest {
    const message = createBaseFailStepRequest();
    message.runId = object.runId ?? "";
    message.stepId = object.stepId ?? "";
    message.errorCode = object.errorCode ?? "";
    message.errorMessage = object.errorMessage ?? "";
    message.leaseEpoch = object.leaseEpoch ?? 0;
    message.retriable = object.retriable ?? false;
    return message;
  },
};

function createBaseFailStepResponse(): FailStepResponse {
  return { nextAction: "", retryDelaySec: 0 };
}

export const FailStepResponse: MessageFns<FailStepResponse> = {
  encode(message: FailStepResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nextAction !== "") {
      writer.uint32(10).string(message.nextAction);
    }
    if (message.retryDelaySec !== 0) {
      writer.uint32(16).uint32(message.retryDelaySec);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FailStepResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFailStepResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nextAction = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.retryDelaySec = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<FailStepResponse>, I>>(base?: I): FailStepResponse {
    return FailStepResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FailStepResponse>, I>>(object: I): FailStepResponse {
    const message = createBaseFailStepResponse();
    message.nextAction = object.nextAction ?? "";
    message.retryDelaySec = object.retryDelaySec ?? 0;
    return message;
  },
};

function createBaseParkRequest(): ParkRequest {
  return {
    runId: "",
    stepId: "",
    leaseEpoch: 0,
    sleep: undefined,
    eventWait: undefined,
    signalWait: undefined,
    nestedRun: undefined,
  };
}

export const ParkRequest: MessageFns<ParkRequest> = {
  encode(message: ParkRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    if (message.stepId !== "") {
      writer.uint32(18).string(message.stepId);
    }
    if (message.leaseEpoch !== 0) {
      writer.uint32(24).uint64(message.leaseEpoch);
    }
    if (message.sleep !== undefined) {
      SleepSpec.encode(message.sleep, writer.uint32(34).fork()).join();
    }
    if (message.eventWait !== undefined) {
      EventWaitSpec.encode(message.eventWait, writer.uint32(42).fork()).join();
    }
    if (message.signalWait !== undefined) {
      SignalWaitSpec.encode(message.signalWait, writer.uint32(50).fork()).join();
    }
    if (message.nestedRun !== undefined) {
      NestedRunSpec.encode(message.nestedRun, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ParkRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParkRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stepId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.leaseEpoch = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sleep = SleepSpec.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.eventWait = EventWaitSpec.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.signalWait = SignalWaitSpec.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.nestedRun = NestedRunSpec.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<ParkRequest>, I>>(base?: I): ParkRequest {
    return ParkRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ParkRequest>, I>>(object: I): ParkRequest {
    const message = createBaseParkRequest();
    message.runId = object.runId ?? "";
    message.stepId = object.stepId ?? "";
    message.leaseEpoch = object.leaseEpoch ?? 0;
    message.sleep = (object.sleep !== undefined && object.sleep !== null)
      ? SleepSpec.fromPartial(object.sleep)
      : undefined;
    message.eventWait = (object.eventWait !== undefined && object.eventWait !== null)
      ? EventWaitSpec.fromPartial(object.eventWait)
      : undefined;
    message.signalWait = (object.signalWait !== undefined && object.signalWait !== null)
      ? SignalWaitSpec.fromPartial(object.signalWait)
      : undefined;
    message.nestedRun = (object.nestedRun !== undefined && object.nestedRun !== null)
      ? NestedRunSpec.fromPartial(object.nestedRun)
      : undefined;
    return message;
  },
};

function createBaseSleepSpec(): SleepSpec {
  return { durationSec: 0 };
}

export const SleepSpec: MessageFns<SleepSpec> = {
  encode(message: SleepSpec, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.durationSec !== 0) {
      writer.uint32(8).uint32(message.durationSec);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SleepSpec {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSleepSpec();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.durationSec = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SleepSpec>, I>>(base?: I): SleepSpec {
    return SleepSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SleepSpec>, I>>(object: I): SleepSpec {
    const message = createBaseSleepSpec();
    message.durationSec = object.durationSec ?? 0;
    return message;
  },
};

function createBaseEventWaitSpec(): EventWaitSpec {
  return { event: "", filterJson: "", timeoutSec: 0 };
}

export const EventWaitSpec: MessageFns<EventWaitSpec> = {
  encode(message: EventWaitSpec, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event !== "") {
      writer.uint32(10).string(message.event);
    }
    if (message.filterJson !== "") {
      writer.uint32(18).string(message.filterJson);
    }
    if (message.timeoutSec !== 0) {
      writer.uint32(24).uint32(message.timeoutSec);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventWaitSpec {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventWaitSpec();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filterJson = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timeoutSec = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<EventWaitSpec>, I>>(base?: I): EventWaitSpec {
    return EventWaitSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventWaitSpec>, I>>(object: I): EventWaitSpec {
    const message = createBaseEventWaitSpec();
    message.event = object.event ?? "";
    message.filterJson = object.filterJson ?? "";
    message.timeoutSec = object.timeoutSec ?? 0;
    return message;
  },
};

function createBaseSignalWaitSpec(): SignalWaitSpec {
  return { signal: "", timeoutSec: 0 };
}

export const SignalWaitSpec: MessageFns<SignalWaitSpec> = {
  encode(message: SignalWaitSpec, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signal !== "") {
      writer.uint32(10).string(message.signal);
    }
    if (message.timeoutSec !== 0) {
      writer.uint32(16).uint32(message.timeoutSec);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignalWaitSpec {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignalWaitSpec();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signal = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timeoutSec = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<SignalWaitSpec>, I>>(base?: I): SignalWaitSpec {
    return SignalWaitSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignalWaitSpec>, I>>(object: I): SignalWaitSpec {
    const message = createBaseSignalWaitSpec();
    message.signal = object.signal ?? "";
    message.timeoutSec = object.timeoutSec ?? 0;
    return message;
  },
};

function createBaseNestedRunSpec(): NestedRunSpec {
  return { childRunId: "" };
}

export const NestedRunSpec: MessageFns<NestedRunSpec> = {
  encode(message: NestedRunSpec, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.childRunId !== "") {
      writer.uint32(10).string(message.childRunId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NestedRunSpec {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNestedRunSpec();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.childRunId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<NestedRunSpec>, I>>(base?: I): NestedRunSpec {
    return NestedRunSpec.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NestedRunSpec>, I>>(object: I): NestedRunSpec {
    const message = createBaseNestedRunSpec();
    message.childRunId = object.childRunId ?? "";
    return message;
  },
};

function createBaseCompleteRunRequest(): CompleteRunRequest {
  return { runId: "", finalState: Buffer.alloc(0), leaseEpoch: 0, terminalStatus: "" };
}

export const CompleteRunRequest: MessageFns<CompleteRunRequest> = {
  encode(message: CompleteRunRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    if (message.finalState.length !== 0) {
      writer.uint32(18).bytes(message.finalState);
    }
    if (message.leaseEpoch !== 0) {
      writer.uint32(24).uint64(message.leaseEpoch);
    }
    if (message.terminalStatus !== "") {
      writer.uint32(34).string(message.terminalStatus);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteRunRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteRunRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.finalState = Buffer.from(reader.bytes());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.leaseEpoch = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.terminalStatus = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<CompleteRunRequest>, I>>(base?: I): CompleteRunRequest {
    return CompleteRunRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CompleteRunRequest>, I>>(object: I): CompleteRunRequest {
    const message = createBaseCompleteRunRequest();
    message.runId = object.runId ?? "";
    message.finalState = object.finalState ?? Buffer.alloc(0);
    message.leaseEpoch = object.leaseEpoch ?? 0;
    message.terminalStatus = object.terminalStatus ?? "";
    return message;
  },
};

function createBaseHeartbeatRequest(): HeartbeatRequest {
  return { runId: "", instanceId: "", leaseEpoch: 0 };
}

export const HeartbeatRequest: MessageFns<HeartbeatRequest> = {
  encode(message: HeartbeatRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runId !== "") {
      writer.uint32(10).string(message.runId);
    }
    if (message.instanceId !== "") {
      writer.uint32(18).string(message.instanceId);
    }
    if (message.leaseEpoch !== 0) {
      writer.uint32(24).uint64(message.leaseEpoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeartbeatRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeartbeatRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.instanceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.leaseEpoch = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create<I extends Exact<DeepPartial<HeartbeatRequest>, I>>(base?: I): HeartbeatRequest {
    return HeartbeatRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeartbeatRequest>, I>>(object: I): HeartbeatRequest {
    const message = createBaseHeartbeatRequest();
    message.runId = object.runId ?? "";
    message.instanceId = object.instanceId ?? "";
    message.leaseEpoch = object.leaseEpoch ?? 0;
    return message;
  },
};

/**
 * Workflows — durable workflow execution service.
 * Caller-side RPCs: Start, Cancel, Signal, Query, Await, Replay.
 * Owner-side RPCs: Subscribe, BeginStep, CompleteStep, FailStep, Park, Heartbeat.
 */
export type WorkflowsService = typeof WorkflowsService;
export const WorkflowsService = {
  /** Caller-side */
  start: {
    path: "/servicebridge.v1.Workflows/Start" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: StartRunRequest): Buffer => Buffer.from(StartRunRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): StartRunRequest => StartRunRequest.decode(value),
    responseSerialize: (value: StartRunResponse): Buffer => Buffer.from(StartRunResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): StartRunResponse => StartRunResponse.decode(value),
  },
  cancel: {
    path: "/servicebridge.v1.Workflows/Cancel" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CancelRunRequest): Buffer => Buffer.from(CancelRunRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CancelRunRequest => CancelRunRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  signal: {
    path: "/servicebridge.v1.Workflows/Signal" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: SignalRunRequest): Buffer => Buffer.from(SignalRunRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SignalRunRequest => SignalRunRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  query: {
    path: "/servicebridge.v1.Workflows/Query" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: QueryRunRequest): Buffer => Buffer.from(QueryRunRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): QueryRunRequest => QueryRunRequest.decode(value),
    responseSerialize: (value: QueryRunResponse): Buffer => Buffer.from(QueryRunResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): QueryRunResponse => QueryRunResponse.decode(value),
  },
  await: {
    path: "/servicebridge.v1.Workflows/Await" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: AwaitRunRequest): Buffer => Buffer.from(AwaitRunRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AwaitRunRequest => AwaitRunRequest.decode(value),
    responseSerialize: (value: RunStatusUpdate): Buffer => Buffer.from(RunStatusUpdate.encode(value).finish()),
    responseDeserialize: (value: Buffer): RunStatusUpdate => RunStatusUpdate.decode(value),
  },
  replay: {
    path: "/servicebridge.v1.Workflows/Replay" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ReplayRunRequest): Buffer => Buffer.from(ReplayRunRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ReplayRunRequest => ReplayRunRequest.decode(value),
    responseSerialize: (value: ReplayRunResponse): Buffer => Buffer.from(ReplayRunResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ReplayRunResponse => ReplayRunResponse.decode(value),
  },
  /** Owner-side */
  subscribe: {
    path: "/servicebridge.v1.Workflows/Subscribe" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: SubscribeRequest): Buffer => Buffer.from(SubscribeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SubscribeRequest => SubscribeRequest.decode(value),
    responseSerialize: (value: RunAssignment): Buffer => Buffer.from(RunAssignment.encode(value).finish()),
    responseDeserialize: (value: Buffer): RunAssignment => RunAssignment.decode(value),
  },
  beginStep: {
    path: "/servicebridge.v1.Workflows/BeginStep" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: BeginStepRequest): Buffer => Buffer.from(BeginStepRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): BeginStepRequest => BeginStepRequest.decode(value),
    responseSerialize: (value: BeginStepResponse): Buffer => Buffer.from(BeginStepResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): BeginStepResponse => BeginStepResponse.decode(value),
  },
  completeStep: {
    path: "/servicebridge.v1.Workflows/CompleteStep" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CompleteStepRequest): Buffer => Buffer.from(CompleteStepRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CompleteStepRequest => CompleteStepRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  completeRun: {
    path: "/servicebridge.v1.Workflows/CompleteRun" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CompleteRunRequest): Buffer => Buffer.from(CompleteRunRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CompleteRunRequest => CompleteRunRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  failStep: {
    path: "/servicebridge.v1.Workflows/FailStep" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: FailStepRequest): Buffer => Buffer.from(FailStepRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): FailStepRequest => FailStepRequest.decode(value),
    responseSerialize: (value: FailStepResponse): Buffer => Buffer.from(FailStepResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): FailStepResponse => FailStepResponse.decode(value),
  },
  park: {
    path: "/servicebridge.v1.Workflows/Park" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ParkRequest): Buffer => Buffer.from(ParkRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ParkRequest => ParkRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  heartbeat: {
    path: "/servicebridge.v1.Workflows/Heartbeat" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HeartbeatRequest): Buffer => Buffer.from(HeartbeatRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HeartbeatRequest => HeartbeatRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
} as const;

export interface WorkflowsServer extends UntypedServiceImplementation {
  /** Caller-side */
  start: handleUnaryCall<StartRunRequest, StartRunResponse>;
  cancel: handleUnaryCall<CancelRunRequest, Empty>;
  signal: handleUnaryCall<SignalRunRequest, Empty>;
  query: handleUnaryCall<QueryRunRequest, QueryRunResponse>;
  await: handleServerStreamingCall<AwaitRunRequest, RunStatusUpdate>;
  replay: handleUnaryCall<ReplayRunRequest, ReplayRunResponse>;
  /** Owner-side */
  subscribe: handleServerStreamingCall<SubscribeRequest, RunAssignment>;
  beginStep: handleUnaryCall<BeginStepRequest, BeginStepResponse>;
  completeStep: handleUnaryCall<CompleteStepRequest, Empty>;
  completeRun: handleUnaryCall<CompleteRunRequest, Empty>;
  failStep: handleUnaryCall<FailStepRequest, FailStepResponse>;
  park: handleUnaryCall<ParkRequest, Empty>;
  heartbeat: handleUnaryCall<HeartbeatRequest, Empty>;
}

export interface WorkflowsClient extends Client {
  /** Caller-side */
  start(
    request: StartRunRequest,
    callback: (error: ServiceError | null, response: StartRunResponse) => void,
  ): ClientUnaryCall;
  start(
    request: StartRunRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: StartRunResponse) => void,
  ): ClientUnaryCall;
  start(
    request: StartRunRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: StartRunResponse) => void,
  ): ClientUnaryCall;
  cancel(request: CancelRunRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  cancel(
    request: CancelRunRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  cancel(
    request: CancelRunRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  signal(request: SignalRunRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  signal(
    request: SignalRunRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  signal(
    request: SignalRunRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  query(
    request: QueryRunRequest,
    callback: (error: ServiceError | null, response: QueryRunResponse) => void,
  ): ClientUnaryCall;
  query(
    request: QueryRunRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: QueryRunResponse) => void,
  ): ClientUnaryCall;
  query(
    request: QueryRunRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: QueryRunResponse) => void,
  ): ClientUnaryCall;
  await(request: AwaitRunRequest, options?: Partial<CallOptions>): ClientReadableStream<RunStatusUpdate>;
  await(
    request: AwaitRunRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<RunStatusUpdate>;
  replay(
    request: ReplayRunRequest,
    callback: (error: ServiceError | null, response: ReplayRunResponse) => void,
  ): ClientUnaryCall;
  replay(
    request: ReplayRunRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ReplayRunResponse) => void,
  ): ClientUnaryCall;
  replay(
    request: ReplayRunRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ReplayRunResponse) => void,
  ): ClientUnaryCall;
  /** Owner-side */
  subscribe(request: SubscribeRequest, options?: Partial<CallOptions>): ClientReadableStream<RunAssignment>;
  subscribe(
    request: SubscribeRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<RunAssignment>;
  beginStep(
    request: BeginStepRequest,
    callback: (error: ServiceError | null, response: BeginStepResponse) => void,
  ): ClientUnaryCall;
  beginStep(
    request: BeginStepRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BeginStepResponse) => void,
  ): ClientUnaryCall;
  beginStep(
    request: BeginStepRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BeginStepResponse) => void,
  ): ClientUnaryCall;
  completeStep(
    request: CompleteStepRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  completeStep(
    request: CompleteStepRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  completeStep(
    request: CompleteStepRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  completeRun(
    request: CompleteRunRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  completeRun(
    request: CompleteRunRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  completeRun(
    request: CompleteRunRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  failStep(
    request: FailStepRequest,
    callback: (error: ServiceError | null, response: FailStepResponse) => void,
  ): ClientUnaryCall;
  failStep(
    request: FailStepRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: FailStepResponse) => void,
  ): ClientUnaryCall;
  failStep(
    request: FailStepRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: FailStepResponse) => void,
  ): ClientUnaryCall;
  park(request: ParkRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  park(
    request: ParkRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  park(
    request: ParkRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  heartbeat(
    request: HeartbeatRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  heartbeat(
    request: HeartbeatRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  heartbeat(
    request: HeartbeatRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const WorkflowsClient = makeGenericClientConstructor(
  WorkflowsService,
  "servicebridge.v1.Workflows",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): WorkflowsClient;
  service: typeof WorkflowsService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
