// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: servicebridge/v1/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_servicebridge_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_control_proto_rawDescGZIP(), []int{0}
}

type RefreshCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrDer        []byte                 `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshCertRequest) Reset() {
	*x = RefreshCertRequest{}
	mi := &file_servicebridge_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCertRequest) ProtoMessage() {}

func (x *RefreshCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCertRequest.ProtoReflect.Descriptor instead.
func (*RefreshCertRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshCertRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type RefreshCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertDer       []byte                 `protobuf:"bytes,1,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
	CaChainDer    []byte                 `protobuf:"bytes,2,opt,name=ca_chain_der,json=caChainDer,proto3" json:"ca_chain_der,omitempty"`
	NotAfterUnix  int64                  `protobuf:"varint,3,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`
	InstanceId    string                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshCertResponse) Reset() {
	*x = RefreshCertResponse{}
	mi := &file_servicebridge_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCertResponse) ProtoMessage() {}

func (x *RefreshCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCertResponse.ProtoReflect.Descriptor instead.
func (*RefreshCertResponse) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshCertResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *RefreshCertResponse) GetCaChainDer() []byte {
	if x != nil {
		return x.CaChainDer
	}
	return nil
}

func (x *RefreshCertResponse) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

func (x *RefreshCertResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ServerControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ServerControl_Welcome
	//	*ServerControl_Drain
	Kind          isServerControl_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerControl) Reset() {
	*x = ServerControl{}
	mi := &file_servicebridge_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerControl) ProtoMessage() {}

func (x *ServerControl) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerControl.ProtoReflect.Descriptor instead.
func (*ServerControl) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *ServerControl) GetKind() isServerControl_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ServerControl) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Kind.(*ServerControl_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerControl) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Kind.(*ServerControl_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

type isServerControl_Kind interface {
	isServerControl_Kind()
}

type ServerControl_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerControl_Drain struct {
	Drain *Drain `protobuf:"bytes,2,opt,name=drain,proto3,oneof"`
}

func (*ServerControl_Welcome) isServerControl_Kind() {}

func (*ServerControl_Drain) isServerControl_Kind() {}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_servicebridge_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *Welcome) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Welcome) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Welcome) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_servicebridge_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *Drain) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_servicebridge_v1_control_proto protoreflect.FileDescriptor

const file_servicebridge_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1eservicebridge/v1/control.proto\x12\x10servicebridge.v1\"\r\n" +
	"\vOpenRequest\"-\n" +
	"\x12RefreshCertRequest\x12\x17\n" +
	"\acsr_der\x18\x01 \x01(\fR\x06csrDer\"\x99\x01\n" +
	"\x13RefreshCertResponse\x12\x19\n" +
	"\bcert_der\x18\x01 \x01(\fR\acertDer\x12 \n" +
	"\fca_chain_der\x18\x02 \x01(\fR\n" +
	"caChainDer\x12$\n" +
	"\x0enot_after_unix\x18\x03 \x01(\x03R\fnotAfterUnix\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\tR\n" +
	"instanceId\"\x7f\n" +
	"\rServerControl\x125\n" +
	"\awelcome\x18\x01 \x01(\v2\x19.servicebridge.v1.WelcomeH\x00R\awelcome\x12/\n" +
	"\x05drain\x18\x02 \x01(\v2\x17.servicebridge.v1.DrainH\x00R\x05drainB\x06\n" +
	"\x04kind\"j\n" +
	"\aWelcome\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\"\x1f\n" +
	"\x05Drain\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2\xaf\x01\n" +
	"\aControl\x12H\n" +
	"\x04Open\x12\x1d.servicebridge.v1.OpenRequest\x1a\x1f.servicebridge.v1.ServerControl0\x01\x12Z\n" +
	"\vRefreshCert\x12$.servicebridge.v1.RefreshCertRequest\x1a%.servicebridge.v1.RefreshCertResponseBCZAgithub.com/service-bridge/runtime/internal/pb/servicebridge/v1;pbb\x06proto3"

var (
	file_servicebridge_v1_control_proto_rawDescOnce sync.Once
	file_servicebridge_v1_control_proto_rawDescData []byte
)

func file_servicebridge_v1_control_proto_rawDescGZIP() []byte {
	file_servicebridge_v1_control_proto_rawDescOnce.Do(func() {
		file_servicebridge_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servicebridge_v1_control_proto_rawDesc), len(file_servicebridge_v1_control_proto_rawDesc)))
	})
	return file_servicebridge_v1_control_proto_rawDescData
}

var file_servicebridge_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_servicebridge_v1_control_proto_goTypes = []any{
	(*OpenRequest)(nil),         // 0: servicebridge.v1.OpenRequest
	(*RefreshCertRequest)(nil),  // 1: servicebridge.v1.RefreshCertRequest
	(*RefreshCertResponse)(nil), // 2: servicebridge.v1.RefreshCertResponse
	(*ServerControl)(nil),       // 3: servicebridge.v1.ServerControl
	(*Welcome)(nil),             // 4: servicebridge.v1.Welcome
	(*Drain)(nil),               // 5: servicebridge.v1.Drain
}
var file_servicebridge_v1_control_proto_depIdxs = []int32{
	4, // 0: servicebridge.v1.ServerControl.welcome:type_name -> servicebridge.v1.Welcome
	5, // 1: servicebridge.v1.ServerControl.drain:type_name -> servicebridge.v1.Drain
	0, // 2: servicebridge.v1.Control.Open:input_type -> servicebridge.v1.OpenRequest
	1, // 3: servicebridge.v1.Control.RefreshCert:input_type -> servicebridge.v1.RefreshCertRequest
	3, // 4: servicebridge.v1.Control.Open:output_type -> servicebridge.v1.ServerControl
	2, // 5: servicebridge.v1.Control.RefreshCert:output_type -> servicebridge.v1.RefreshCertResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_servicebridge_v1_control_proto_init() }
func file_servicebridge_v1_control_proto_init() {
	if File_servicebridge_v1_control_proto != nil {
		return
	}
	file_servicebridge_v1_control_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerControl_Welcome)(nil),
		(*ServerControl_Drain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servicebridge_v1_control_proto_rawDesc), len(file_servicebridge_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicebridge_v1_control_proto_goTypes,
		DependencyIndexes: file_servicebridge_v1_control_proto_depIdxs,
		MessageInfos:      file_servicebridge_v1_control_proto_msgTypes,
	}.Build()
	File_servicebridge_v1_control_proto = out.File
	file_servicebridge_v1_control_proto_goTypes = nil
	file_servicebridge_v1_control_proto_depIdxs = nil
}
