// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: servicebridge/v1/events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishStatus int32

const (
	PublishStatus_PUBLISH_STATUS_UNSPECIFIED           PublishStatus = 0
	PublishStatus_PUBLISH_STATUS_ACCEPTED              PublishStatus = 1
	PublishStatus_PUBLISH_STATUS_REJECTED_DUPLICATE    PublishStatus = 3
	PublishStatus_PUBLISH_STATUS_REJECTED_INVALID_NAME PublishStatus = 5
	// ADR-0004: publisher does not have event.publish action rule matching this
	// event name (or its capability is disabled). Per-envelope reject — other
	// events in the batch proceed.
	PublishStatus_PUBLISH_STATUS_REJECTED_FORBIDDEN PublishStatus = 6
)

// Enum value maps for PublishStatus.
var (
	PublishStatus_name = map[int32]string{
		0: "PUBLISH_STATUS_UNSPECIFIED",
		1: "PUBLISH_STATUS_ACCEPTED",
		3: "PUBLISH_STATUS_REJECTED_DUPLICATE",
		5: "PUBLISH_STATUS_REJECTED_INVALID_NAME",
		6: "PUBLISH_STATUS_REJECTED_FORBIDDEN",
	}
	PublishStatus_value = map[string]int32{
		"PUBLISH_STATUS_UNSPECIFIED":           0,
		"PUBLISH_STATUS_ACCEPTED":              1,
		"PUBLISH_STATUS_REJECTED_DUPLICATE":    3,
		"PUBLISH_STATUS_REJECTED_INVALID_NAME": 5,
		"PUBLISH_STATUS_REJECTED_FORBIDDEN":    6,
	}
)

func (x PublishStatus) Enum() *PublishStatus {
	p := new(PublishStatus)
	*p = x
	return p
}

func (x PublishStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_servicebridge_v1_events_proto_enumTypes[0].Descriptor()
}

func (PublishStatus) Type() protoreflect.EnumType {
	return &file_servicebridge_v1_events_proto_enumTypes[0]
}

func (x PublishStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishStatus.Descriptor instead.
func (PublishStatus) EnumDescriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{0}
}

type EventEnvelope struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Payload          []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ContractHash     string                 `protobuf:"bytes,4,opt,name=contract_hash,json=contractHash,proto3" json:"contract_hash,omitempty"`
	PartitionKey     string                 `protobuf:"bytes,5,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	FireAndForget    bool                   `protobuf:"varint,7,opt,name=fire_and_forget,json=fireAndForget,proto3" json:"fire_and_forget,omitempty"`
	Headers          map[string]string      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OccurredAtUnixMs int64                  `protobuf:"varint,9,opt,name=occurred_at_unix_ms,json=occurredAtUnixMs,proto3" json:"occurred_at_unix_ms,omitempty"`
	// X-SB-Trace propagation: carried in EventEnvelope for publisher→consumer.
	XSbTrace string `protobuf:"bytes,10,opt,name=x_sb_trace,json=xSbTrace,proto3" json:"x_sb_trace,omitempty"` // "traceID-parentOpID" canonical format (ADR 0006 §3)
	// payload_json — JSON-encoded view of the same payload, populated by the
	// publisher SDK alongside the canonical protobuf `payload`. Used by the
	// workflow signal router to evaluate JSON-path `wait_event` filters
	// without decoding the protobuf form (runtime treats payload as opaque
	// bytes per ADR-0002). Empty when publisher cannot produce JSON.
	PayloadJson   []byte `protobuf:"bytes,11,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventEnvelope) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetContractHash() string {
	if x != nil {
		return x.ContractHash
	}
	return ""
}

func (x *EventEnvelope) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *EventEnvelope) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *EventEnvelope) GetFireAndForget() bool {
	if x != nil {
		return x.FireAndForget
	}
	return false
}

func (x *EventEnvelope) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *EventEnvelope) GetOccurredAtUnixMs() int64 {
	if x != nil {
		return x.OccurredAtUnixMs
	}
	return 0
}

func (x *EventEnvelope) GetXSbTrace() string {
	if x != nil {
		return x.XSbTrace
	}
	return ""
}

func (x *EventEnvelope) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type PublishRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublisherServiceId  string                 `protobuf:"bytes,1,opt,name=publisher_service_id,json=publisherServiceId,proto3" json:"publisher_service_id,omitempty"`
	PublisherInstanceId string                 `protobuf:"bytes,2,opt,name=publisher_instance_id,json=publisherInstanceId,proto3" json:"publisher_instance_id,omitempty"`
	Events              []*EventEnvelope       `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetPublisherServiceId() string {
	if x != nil {
		return x.PublisherServiceId
	}
	return ""
}

func (x *PublishRequest) GetPublisherInstanceId() string {
	if x != nil {
		return x.PublisherInstanceId
	}
	return ""
}

func (x *PublishRequest) GetEvents() []*EventEnvelope {
	if x != nil {
		return x.Events
	}
	return nil
}

type PublishStatusEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        PublishStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=servicebridge.v1.PublishStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishStatusEntry) Reset() {
	*x = PublishStatusEntry{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishStatusEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishStatusEntry) ProtoMessage() {}

func (x *PublishStatusEntry) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishStatusEntry.ProtoReflect.Descriptor instead.
func (*PublishStatusEntry) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *PublishStatusEntry) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PublishStatusEntry) GetStatus() PublishStatus {
	if x != nil {
		return x.Status
	}
	return PublishStatus_PUBLISH_STATUS_UNSPECIFIED
}

func (x *PublishStatusEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PublishStatusEntry  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *PublishResponse) GetResults() []*PublishStatusEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

type SubscribeInit struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SubscriberServiceId  string                 `protobuf:"bytes,1,opt,name=subscriber_service_id,json=subscriberServiceId,proto3" json:"subscriber_service_id,omitempty"`
	SubscriberInstanceId string                 `protobuf:"bytes,2,opt,name=subscriber_instance_id,json=subscriberInstanceId,proto3" json:"subscriber_instance_id,omitempty"`
	MaxInFlight          int32                  `protobuf:"varint,3,opt,name=max_in_flight,json=maxInFlight,proto3" json:"max_in_flight,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubscribeInit) Reset() {
	*x = SubscribeInit{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeInit) ProtoMessage() {}

func (x *SubscribeInit) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeInit.ProtoReflect.Descriptor instead.
func (*SubscribeInit) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeInit) GetSubscriberServiceId() string {
	if x != nil {
		return x.SubscriberServiceId
	}
	return ""
}

func (x *SubscribeInit) GetSubscriberInstanceId() string {
	if x != nil {
		return x.SubscriberInstanceId
	}
	return ""
}

func (x *SubscribeInit) GetMaxInFlight() int32 {
	if x != nil {
		return x.MaxInFlight
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	EventId       []byte                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *Ack) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

type Nack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	EventId       []byte                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nack) Reset() {
	*x = Nack{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nack) ProtoMessage() {}

func (x *Nack) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nack.ProtoReflect.Descriptor instead.
func (*Nack) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *Nack) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *Nack) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Nack) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

type SubscribeClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*SubscribeClientMessage_Init
	//	*SubscribeClientMessage_Ack
	//	*SubscribeClientMessage_Nack
	Kind          isSubscribeClientMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeClientMessage) Reset() {
	*x = SubscribeClientMessage{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeClientMessage) ProtoMessage() {}

func (x *SubscribeClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeClientMessage.ProtoReflect.Descriptor instead.
func (*SubscribeClientMessage) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeClientMessage) GetKind() isSubscribeClientMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *SubscribeClientMessage) GetInit() *SubscribeInit {
	if x != nil {
		if x, ok := x.Kind.(*SubscribeClientMessage_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *SubscribeClientMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Kind.(*SubscribeClientMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *SubscribeClientMessage) GetNack() *Nack {
	if x != nil {
		if x, ok := x.Kind.(*SubscribeClientMessage_Nack); ok {
			return x.Nack
		}
	}
	return nil
}

type isSubscribeClientMessage_Kind interface {
	isSubscribeClientMessage_Kind()
}

type SubscribeClientMessage_Init struct {
	Init *SubscribeInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type SubscribeClientMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type SubscribeClientMessage_Nack struct {
	Nack *Nack `protobuf:"bytes,3,opt,name=nack,proto3,oneof"`
}

func (*SubscribeClientMessage_Init) isSubscribeClientMessage_Kind() {}

func (*SubscribeClientMessage_Ack) isSubscribeClientMessage_Kind() {}

func (*SubscribeClientMessage_Nack) isSubscribeClientMessage_Kind() {}

type EventDelivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Envelope      *EventEnvelope         `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Attempt       int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDelivery) Reset() {
	*x = EventDelivery{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDelivery) ProtoMessage() {}

func (x *EventDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDelivery.ProtoReflect.Descriptor instead.
func (*EventDelivery) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *EventDelivery) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *EventDelivery) GetEnvelope() *EventEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *EventDelivery) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type SubscribeServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*SubscribeServerMessage_Delivery
	Kind          isSubscribeServerMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServerMessage) Reset() {
	*x = SubscribeServerMessage{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServerMessage) ProtoMessage() {}

func (x *SubscribeServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServerMessage.ProtoReflect.Descriptor instead.
func (*SubscribeServerMessage) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeServerMessage) GetKind() isSubscribeServerMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *SubscribeServerMessage) GetDelivery() *EventDelivery {
	if x != nil {
		if x, ok := x.Kind.(*SubscribeServerMessage_Delivery); ok {
			return x.Delivery
		}
	}
	return nil
}

type isSubscribeServerMessage_Kind interface {
	isSubscribeServerMessage_Kind()
}

type SubscribeServerMessage_Delivery struct {
	Delivery *EventDelivery `protobuf:"bytes,1,opt,name=delivery,proto3,oneof"`
}

func (*SubscribeServerMessage_Delivery) isSubscribeServerMessage_Kind() {}

type ReplayDlqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDlqRequest) Reset() {
	*x = ReplayDlqRequest{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDlqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDlqRequest) ProtoMessage() {}

func (x *ReplayDlqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDlqRequest.ProtoReflect.Descriptor instead.
func (*ReplayDlqRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *ReplayDlqRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ReplayDlqResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDlqResponse) Reset() {
	*x = ReplayDlqResponse{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDlqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDlqResponse) ProtoMessage() {}

func (x *ReplayDlqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDlqResponse.ProtoReflect.Descriptor instead.
func (*ReplayDlqResponse) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *ReplayDlqResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ListDlqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDlqRequest) Reset() {
	*x = ListDlqRequest{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDlqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDlqRequest) ProtoMessage() {}

func (x *ListDlqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDlqRequest.ProtoReflect.Descriptor instead.
func (*ListDlqRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *ListDlqRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDlqRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type DlqEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventName       string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	ConsumerService string                 `protobuf:"bytes,3,opt,name=consumer_service,json=consumerService,proto3" json:"consumer_service,omitempty"`
	LastError       string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	DlqAtUnixMs     int64                  `protobuf:"varint,5,opt,name=dlq_at_unix_ms,json=dlqAtUnixMs,proto3" json:"dlq_at_unix_ms,omitempty"`
	ReplayCount     int32                  `protobuf:"varint,6,opt,name=replay_count,json=replayCount,proto3" json:"replay_count,omitempty"`
	TotalAttempts   int32                  `protobuf:"varint,7,opt,name=total_attempts,json=totalAttempts,proto3" json:"total_attempts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DlqEntry) Reset() {
	*x = DlqEntry{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlqEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlqEntry) ProtoMessage() {}

func (x *DlqEntry) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlqEntry.ProtoReflect.Descriptor instead.
func (*DlqEntry) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{13}
}

func (x *DlqEntry) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DlqEntry) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *DlqEntry) GetConsumerService() string {
	if x != nil {
		return x.ConsumerService
	}
	return ""
}

func (x *DlqEntry) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *DlqEntry) GetDlqAtUnixMs() int64 {
	if x != nil {
		return x.DlqAtUnixMs
	}
	return 0
}

func (x *DlqEntry) GetReplayCount() int32 {
	if x != nil {
		return x.ReplayCount
	}
	return 0
}

func (x *DlqEntry) GetTotalAttempts() int32 {
	if x != nil {
		return x.TotalAttempts
	}
	return 0
}

type ListDlqResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DlqEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDlqResponse) Reset() {
	*x = ListDlqResponse{}
	mi := &file_servicebridge_v1_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDlqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDlqResponse) ProtoMessage() {}

func (x *ListDlqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDlqResponse.ProtoReflect.Descriptor instead.
func (*ListDlqResponse) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_events_proto_rawDescGZIP(), []int{14}
}

func (x *ListDlqResponse) GetEntries() []*DlqEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListDlqResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_servicebridge_v1_events_proto protoreflect.FileDescriptor

const file_servicebridge_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1dservicebridge/v1/events.proto\x12\x10servicebridge.v1\"\xdc\x03\n" +
	"\rEventEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12#\n" +
	"\rcontract_hash\x18\x04 \x01(\tR\fcontractHash\x12#\n" +
	"\rpartition_key\x18\x05 \x01(\tR\fpartitionKey\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12&\n" +
	"\x0ffire_and_forget\x18\a \x01(\bR\rfireAndForget\x12F\n" +
	"\aheaders\x18\b \x03(\v2,.servicebridge.v1.EventEnvelope.HeadersEntryR\aheaders\x12-\n" +
	"\x13occurred_at_unix_ms\x18\t \x01(\x03R\x10occurredAtUnixMs\x12\x1c\n" +
	"\n" +
	"x_sb_trace\x18\n" +
	" \x01(\tR\bxSbTrace\x12!\n" +
	"\fpayload_json\x18\v \x01(\fR\vpayloadJson\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\x0ePublishRequest\x120\n" +
	"\x14publisher_service_id\x18\x01 \x01(\tR\x12publisherServiceId\x122\n" +
	"\x15publisher_instance_id\x18\x02 \x01(\tR\x13publisherInstanceId\x127\n" +
	"\x06events\x18\x03 \x03(\v2\x1f.servicebridge.v1.EventEnvelopeR\x06events\"\x82\x01\n" +
	"\x12PublishStatusEntry\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.servicebridge.v1.PublishStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"Q\n" +
	"\x0fPublishResponse\x12>\n" +
	"\aresults\x18\x01 \x03(\v2$.servicebridge.v1.PublishStatusEntryR\aresults\"\x9d\x01\n" +
	"\rSubscribeInit\x122\n" +
	"\x15subscriber_service_id\x18\x01 \x01(\tR\x13subscriberServiceId\x124\n" +
	"\x16subscriber_instance_id\x18\x02 \x01(\tR\x14subscriberInstanceId\x12\"\n" +
	"\rmax_in_flight\x18\x03 \x01(\x05R\vmaxInFlight\"A\n" +
	"\x03Ack\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\fR\aeventId\"g\n" +
	"\x04Nack\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\fR\aeventId\"\xb0\x01\n" +
	"\x16SubscribeClientMessage\x125\n" +
	"\x04init\x18\x01 \x01(\v2\x1f.servicebridge.v1.SubscribeInitH\x00R\x04init\x12)\n" +
	"\x03ack\x18\x02 \x01(\v2\x15.servicebridge.v1.AckH\x00R\x03ack\x12,\n" +
	"\x04nack\x18\x03 \x01(\v2\x16.servicebridge.v1.NackH\x00R\x04nackB\x06\n" +
	"\x04kind\"\x87\x01\n" +
	"\rEventDelivery\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12;\n" +
	"\benvelope\x18\x02 \x01(\v2\x1f.servicebridge.v1.EventEnvelopeR\benvelope\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\"_\n" +
	"\x16SubscribeServerMessage\x12=\n" +
	"\bdelivery\x18\x01 \x01(\v2\x1f.servicebridge.v1.EventDeliveryH\x00R\bdeliveryB\x06\n" +
	"\x04kind\"-\n" +
	"\x10ReplayDlqRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\".\n" +
	"\x11ReplayDlqResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\">\n" +
	"\x0eListDlqRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"\xfd\x01\n" +
	"\bDlqEntry\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12)\n" +
	"\x10consumer_service\x18\x03 \x01(\tR\x0fconsumerService\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\x12#\n" +
	"\x0edlq_at_unix_ms\x18\x05 \x01(\x03R\vdlqAtUnixMs\x12!\n" +
	"\freplay_count\x18\x06 \x01(\x05R\vreplayCount\x12%\n" +
	"\x0etotal_attempts\x18\a \x01(\x05R\rtotalAttempts\"h\n" +
	"\x0fListDlqResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.servicebridge.v1.DlqEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor*\xc4\x01\n" +
	"\rPublishStatus\x12\x1e\n" +
	"\x1aPUBLISH_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PUBLISH_STATUS_ACCEPTED\x10\x01\x12%\n" +
	"!PUBLISH_STATUS_REJECTED_DUPLICATE\x10\x03\x12(\n" +
	"$PUBLISH_STATUS_REJECTED_INVALID_NAME\x10\x05\x12%\n" +
	"!PUBLISH_STATUS_REJECTED_FORBIDDEN\x10\x062\xe3\x02\n" +
	"\x06Events\x12N\n" +
	"\aPublish\x12 .servicebridge.v1.PublishRequest\x1a!.servicebridge.v1.PublishResponse\x12c\n" +
	"\tSubscribe\x12(.servicebridge.v1.SubscribeClientMessage\x1a(.servicebridge.v1.SubscribeServerMessage(\x010\x01\x12T\n" +
	"\tReplayDlq\x12\".servicebridge.v1.ReplayDlqRequest\x1a#.servicebridge.v1.ReplayDlqResponse\x12N\n" +
	"\aListDlq\x12 .servicebridge.v1.ListDlqRequest\x1a!.servicebridge.v1.ListDlqResponseBCZAgithub.com/service-bridge/runtime/internal/pb/servicebridge/v1;pbb\x06proto3"

var (
	file_servicebridge_v1_events_proto_rawDescOnce sync.Once
	file_servicebridge_v1_events_proto_rawDescData []byte
)

func file_servicebridge_v1_events_proto_rawDescGZIP() []byte {
	file_servicebridge_v1_events_proto_rawDescOnce.Do(func() {
		file_servicebridge_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servicebridge_v1_events_proto_rawDesc), len(file_servicebridge_v1_events_proto_rawDesc)))
	})
	return file_servicebridge_v1_events_proto_rawDescData
}

var file_servicebridge_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_servicebridge_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_servicebridge_v1_events_proto_goTypes = []any{
	(PublishStatus)(0),             // 0: servicebridge.v1.PublishStatus
	(*EventEnvelope)(nil),          // 1: servicebridge.v1.EventEnvelope
	(*PublishRequest)(nil),         // 2: servicebridge.v1.PublishRequest
	(*PublishStatusEntry)(nil),     // 3: servicebridge.v1.PublishStatusEntry
	(*PublishResponse)(nil),        // 4: servicebridge.v1.PublishResponse
	(*SubscribeInit)(nil),          // 5: servicebridge.v1.SubscribeInit
	(*Ack)(nil),                    // 6: servicebridge.v1.Ack
	(*Nack)(nil),                   // 7: servicebridge.v1.Nack
	(*SubscribeClientMessage)(nil), // 8: servicebridge.v1.SubscribeClientMessage
	(*EventDelivery)(nil),          // 9: servicebridge.v1.EventDelivery
	(*SubscribeServerMessage)(nil), // 10: servicebridge.v1.SubscribeServerMessage
	(*ReplayDlqRequest)(nil),       // 11: servicebridge.v1.ReplayDlqRequest
	(*ReplayDlqResponse)(nil),      // 12: servicebridge.v1.ReplayDlqResponse
	(*ListDlqRequest)(nil),         // 13: servicebridge.v1.ListDlqRequest
	(*DlqEntry)(nil),               // 14: servicebridge.v1.DlqEntry
	(*ListDlqResponse)(nil),        // 15: servicebridge.v1.ListDlqResponse
	nil,                            // 16: servicebridge.v1.EventEnvelope.HeadersEntry
}
var file_servicebridge_v1_events_proto_depIdxs = []int32{
	16, // 0: servicebridge.v1.EventEnvelope.headers:type_name -> servicebridge.v1.EventEnvelope.HeadersEntry
	1,  // 1: servicebridge.v1.PublishRequest.events:type_name -> servicebridge.v1.EventEnvelope
	0,  // 2: servicebridge.v1.PublishStatusEntry.status:type_name -> servicebridge.v1.PublishStatus
	3,  // 3: servicebridge.v1.PublishResponse.results:type_name -> servicebridge.v1.PublishStatusEntry
	5,  // 4: servicebridge.v1.SubscribeClientMessage.init:type_name -> servicebridge.v1.SubscribeInit
	6,  // 5: servicebridge.v1.SubscribeClientMessage.ack:type_name -> servicebridge.v1.Ack
	7,  // 6: servicebridge.v1.SubscribeClientMessage.nack:type_name -> servicebridge.v1.Nack
	1,  // 7: servicebridge.v1.EventDelivery.envelope:type_name -> servicebridge.v1.EventEnvelope
	9,  // 8: servicebridge.v1.SubscribeServerMessage.delivery:type_name -> servicebridge.v1.EventDelivery
	14, // 9: servicebridge.v1.ListDlqResponse.entries:type_name -> servicebridge.v1.DlqEntry
	2,  // 10: servicebridge.v1.Events.Publish:input_type -> servicebridge.v1.PublishRequest
	8,  // 11: servicebridge.v1.Events.Subscribe:input_type -> servicebridge.v1.SubscribeClientMessage
	11, // 12: servicebridge.v1.Events.ReplayDlq:input_type -> servicebridge.v1.ReplayDlqRequest
	13, // 13: servicebridge.v1.Events.ListDlq:input_type -> servicebridge.v1.ListDlqRequest
	4,  // 14: servicebridge.v1.Events.Publish:output_type -> servicebridge.v1.PublishResponse
	10, // 15: servicebridge.v1.Events.Subscribe:output_type -> servicebridge.v1.SubscribeServerMessage
	12, // 16: servicebridge.v1.Events.ReplayDlq:output_type -> servicebridge.v1.ReplayDlqResponse
	15, // 17: servicebridge.v1.Events.ListDlq:output_type -> servicebridge.v1.ListDlqResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_servicebridge_v1_events_proto_init() }
func file_servicebridge_v1_events_proto_init() {
	if File_servicebridge_v1_events_proto != nil {
		return
	}
	file_servicebridge_v1_events_proto_msgTypes[7].OneofWrappers = []any{
		(*SubscribeClientMessage_Init)(nil),
		(*SubscribeClientMessage_Ack)(nil),
		(*SubscribeClientMessage_Nack)(nil),
	}
	file_servicebridge_v1_events_proto_msgTypes[9].OneofWrappers = []any{
		(*SubscribeServerMessage_Delivery)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servicebridge_v1_events_proto_rawDesc), len(file_servicebridge_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicebridge_v1_events_proto_goTypes,
		DependencyIndexes: file_servicebridge_v1_events_proto_depIdxs,
		EnumInfos:         file_servicebridge_v1_events_proto_enumTypes,
		MessageInfos:      file_servicebridge_v1_events_proto_msgTypes,
	}.Build()
	File_servicebridge_v1_events_proto = out.File
	file_servicebridge_v1_events_proto_goTypes = nil
	file_servicebridge_v1_events_proto_depIdxs = nil
}
