// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: servicebridge/v1/invoke.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Invoke_Unary_FullMethodName  = "/servicebridge.v1.Invoke/Unary"
	Invoke_Stream_FullMethodName = "/servicebridge.v1.Invoke/Stream"
)

// InvokeClient is the client API for Invoke service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Invoke — proxy RPC сервис на рантайме.
// Принимает вызов от caller-SDK, резолвит инстанс target-сервиса, проксирует Call.Unary к нему.
// Payload — passthrough bytes, рантайм не декодирует.
type InvokeClient interface {
	Unary(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	// Stream — proxy server-side streaming. Runtime получает один запрос,
	// открывает Call.Stream к выбранному callee, пробрасывает chunks обратно.
	Stream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeChunk], error)
}

type invokeClient struct {
	cc grpc.ClientConnInterface
}

func NewInvokeClient(cc grpc.ClientConnInterface) InvokeClient {
	return &invokeClient{cc}
}

func (c *invokeClient) Unary(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, Invoke_Unary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invokeClient) Stream(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Invoke_ServiceDesc.Streams[0], Invoke_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InvokeRequest, InvokeChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Invoke_StreamClient = grpc.ServerStreamingClient[InvokeChunk]

// InvokeServer is the server API for Invoke service.
// All implementations should embed UnimplementedInvokeServer
// for forward compatibility.
//
// Invoke — proxy RPC сервис на рантайме.
// Принимает вызов от caller-SDK, резолвит инстанс target-сервиса, проксирует Call.Unary к нему.
// Payload — passthrough bytes, рантайм не декодирует.
type InvokeServer interface {
	Unary(context.Context, *InvokeRequest) (*InvokeResponse, error)
	// Stream — proxy server-side streaming. Runtime получает один запрос,
	// открывает Call.Stream к выбранному callee, пробрасывает chunks обратно.
	Stream(*InvokeRequest, grpc.ServerStreamingServer[InvokeChunk]) error
}

// UnimplementedInvokeServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvokeServer struct{}

func (UnimplementedInvokeServer) Unary(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unary not implemented")
}
func (UnimplementedInvokeServer) Stream(*InvokeRequest, grpc.ServerStreamingServer[InvokeChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedInvokeServer) testEmbeddedByValue() {}

// UnsafeInvokeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvokeServer will
// result in compilation errors.
type UnsafeInvokeServer interface {
	mustEmbedUnimplementedInvokeServer()
}

func RegisterInvokeServer(s grpc.ServiceRegistrar, srv InvokeServer) {
	// If the following call pancis, it indicates UnimplementedInvokeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Invoke_ServiceDesc, srv)
}

func _Invoke_Unary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokeServer).Unary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Invoke_Unary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokeServer).Unary(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invoke_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InvokeServer).Stream(m, &grpc.GenericServerStream[InvokeRequest, InvokeChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Invoke_StreamServer = grpc.ServerStreamingServer[InvokeChunk]

// Invoke_ServiceDesc is the grpc.ServiceDesc for Invoke service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Invoke_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicebridge.v1.Invoke",
	HandlerType: (*InvokeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unary",
			Handler:    _Invoke_Unary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Invoke_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "servicebridge/v1/invoke.proto",
}
