// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: servicebridge/v1/telemetry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Channel classifies the transport/execution context of an operation.
// Mirrors the SQL CHECK constraint in migration 051.
// source of truth: migrations/051_operations.up.sql
type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_HTTP                Channel = 1
	Channel_RPC                 Channel = 2
	Channel_EVENT               Channel = 3
	Channel_WORKFLOW            Channel = 4
	Channel_JOB                 Channel = 5
	Channel_USER                Channel = 6
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "HTTP",
		2: "RPC",
		3: "EVENT",
		4: "WORKFLOW",
		5: "JOB",
		6: "USER",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"HTTP":                1,
		"RPC":                 2,
		"EVENT":               3,
		"WORKFLOW":            4,
		"JOB":                 5,
		"USER":                6,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_servicebridge_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_servicebridge_v1_telemetry_proto_enumTypes[0]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

// Status represents the lifecycle state of an operation.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_PENDING            Status = 1
	Status_SUCCESS            Status = 2
	Status_ERROR              Status = 3
	Status_TIMEOUT            Status = 4
	Status_ABANDONED          Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "SUCCESS",
		3: "ERROR",
		4: "TIMEOUT",
		5: "ABANDONED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"PENDING":            1,
		"SUCCESS":            2,
		"ERROR":              3,
		"TIMEOUT":            4,
		"ABANDONED":          5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_servicebridge_v1_telemetry_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_servicebridge_v1_telemetry_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_servicebridge_v1_telemetry_proto_enumTypes[2].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_servicebridge_v1_telemetry_proto_enumTypes[2]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

type MetricKind int32

const (
	MetricKind_METRIC_KIND_UNSPECIFIED MetricKind = 0
	MetricKind_METRIC_KIND_COUNTER     MetricKind = 1
	MetricKind_METRIC_KIND_GAUGE       MetricKind = 2
	MetricKind_METRIC_KIND_HISTOGRAM   MetricKind = 3
)

// Enum value maps for MetricKind.
var (
	MetricKind_name = map[int32]string{
		0: "METRIC_KIND_UNSPECIFIED",
		1: "METRIC_KIND_COUNTER",
		2: "METRIC_KIND_GAUGE",
		3: "METRIC_KIND_HISTOGRAM",
	}
	MetricKind_value = map[string]int32{
		"METRIC_KIND_UNSPECIFIED": 0,
		"METRIC_KIND_COUNTER":     1,
		"METRIC_KIND_GAUGE":       2,
		"METRIC_KIND_HISTOGRAM":   3,
	}
)

func (x MetricKind) Enum() *MetricKind {
	p := new(MetricKind)
	*p = x
	return p
}

func (x MetricKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricKind) Descriptor() protoreflect.EnumDescriptor {
	return file_servicebridge_v1_telemetry_proto_enumTypes[3].Descriptor()
}

func (MetricKind) Type() protoreflect.EnumType {
	return &file_servicebridge_v1_telemetry_proto_enumTypes[3]
}

func (x MetricKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricKind.Descriptor instead.
func (MetricKind) EnumDescriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

// TelemetryBatch is the request message for the Report bidi stream.
// Each batch carries exactly one kind of payload.
// @public — см. ./README.md
type TelemetryBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*TelemetryBatch_Ops
	//	*TelemetryBatch_Logs
	//	*TelemetryBatch_Metrics
	//	*TelemetryBatch_Payloads
	Kind          isTelemetryBatch_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryBatch) GetKind() isTelemetryBatch_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TelemetryBatch) GetOps() *OpBatch {
	if x != nil {
		if x, ok := x.Kind.(*TelemetryBatch_Ops); ok {
			return x.Ops
		}
	}
	return nil
}

func (x *TelemetryBatch) GetLogs() *LogBatch {
	if x != nil {
		if x, ok := x.Kind.(*TelemetryBatch_Logs); ok {
			return x.Logs
		}
	}
	return nil
}

func (x *TelemetryBatch) GetMetrics() *MetricBatch {
	if x != nil {
		if x, ok := x.Kind.(*TelemetryBatch_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *TelemetryBatch) GetPayloads() *PayloadBatch {
	if x != nil {
		if x, ok := x.Kind.(*TelemetryBatch_Payloads); ok {
			return x.Payloads
		}
	}
	return nil
}

type isTelemetryBatch_Kind interface {
	isTelemetryBatch_Kind()
}

type TelemetryBatch_Ops struct {
	Ops *OpBatch `protobuf:"bytes,1,opt,name=ops,proto3,oneof"`
}

type TelemetryBatch_Logs struct {
	Logs *LogBatch `protobuf:"bytes,2,opt,name=logs,proto3,oneof"`
}

type TelemetryBatch_Metrics struct {
	Metrics *MetricBatch `protobuf:"bytes,3,opt,name=metrics,proto3,oneof"`
}

type TelemetryBatch_Payloads struct {
	Payloads *PayloadBatch `protobuf:"bytes,4,opt,name=payloads,proto3,oneof"`
}

func (*TelemetryBatch_Ops) isTelemetryBatch_Kind() {}

func (*TelemetryBatch_Logs) isTelemetryBatch_Kind() {}

func (*TelemetryBatch_Metrics) isTelemetryBatch_Kind() {}

func (*TelemetryBatch_Payloads) isTelemetryBatch_Kind() {}

type OpBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OpReport            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpBatch) Reset() {
	*x = OpBatch{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpBatch) ProtoMessage() {}

func (x *OpBatch) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpBatch.ProtoReflect.Descriptor instead.
func (*OpBatch) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *OpBatch) GetItems() []*OpReport {
	if x != nil {
		return x.Items
	}
	return nil
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Log                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *LogBatch) GetItems() []*Log {
	if x != nil {
		return x.Items
	}
	return nil
}

type MetricBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MetricPoint         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *MetricBatch) GetItems() []*MetricPoint {
	if x != nil {
		return x.Items
	}
	return nil
}

type PayloadBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PayloadAttachment   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadBatch) Reset() {
	*x = PayloadBatch{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadBatch) ProtoMessage() {}

func (x *PayloadBatch) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadBatch.ProtoReflect.Descriptor instead.
func (*PayloadBatch) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *PayloadBatch) GetItems() []*PayloadAttachment {
	if x != nil {
		return x.Items
	}
	return nil
}

// OpReport is a single operation lifecycle event.
// finished_at_ms absent = START frame; present = END frame (ADR 0007 §2).
// actor identity is taken from the mTLS cert on the server side (ADR-0006).
// @public — см. ./README.md
type OpReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`            // UUIDv7 canonical string
	OpId          string                 `protobuf:"bytes,2,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`                     // UUIDv7 canonical string
	ParentOpId    string                 `protobuf:"bytes,3,opt,name=parent_op_id,json=parentOpId,proto3" json:"parent_op_id,omitempty"` // empty for root
	Channel       Channel                `protobuf:"varint,4,opt,name=channel,proto3,enum=servicebridge.v1.Channel" json:"channel,omitempty"`
	Kind          uint32                 `protobuf:"varint,5,opt,name=kind,proto3" json:"kind,omitempty"`                                         // per-channel kind value; see enums.go
	Subject       string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`                                    // ADR 0007 §4 format: "channel.kind:actor/target"
	PeerServiceId string                 `protobuf:"bytes,9,opt,name=peer_service_id,json=peerServiceId,proto3" json:"peer_service_id,omitempty"` // UUID canonical string, optional
	BusinessKey   string                 `protobuf:"bytes,10,opt,name=business_key,json=businessKey,proto3" json:"business_key,omitempty"`        // idempotency/correlation key per kind
	Attempt       int32                  `protobuf:"varint,11,opt,name=attempt,proto3" json:"attempt,omitempty"`
	StartedAtMs   int64                  `protobuf:"varint,12,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`          // unix-ms
	FinishedAtMs  *int64                 `protobuf:"varint,13,opt,name=finished_at_ms,json=finishedAtMs,proto3,oneof" json:"finished_at_ms,omitempty"` // unix-ms; absent = START, present = END
	Status        Status                 `protobuf:"varint,14,opt,name=status,proto3,enum=servicebridge.v1.Status" json:"status,omitempty"`
	StatusMessage string                 `protobuf:"bytes,15,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	MetaJson      []byte                 `protobuf:"bytes,16,opt,name=meta_json,json=metaJson,proto3" json:"meta_json,omitempty"`    // per-kind structured meta; cap 8KB
	AttrsJson     []byte                 `protobuf:"bytes,17,opt,name=attrs_json,json=attrsJson,proto3" json:"attrs_json,omitempty"` // free-form key-value; cap 2KB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpReport) Reset() {
	*x = OpReport{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpReport) ProtoMessage() {}

func (x *OpReport) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpReport.ProtoReflect.Descriptor instead.
func (*OpReport) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *OpReport) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OpReport) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *OpReport) GetParentOpId() string {
	if x != nil {
		return x.ParentOpId
	}
	return ""
}

func (x *OpReport) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *OpReport) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *OpReport) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *OpReport) GetPeerServiceId() string {
	if x != nil {
		return x.PeerServiceId
	}
	return ""
}

func (x *OpReport) GetBusinessKey() string {
	if x != nil {
		return x.BusinessKey
	}
	return ""
}

func (x *OpReport) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *OpReport) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *OpReport) GetFinishedAtMs() int64 {
	if x != nil && x.FinishedAtMs != nil {
		return *x.FinishedAtMs
	}
	return 0
}

func (x *OpReport) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *OpReport) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *OpReport) GetMetaJson() []byte {
	if x != nil {
		return x.MetaJson
	}
	return nil
}

func (x *OpReport) GetAttrsJson() []byte {
	if x != nil {
		return x.AttrsJson
	}
	return nil
}

// Log is a structured log entry.
// trace_id and op_id are optional UUID canonical strings.
// @public — см. ./README.md
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtUnixMs      int64                  `protobuf:"varint,1,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=servicebridge.v1.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	FieldsJson    []byte                 `protobuf:"bytes,4,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"` // JSON-encoded Record<string, unknown>
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`          // UUID canonical, optional
	OpId          string                 `protobuf:"bytes,6,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`                   // UUID canonical, optional (renamed from span_id)
	InstanceId    string                 `protobuf:"bytes,7,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Source        string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"` // 'sdk' | 'console' | 'runtime'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *Log) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

func (x *Log) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Log) GetFieldsJson() []byte {
	if x != nil {
		return x.FieldsJson
	}
	return nil
}

func (x *Log) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Log) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *Log) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Log) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// MetricPoint is a single metric observation.
// @public — см. ./README.md
type MetricPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtUnixMs      int64                  `protobuf:"varint,1,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          MetricKind             `protobuf:"varint,3,opt,name=kind,proto3,enum=servicebridge.v1.MetricKind" json:"kind,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InstanceId    string                 `protobuf:"bytes,5,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Value         float64                `protobuf:"fixed64,6,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`                                  // UCUM: 's', 'By', '1'
	BucketsJson   []byte                 `protobuf:"bytes,8,opt,name=buckets_json,json=bucketsJson,proto3" json:"buckets_json,omitempty"` // [{le, count}] JSON for histograms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *MetricPoint) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

func (x *MetricPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricPoint) GetKind() MetricKind {
	if x != nil {
		return x.Kind
	}
	return MetricKind_METRIC_KIND_UNSPECIFIED
}

func (x *MetricPoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricPoint) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPoint) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricPoint) GetBucketsJson() []byte {
	if x != nil {
		return x.BucketsJson
	}
	return nil
}

// PayloadAttachment carries a captured request/response payload.
// @public — см. ./README.md
type PayloadAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // UUID canonical
	OpId          string                 `protobuf:"bytes,2,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`          // UUID canonical
	Direction     uint32                 `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"`           // 1=IN, 2=OUT
	Bytes         []byte                 `protobuf:"bytes,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	OriginalSize  int32                  `protobuf:"varint,5,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	ContractHash  string                 `protobuf:"bytes,6,opt,name=contract_hash,json=contractHash,proto3" json:"contract_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadAttachment) Reset() {
	*x = PayloadAttachment{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadAttachment) ProtoMessage() {}

func (x *PayloadAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadAttachment.ProtoReflect.Descriptor instead.
func (*PayloadAttachment) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *PayloadAttachment) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *PayloadAttachment) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *PayloadAttachment) GetDirection() uint32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *PayloadAttachment) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *PayloadAttachment) GetOriginalSize() int32 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *PayloadAttachment) GetContractHash() string {
	if x != nil {
		return x.ContractHash
	}
	return ""
}

// TelemetryAck is sent periodically by the server on the Report stream.
// It provides flow control and signals drain.
// @public — см. ./README.md
type TelemetryAck struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ReceivedBytesHighWater uint64                 `protobuf:"varint,1,opt,name=received_bytes_high_water,json=receivedBytesHighWater,proto3" json:"received_bytes_high_water,omitempty"`
	BackpressureLevel      uint32                 `protobuf:"varint,2,opt,name=backpressure_level,json=backpressureLevel,proto3" json:"backpressure_level,omitempty"` // 0=normal, 1=slow, 2=pause
	DropCountServerSide    uint64                 `protobuf:"varint,3,opt,name=drop_count_server_side,json=dropCountServerSide,proto3" json:"drop_count_server_side,omitempty"`
	DrainReason            string                 `protobuf:"bytes,4,opt,name=drain_reason,json=drainReason,proto3" json:"drain_reason,omitempty"` // non-empty → graceful close requested
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *TelemetryAck) GetReceivedBytesHighWater() uint64 {
	if x != nil {
		return x.ReceivedBytesHighWater
	}
	return 0
}

func (x *TelemetryAck) GetBackpressureLevel() uint32 {
	if x != nil {
		return x.BackpressureLevel
	}
	return 0
}

func (x *TelemetryAck) GetDropCountServerSide() uint64 {
	if x != nil {
		return x.DropCountServerSide
	}
	return 0
}

func (x *TelemetryAck) GetDrainReason() string {
	if x != nil {
		return x.DrainReason
	}
	return ""
}

type ListTracesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelFilter []Channel              `protobuf:"varint,1,rep,packed,name=channel_filter,json=channelFilter,proto3,enum=servicebridge.v1.Channel" json:"channel_filter,omitempty"`
	StatusFilter  []Status               `protobuf:"varint,2,rep,packed,name=status_filter,json=statusFilter,proto3,enum=servicebridge.v1.Status" json:"status_filter,omitempty"`
	FromMs        int64                  `protobuf:"varint,3,opt,name=from_ms,json=fromMs,proto3" json:"from_ms,omitempty"`
	ToMs          int64                  `protobuf:"varint,4,opt,name=to_ms,json=toMs,proto3" json:"to_ms,omitempty"`
	ServiceId     string                 `protobuf:"bytes,5,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	TextQuery     string                 `protobuf:"bytes,6,opt,name=text_query,json=textQuery,proto3" json:"text_query,omitempty"` // searched in subject + business_key
	Limit         uint32                 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,8,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracesRequest) Reset() {
	*x = ListTracesRequest{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracesRequest) ProtoMessage() {}

func (x *ListTracesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracesRequest.ProtoReflect.Descriptor instead.
func (*ListTracesRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{10}
}

func (x *ListTracesRequest) GetChannelFilter() []Channel {
	if x != nil {
		return x.ChannelFilter
	}
	return nil
}

func (x *ListTracesRequest) GetStatusFilter() []Status {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

func (x *ListTracesRequest) GetFromMs() int64 {
	if x != nil {
		return x.FromMs
	}
	return 0
}

func (x *ListTracesRequest) GetToMs() int64 {
	if x != nil {
		return x.ToMs
	}
	return 0
}

func (x *ListTracesRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ListTracesRequest) GetTextQuery() string {
	if x != nil {
		return x.TextQuery
	}
	return ""
}

func (x *ListTracesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTracesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type TraceSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // UUIDv7
	RootSubject   string                 `protobuf:"bytes,2,opt,name=root_subject,json=rootSubject,proto3" json:"root_subject,omitempty"`
	RootServiceId string                 `protobuf:"bytes,3,opt,name=root_service_id,json=rootServiceId,proto3" json:"root_service_id,omitempty"`
	StartedAtMs   int64                  `protobuf:"varint,4,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	OpCount       uint32                 `protobuf:"varint,6,opt,name=op_count,json=opCount,proto3" json:"op_count,omitempty"`
	OverallStatus Status                 `protobuf:"varint,7,opt,name=overall_status,json=overallStatus,proto3,enum=servicebridge.v1.Status" json:"overall_status,omitempty"`
	HasRunning    bool                   `protobuf:"varint,8,opt,name=has_running,json=hasRunning,proto3" json:"has_running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceSummary) Reset() {
	*x = TraceSummary{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceSummary) ProtoMessage() {}

func (x *TraceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceSummary.ProtoReflect.Descriptor instead.
func (*TraceSummary) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{11}
}

func (x *TraceSummary) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceSummary) GetRootSubject() string {
	if x != nil {
		return x.RootSubject
	}
	return ""
}

func (x *TraceSummary) GetRootServiceId() string {
	if x != nil {
		return x.RootServiceId
	}
	return ""
}

func (x *TraceSummary) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *TraceSummary) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TraceSummary) GetOpCount() uint32 {
	if x != nil {
		return x.OpCount
	}
	return 0
}

func (x *TraceSummary) GetOverallStatus() Status {
	if x != nil {
		return x.OverallStatus
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *TraceSummary) GetHasRunning() bool {
	if x != nil {
		return x.HasRunning
	}
	return false
}

type ListTracesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*TraceSummary        `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTracesResponse) Reset() {
	*x = ListTracesResponse{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTracesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTracesResponse) ProtoMessage() {}

func (x *ListTracesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTracesResponse.ProtoReflect.Descriptor instead.
func (*ListTracesResponse) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{12}
}

func (x *ListTracesResponse) GetTraces() []*TraceSummary {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *ListTracesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceRequest) Reset() {
	*x = GetTraceRequest{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceRequest) ProtoMessage() {}

func (x *GetTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceRequest.ProtoReflect.Descriptor instead.
func (*GetTraceRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{13}
}

func (x *GetTraceRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetTraceRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTraceRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type OperationView struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OpId            string                 `protobuf:"bytes,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	TraceId         string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ParentOpId      string                 `protobuf:"bytes,3,opt,name=parent_op_id,json=parentOpId,proto3" json:"parent_op_id,omitempty"`
	Channel         Channel                `protobuf:"varint,4,opt,name=channel,proto3,enum=servicebridge.v1.Channel" json:"channel,omitempty"`
	Kind            uint32                 `protobuf:"varint,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Subject         string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	ActorServiceId  string                 `protobuf:"bytes,7,opt,name=actor_service_id,json=actorServiceId,proto3" json:"actor_service_id,omitempty"`
	ActorInstanceId string                 `protobuf:"bytes,8,opt,name=actor_instance_id,json=actorInstanceId,proto3" json:"actor_instance_id,omitempty"`
	PeerServiceId   string                 `protobuf:"bytes,9,opt,name=peer_service_id,json=peerServiceId,proto3" json:"peer_service_id,omitempty"`
	BusinessKey     string                 `protobuf:"bytes,10,opt,name=business_key,json=businessKey,proto3" json:"business_key,omitempty"`
	Attempt         int32                  `protobuf:"varint,11,opt,name=attempt,proto3" json:"attempt,omitempty"`
	StartedAtMs     int64                  `protobuf:"varint,12,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	FinishedAtMs    *int64                 `protobuf:"varint,13,opt,name=finished_at_ms,json=finishedAtMs,proto3,oneof" json:"finished_at_ms,omitempty"`
	Status          Status                 `protobuf:"varint,14,opt,name=status,proto3,enum=servicebridge.v1.Status" json:"status,omitempty"`
	StatusMessage   string                 `protobuf:"bytes,15,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	MetaJson        []byte                 `protobuf:"bytes,16,opt,name=meta_json,json=metaJson,proto3" json:"meta_json,omitempty"`
	AttrsJson       []byte                 `protobuf:"bytes,17,opt,name=attrs_json,json=attrsJson,proto3" json:"attrs_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OperationView) Reset() {
	*x = OperationView{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationView) ProtoMessage() {}

func (x *OperationView) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationView.ProtoReflect.Descriptor instead.
func (*OperationView) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{14}
}

func (x *OperationView) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *OperationView) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OperationView) GetParentOpId() string {
	if x != nil {
		return x.ParentOpId
	}
	return ""
}

func (x *OperationView) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *OperationView) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *OperationView) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *OperationView) GetActorServiceId() string {
	if x != nil {
		return x.ActorServiceId
	}
	return ""
}

func (x *OperationView) GetActorInstanceId() string {
	if x != nil {
		return x.ActorInstanceId
	}
	return ""
}

func (x *OperationView) GetPeerServiceId() string {
	if x != nil {
		return x.PeerServiceId
	}
	return ""
}

func (x *OperationView) GetBusinessKey() string {
	if x != nil {
		return x.BusinessKey
	}
	return ""
}

func (x *OperationView) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *OperationView) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *OperationView) GetFinishedAtMs() int64 {
	if x != nil && x.FinishedAtMs != nil {
		return *x.FinishedAtMs
	}
	return 0
}

func (x *OperationView) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *OperationView) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *OperationView) GetMetaJson() []byte {
	if x != nil {
		return x.MetaJson
	}
	return nil
}

func (x *OperationView) GetAttrsJson() []byte {
	if x != nil {
		return x.AttrsJson
	}
	return nil
}

type GetTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*OperationView       `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Truncated     bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceResponse) Reset() {
	*x = GetTraceResponse{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceResponse) ProtoMessage() {}

func (x *GetTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceResponse.ProtoReflect.Descriptor instead.
func (*GetTraceResponse) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{15}
}

func (x *GetTraceResponse) GetOps() []*OperationView {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *GetTraceResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetTraceResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpId          string                 `protobuf:"bytes,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{16}
}

func (x *GetOperationRequest) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            *OperationView         `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{17}
}

func (x *GetOperationResponse) GetOp() *OperationView {
	if x != nil {
		return x.Op
	}
	return nil
}

type GetPayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	OpId          string                 `protobuf:"bytes,2,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	Direction     uint32                 `protobuf:"varint,3,opt,name=direction,proto3" json:"direction,omitempty"` // 1=IN, 2=OUT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayloadRequest) Reset() {
	*x = GetPayloadRequest{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayloadRequest) ProtoMessage() {}

func (x *GetPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayloadRequest.ProtoReflect.Descriptor instead.
func (*GetPayloadRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{18}
}

func (x *GetPayloadRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetPayloadRequest) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *GetPayloadRequest) GetDirection() uint32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

type GetPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawBytes      []byte                 `protobuf:"bytes,1,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"`
	DecodedBytes  []byte                 `protobuf:"bytes,2,opt,name=decoded_bytes,json=decodedBytes,proto3" json:"decoded_bytes,omitempty"`
	OriginalSize  int32                  `protobuf:"varint,3,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`
	ContractHash  string                 `protobuf:"bytes,4,opt,name=contract_hash,json=contractHash,proto3" json:"contract_hash,omitempty"`
	SchemaDrift   bool                   `protobuf:"varint,5,opt,name=schema_drift,json=schemaDrift,proto3" json:"schema_drift,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayloadResponse) Reset() {
	*x = GetPayloadResponse{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayloadResponse) ProtoMessage() {}

func (x *GetPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayloadResponse.ProtoReflect.Descriptor instead.
func (*GetPayloadResponse) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{19}
}

func (x *GetPayloadResponse) GetRawBytes() []byte {
	if x != nil {
		return x.RawBytes
	}
	return nil
}

func (x *GetPayloadResponse) GetDecodedBytes() []byte {
	if x != nil {
		return x.DecodedBytes
	}
	return nil
}

func (x *GetPayloadResponse) GetOriginalSize() int32 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *GetPayloadResponse) GetContractHash() string {
	if x != nil {
		return x.ContractHash
	}
	return ""
}

func (x *GetPayloadResponse) GetSchemaDrift() bool {
	if x != nil {
		return x.SchemaDrift
	}
	return false
}

type QueryLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FromUnixMs    int64                  `protobuf:"varint,3,opt,name=from_unix_ms,json=fromUnixMs,proto3" json:"from_unix_ms,omitempty"`
	ToUnixMs      int64                  `protobuf:"varint,4,opt,name=to_unix_ms,json=toUnixMs,proto3" json:"to_unix_ms,omitempty"`
	MinLevel      LogLevel               `protobuf:"varint,5,opt,name=min_level,json=minLevel,proto3,enum=servicebridge.v1.LogLevel" json:"min_level,omitempty"`
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // UUID canonical, optional filter
	TextQuery     string                 `protobuf:"bytes,7,opt,name=text_query,json=textQuery,proto3" json:"text_query,omitempty"`
	Limit         uint32                 `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,9,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogsRequest) Reset() {
	*x = QueryLogsRequest{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsRequest) ProtoMessage() {}

func (x *QueryLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsRequest.ProtoReflect.Descriptor instead.
func (*QueryLogsRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{20}
}

func (x *QueryLogsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *QueryLogsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *QueryLogsRequest) GetFromUnixMs() int64 {
	if x != nil {
		return x.FromUnixMs
	}
	return 0
}

func (x *QueryLogsRequest) GetToUnixMs() int64 {
	if x != nil {
		return x.ToUnixMs
	}
	return 0
}

func (x *QueryLogsRequest) GetMinLevel() LogLevel {
	if x != nil {
		return x.MinLevel
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *QueryLogsRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *QueryLogsRequest) GetTextQuery() string {
	if x != nil {
		return x.TextQuery
	}
	return ""
}

func (x *QueryLogsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryLogsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type QueryLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Log                 `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogsResponse) Reset() {
	*x = QueryLogsResponse{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsResponse) ProtoMessage() {}

func (x *QueryLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsResponse.ProtoReflect.Descriptor instead.
func (*QueryLogsResponse) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{21}
}

func (x *QueryLogsResponse) GetEntries() []*Log {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *QueryLogsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type QueryMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FromUnixMs    int64                  `protobuf:"varint,4,opt,name=from_unix_ms,json=fromUnixMs,proto3" json:"from_unix_ms,omitempty"`
	ToUnixMs      int64                  `protobuf:"varint,5,opt,name=to_unix_ms,json=toUnixMs,proto3" json:"to_unix_ms,omitempty"`
	LabelFilters  map[string]string      `protobuf:"bytes,6,rep,name=label_filters,json=labelFilters,proto3" json:"label_filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StepSeconds   uint32                 `protobuf:"varint,7,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	Percentiles   []float64              `protobuf:"fixed64,8,rep,packed,name=percentiles,proto3" json:"percentiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetricsRequest) Reset() {
	*x = QueryMetricsRequest{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsRequest) ProtoMessage() {}

func (x *QueryMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsRequest.ProtoReflect.Descriptor instead.
func (*QueryMetricsRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{22}
}

func (x *QueryMetricsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *QueryMetricsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *QueryMetricsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryMetricsRequest) GetFromUnixMs() int64 {
	if x != nil {
		return x.FromUnixMs
	}
	return 0
}

func (x *QueryMetricsRequest) GetToUnixMs() int64 {
	if x != nil {
		return x.ToUnixMs
	}
	return 0
}

func (x *QueryMetricsRequest) GetLabelFilters() map[string]string {
	if x != nil {
		return x.LabelFilters
	}
	return nil
}

func (x *QueryMetricsRequest) GetStepSeconds() uint32 {
	if x != nil {
		return x.StepSeconds
	}
	return 0
}

func (x *QueryMetricsRequest) GetPercentiles() []float64 {
	if x != nil {
		return x.Percentiles
	}
	return nil
}

type MetricSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	TsUnixMs      []int64                `protobuf:"varint,4,rep,packed,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	Values        []float64              `protobuf:"fixed64,5,rep,packed,name=values,proto3" json:"values,omitempty"`                        // bucket average
	MaxValues     []float64              `protobuf:"fixed64,6,rep,packed,name=max_values,json=maxValues,proto3" json:"max_values,omitempty"` // bucket peak (parallel to values), preserves spikes hidden by the average
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSeries) Reset() {
	*x = MetricSeries{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSeries) ProtoMessage() {}

func (x *MetricSeries) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSeries.ProtoReflect.Descriptor instead.
func (*MetricSeries) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{23}
}

func (x *MetricSeries) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricSeries) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricSeries) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *MetricSeries) GetTsUnixMs() []int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return nil
}

func (x *MetricSeries) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *MetricSeries) GetMaxValues() []float64 {
	if x != nil {
		return x.MaxValues
	}
	return nil
}

type QueryMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*MetricSeries        `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetricsResponse) Reset() {
	*x = QueryMetricsResponse{}
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsResponse) ProtoMessage() {}

func (x *QueryMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_telemetry_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsResponse.ProtoReflect.Descriptor instead.
func (*QueryMetricsResponse) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_telemetry_proto_rawDescGZIP(), []int{24}
}

func (x *QueryMetricsResponse) GetSeries() []*MetricSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

var File_servicebridge_v1_telemetry_proto protoreflect.FileDescriptor

const file_servicebridge_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	" servicebridge/v1/telemetry.proto\x12\x10servicebridge.v1\"\xf2\x01\n" +
	"\x0eTelemetryBatch\x12-\n" +
	"\x03ops\x18\x01 \x01(\v2\x19.servicebridge.v1.OpBatchH\x00R\x03ops\x120\n" +
	"\x04logs\x18\x02 \x01(\v2\x1a.servicebridge.v1.LogBatchH\x00R\x04logs\x129\n" +
	"\ametrics\x18\x03 \x01(\v2\x1d.servicebridge.v1.MetricBatchH\x00R\ametrics\x12<\n" +
	"\bpayloads\x18\x04 \x01(\v2\x1e.servicebridge.v1.PayloadBatchH\x00R\bpayloadsB\x06\n" +
	"\x04kind\";\n" +
	"\aOpBatch\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.servicebridge.v1.OpReportR\x05items\"7\n" +
	"\bLogBatch\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.servicebridge.v1.LogR\x05items\"B\n" +
	"\vMetricBatch\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.servicebridge.v1.MetricPointR\x05items\"I\n" +
	"\fPayloadBatch\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.servicebridge.v1.PayloadAttachmentR\x05items\"\xcc\x04\n" +
	"\bOpReport\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x13\n" +
	"\x05op_id\x18\x02 \x01(\tR\x04opId\x12 \n" +
	"\fparent_op_id\x18\x03 \x01(\tR\n" +
	"parentOpId\x123\n" +
	"\achannel\x18\x04 \x01(\x0e2\x19.servicebridge.v1.ChannelR\achannel\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\rR\x04kind\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12&\n" +
	"\x0fpeer_service_id\x18\t \x01(\tR\rpeerServiceId\x12!\n" +
	"\fbusiness_key\x18\n" +
	" \x01(\tR\vbusinessKey\x12\x18\n" +
	"\aattempt\x18\v \x01(\x05R\aattempt\x12\"\n" +
	"\rstarted_at_ms\x18\f \x01(\x03R\vstartedAtMs\x12)\n" +
	"\x0efinished_at_ms\x18\r \x01(\x03H\x00R\ffinishedAtMs\x88\x01\x01\x120\n" +
	"\x06status\x18\x0e \x01(\x0e2\x18.servicebridge.v1.StatusR\x06status\x12%\n" +
	"\x0estatus_message\x18\x0f \x01(\tR\rstatusMessage\x12\x1b\n" +
	"\tmeta_json\x18\x10 \x01(\fR\bmetaJson\x12\x1d\n" +
	"\n" +
	"attrs_json\x18\x11 \x01(\fR\tattrsJsonB\x11\n" +
	"\x0f_finished_at_msJ\x04\b\a\x10\bJ\x04\b\b\x10\tR\x10actor_service_idR\x11actor_instance_id\"\xf9\x01\n" +
	"\x03Log\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x01 \x01(\x03R\batUnixMs\x120\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1a.servicebridge.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vfields_json\x18\x04 \x01(\fR\n" +
	"fieldsJson\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x13\n" +
	"\x05op_id\x18\x06 \x01(\tR\x04opId\x12\x1f\n" +
	"\vinstance_id\x18\a \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\"\xdd\x02\n" +
	"\vMetricPoint\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x01 \x01(\x03R\batUnixMs\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1c.servicebridge.v1.MetricKindR\x04kind\x12A\n" +
	"\x06labels\x18\x04 \x03(\v2).servicebridge.v1.MetricPoint.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vinstance_id\x18\x05 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unit\x12!\n" +
	"\fbuckets_json\x18\b \x01(\fR\vbucketsJson\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x01\n" +
	"\x11PayloadAttachment\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x13\n" +
	"\x05op_id\x18\x02 \x01(\tR\x04opId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\rR\tdirection\x12\x14\n" +
	"\x05bytes\x18\x04 \x01(\fR\x05bytes\x12#\n" +
	"\roriginal_size\x18\x05 \x01(\x05R\foriginalSize\x12#\n" +
	"\rcontract_hash\x18\x06 \x01(\tR\fcontractHash\"\xd0\x01\n" +
	"\fTelemetryAck\x129\n" +
	"\x19received_bytes_high_water\x18\x01 \x01(\x04R\x16receivedBytesHighWater\x12-\n" +
	"\x12backpressure_level\x18\x02 \x01(\rR\x11backpressureLevel\x123\n" +
	"\x16drop_count_server_side\x18\x03 \x01(\x04R\x13dropCountServerSide\x12!\n" +
	"\fdrain_reason\x18\x04 \x01(\tR\vdrainReason\"\xae\x02\n" +
	"\x11ListTracesRequest\x12@\n" +
	"\x0echannel_filter\x18\x01 \x03(\x0e2\x19.servicebridge.v1.ChannelR\rchannelFilter\x12=\n" +
	"\rstatus_filter\x18\x02 \x03(\x0e2\x18.servicebridge.v1.StatusR\fstatusFilter\x12\x17\n" +
	"\afrom_ms\x18\x03 \x01(\x03R\x06fromMs\x12\x13\n" +
	"\x05to_ms\x18\x04 \x01(\x03R\x04toMs\x12\x1d\n" +
	"\n" +
	"service_id\x18\x05 \x01(\tR\tserviceId\x12\x1d\n" +
	"\n" +
	"text_query\x18\x06 \x01(\tR\ttextQuery\x12\x14\n" +
	"\x05limit\x18\a \x01(\rR\x05limit\x12\x16\n" +
	"\x06cursor\x18\b \x01(\tR\x06cursor\"\xb6\x02\n" +
	"\fTraceSummary\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12!\n" +
	"\froot_subject\x18\x02 \x01(\tR\vrootSubject\x12&\n" +
	"\x0froot_service_id\x18\x03 \x01(\tR\rrootServiceId\x12\"\n" +
	"\rstarted_at_ms\x18\x04 \x01(\x03R\vstartedAtMs\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\x12\x19\n" +
	"\bop_count\x18\x06 \x01(\rR\aopCount\x12?\n" +
	"\x0eoverall_status\x18\a \x01(\x0e2\x18.servicebridge.v1.StatusR\roverallStatus\x12\x1f\n" +
	"\vhas_running\x18\b \x01(\bR\n" +
	"hasRunning\"m\n" +
	"\x12ListTracesResponse\x126\n" +
	"\x06traces\x18\x01 \x03(\v2\x1e.servicebridge.v1.TraceSummaryR\x06traces\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"Z\n" +
	"\x0fGetTraceRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\xab\x05\n" +
	"\rOperationView\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\tR\x04opId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12 \n" +
	"\fparent_op_id\x18\x03 \x01(\tR\n" +
	"parentOpId\x123\n" +
	"\achannel\x18\x04 \x01(\x0e2\x19.servicebridge.v1.ChannelR\achannel\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\rR\x04kind\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12(\n" +
	"\x10actor_service_id\x18\a \x01(\tR\x0eactorServiceId\x12*\n" +
	"\x11actor_instance_id\x18\b \x01(\tR\x0factorInstanceId\x12&\n" +
	"\x0fpeer_service_id\x18\t \x01(\tR\rpeerServiceId\x12!\n" +
	"\fbusiness_key\x18\n" +
	" \x01(\tR\vbusinessKey\x12\x18\n" +
	"\aattempt\x18\v \x01(\x05R\aattempt\x12\"\n" +
	"\rstarted_at_ms\x18\f \x01(\x03R\vstartedAtMs\x12)\n" +
	"\x0efinished_at_ms\x18\r \x01(\x03H\x00R\ffinishedAtMs\x88\x01\x01\x120\n" +
	"\x06status\x18\x0e \x01(\x0e2\x18.servicebridge.v1.StatusR\x06status\x12%\n" +
	"\x0estatus_message\x18\x0f \x01(\tR\rstatusMessage\x12\x1b\n" +
	"\tmeta_json\x18\x10 \x01(\fR\bmetaJson\x12\x1d\n" +
	"\n" +
	"attrs_json\x18\x11 \x01(\fR\tattrsJsonB\x11\n" +
	"\x0f_finished_at_msJ\x04\b\x12\x10\x13J\x04\b\x13\x10\x14R\x12decoded_payload_inR\x13decoded_payload_out\"\x84\x01\n" +
	"\x10GetTraceResponse\x121\n" +
	"\x03ops\x18\x01 \x03(\v2\x1f.servicebridge.v1.OperationViewR\x03ops\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"*\n" +
	"\x13GetOperationRequest\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\tR\x04opId\"G\n" +
	"\x14GetOperationResponse\x12/\n" +
	"\x02op\x18\x01 \x01(\v2\x1f.servicebridge.v1.OperationViewR\x02op\"a\n" +
	"\x11GetPayloadRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x13\n" +
	"\x05op_id\x18\x02 \x01(\tR\x04opId\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\rR\tdirection\"\xc3\x01\n" +
	"\x12GetPayloadResponse\x12\x1b\n" +
	"\traw_bytes\x18\x01 \x01(\fR\brawBytes\x12#\n" +
	"\rdecoded_bytes\x18\x02 \x01(\fR\fdecodedBytes\x12#\n" +
	"\roriginal_size\x18\x03 \x01(\x05R\foriginalSize\x12#\n" +
	"\rcontract_hash\x18\x04 \x01(\tR\fcontractHash\x12!\n" +
	"\fschema_drift\x18\x05 \x01(\bR\vschemaDrift\"\xb3\x02\n" +
	"\x10QueryLogsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12 \n" +
	"\ffrom_unix_ms\x18\x03 \x01(\x03R\n" +
	"fromUnixMs\x12\x1c\n" +
	"\n" +
	"to_unix_ms\x18\x04 \x01(\x03R\btoUnixMs\x127\n" +
	"\tmin_level\x18\x05 \x01(\x0e2\x1a.servicebridge.v1.LogLevelR\bminLevel\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"text_query\x18\a \x01(\tR\ttextQuery\x12\x14\n" +
	"\x05limit\x18\b \x01(\rR\x05limit\x12\x16\n" +
	"\x06cursor\x18\t \x01(\tR\x06cursor\"e\n" +
	"\x11QueryLogsResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.servicebridge.v1.LogR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x8d\x03\n" +
	"\x13QueryMetricsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\ffrom_unix_ms\x18\x04 \x01(\x03R\n" +
	"fromUnixMs\x12\x1c\n" +
	"\n" +
	"to_unix_ms\x18\x05 \x01(\x03R\btoUnixMs\x12\\\n" +
	"\rlabel_filters\x18\x06 \x03(\v27.servicebridge.v1.QueryMetricsRequest.LabelFiltersEntryR\flabelFilters\x12!\n" +
	"\fstep_seconds\x18\a \x01(\rR\vstepSeconds\x12 \n" +
	"\vpercentiles\x18\b \x03(\x01R\vpercentiles\x1a?\n" +
	"\x11LabelFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x02\n" +
	"\fMetricSeries\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12B\n" +
	"\x06labels\x18\x02 \x03(\v2*.servicebridge.v1.MetricSeries.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x04 \x03(\x03R\btsUnixMs\x12\x16\n" +
	"\x06values\x18\x05 \x03(\x01R\x06values\x12\x1d\n" +
	"\n" +
	"max_values\x18\x06 \x03(\x01R\tmaxValues\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x14QueryMetricsResponse\x126\n" +
	"\x06series\x18\x01 \x03(\v2\x1e.servicebridge.v1.MetricSeriesR\x06series*a\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\a\n" +
	"\x03RPC\x10\x02\x12\t\n" +
	"\x05EVENT\x10\x03\x12\f\n" +
	"\bWORKFLOW\x10\x04\x12\a\n" +
	"\x03JOB\x10\x05\x12\b\n" +
	"\x04USER\x10\x06*a\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\v\n" +
	"\aTIMEOUT\x10\x04\x12\r\n" +
	"\tABANDONED\x10\x05*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04*t\n" +
	"\n" +
	"MetricKind\x12\x1b\n" +
	"\x17METRIC_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13METRIC_KIND_COUNTER\x10\x01\x12\x15\n" +
	"\x11METRIC_KIND_GAUGE\x10\x02\x12\x19\n" +
	"\x15METRIC_KIND_HISTOGRAM\x10\x032\xf4\x04\n" +
	"\tTelemetry\x12N\n" +
	"\x06Report\x12 .servicebridge.v1.TelemetryBatch\x1a\x1e.servicebridge.v1.TelemetryAck(\x010\x01\x12W\n" +
	"\n" +
	"ListTraces\x12#.servicebridge.v1.ListTracesRequest\x1a$.servicebridge.v1.ListTracesResponse\x12Q\n" +
	"\bGetTrace\x12!.servicebridge.v1.GetTraceRequest\x1a\".servicebridge.v1.GetTraceResponse\x12]\n" +
	"\fGetOperation\x12%.servicebridge.v1.GetOperationRequest\x1a&.servicebridge.v1.GetOperationResponse\x12W\n" +
	"\n" +
	"GetPayload\x12#.servicebridge.v1.GetPayloadRequest\x1a$.servicebridge.v1.GetPayloadResponse\x12T\n" +
	"\tQueryLogs\x12\".servicebridge.v1.QueryLogsRequest\x1a#.servicebridge.v1.QueryLogsResponse\x12]\n" +
	"\fQueryMetrics\x12%.servicebridge.v1.QueryMetricsRequest\x1a&.servicebridge.v1.QueryMetricsResponseBCZAgithub.com/service-bridge/runtime/internal/pb/servicebridge/v1;pbb\x06proto3"

var (
	file_servicebridge_v1_telemetry_proto_rawDescOnce sync.Once
	file_servicebridge_v1_telemetry_proto_rawDescData []byte
)

func file_servicebridge_v1_telemetry_proto_rawDescGZIP() []byte {
	file_servicebridge_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_servicebridge_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servicebridge_v1_telemetry_proto_rawDesc), len(file_servicebridge_v1_telemetry_proto_rawDesc)))
	})
	return file_servicebridge_v1_telemetry_proto_rawDescData
}

var file_servicebridge_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_servicebridge_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_servicebridge_v1_telemetry_proto_goTypes = []any{
	(Channel)(0),                 // 0: servicebridge.v1.Channel
	(Status)(0),                  // 1: servicebridge.v1.Status
	(LogLevel)(0),                // 2: servicebridge.v1.LogLevel
	(MetricKind)(0),              // 3: servicebridge.v1.MetricKind
	(*TelemetryBatch)(nil),       // 4: servicebridge.v1.TelemetryBatch
	(*OpBatch)(nil),              // 5: servicebridge.v1.OpBatch
	(*LogBatch)(nil),             // 6: servicebridge.v1.LogBatch
	(*MetricBatch)(nil),          // 7: servicebridge.v1.MetricBatch
	(*PayloadBatch)(nil),         // 8: servicebridge.v1.PayloadBatch
	(*OpReport)(nil),             // 9: servicebridge.v1.OpReport
	(*Log)(nil),                  // 10: servicebridge.v1.Log
	(*MetricPoint)(nil),          // 11: servicebridge.v1.MetricPoint
	(*PayloadAttachment)(nil),    // 12: servicebridge.v1.PayloadAttachment
	(*TelemetryAck)(nil),         // 13: servicebridge.v1.TelemetryAck
	(*ListTracesRequest)(nil),    // 14: servicebridge.v1.ListTracesRequest
	(*TraceSummary)(nil),         // 15: servicebridge.v1.TraceSummary
	(*ListTracesResponse)(nil),   // 16: servicebridge.v1.ListTracesResponse
	(*GetTraceRequest)(nil),      // 17: servicebridge.v1.GetTraceRequest
	(*OperationView)(nil),        // 18: servicebridge.v1.OperationView
	(*GetTraceResponse)(nil),     // 19: servicebridge.v1.GetTraceResponse
	(*GetOperationRequest)(nil),  // 20: servicebridge.v1.GetOperationRequest
	(*GetOperationResponse)(nil), // 21: servicebridge.v1.GetOperationResponse
	(*GetPayloadRequest)(nil),    // 22: servicebridge.v1.GetPayloadRequest
	(*GetPayloadResponse)(nil),   // 23: servicebridge.v1.GetPayloadResponse
	(*QueryLogsRequest)(nil),     // 24: servicebridge.v1.QueryLogsRequest
	(*QueryLogsResponse)(nil),    // 25: servicebridge.v1.QueryLogsResponse
	(*QueryMetricsRequest)(nil),  // 26: servicebridge.v1.QueryMetricsRequest
	(*MetricSeries)(nil),         // 27: servicebridge.v1.MetricSeries
	(*QueryMetricsResponse)(nil), // 28: servicebridge.v1.QueryMetricsResponse
	nil,                          // 29: servicebridge.v1.MetricPoint.LabelsEntry
	nil,                          // 30: servicebridge.v1.QueryMetricsRequest.LabelFiltersEntry
	nil,                          // 31: servicebridge.v1.MetricSeries.LabelsEntry
}
var file_servicebridge_v1_telemetry_proto_depIdxs = []int32{
	5,  // 0: servicebridge.v1.TelemetryBatch.ops:type_name -> servicebridge.v1.OpBatch
	6,  // 1: servicebridge.v1.TelemetryBatch.logs:type_name -> servicebridge.v1.LogBatch
	7,  // 2: servicebridge.v1.TelemetryBatch.metrics:type_name -> servicebridge.v1.MetricBatch
	8,  // 3: servicebridge.v1.TelemetryBatch.payloads:type_name -> servicebridge.v1.PayloadBatch
	9,  // 4: servicebridge.v1.OpBatch.items:type_name -> servicebridge.v1.OpReport
	10, // 5: servicebridge.v1.LogBatch.items:type_name -> servicebridge.v1.Log
	11, // 6: servicebridge.v1.MetricBatch.items:type_name -> servicebridge.v1.MetricPoint
	12, // 7: servicebridge.v1.PayloadBatch.items:type_name -> servicebridge.v1.PayloadAttachment
	0,  // 8: servicebridge.v1.OpReport.channel:type_name -> servicebridge.v1.Channel
	1,  // 9: servicebridge.v1.OpReport.status:type_name -> servicebridge.v1.Status
	2,  // 10: servicebridge.v1.Log.level:type_name -> servicebridge.v1.LogLevel
	3,  // 11: servicebridge.v1.MetricPoint.kind:type_name -> servicebridge.v1.MetricKind
	29, // 12: servicebridge.v1.MetricPoint.labels:type_name -> servicebridge.v1.MetricPoint.LabelsEntry
	0,  // 13: servicebridge.v1.ListTracesRequest.channel_filter:type_name -> servicebridge.v1.Channel
	1,  // 14: servicebridge.v1.ListTracesRequest.status_filter:type_name -> servicebridge.v1.Status
	1,  // 15: servicebridge.v1.TraceSummary.overall_status:type_name -> servicebridge.v1.Status
	15, // 16: servicebridge.v1.ListTracesResponse.traces:type_name -> servicebridge.v1.TraceSummary
	0,  // 17: servicebridge.v1.OperationView.channel:type_name -> servicebridge.v1.Channel
	1,  // 18: servicebridge.v1.OperationView.status:type_name -> servicebridge.v1.Status
	18, // 19: servicebridge.v1.GetTraceResponse.ops:type_name -> servicebridge.v1.OperationView
	18, // 20: servicebridge.v1.GetOperationResponse.op:type_name -> servicebridge.v1.OperationView
	2,  // 21: servicebridge.v1.QueryLogsRequest.min_level:type_name -> servicebridge.v1.LogLevel
	10, // 22: servicebridge.v1.QueryLogsResponse.entries:type_name -> servicebridge.v1.Log
	30, // 23: servicebridge.v1.QueryMetricsRequest.label_filters:type_name -> servicebridge.v1.QueryMetricsRequest.LabelFiltersEntry
	31, // 24: servicebridge.v1.MetricSeries.labels:type_name -> servicebridge.v1.MetricSeries.LabelsEntry
	27, // 25: servicebridge.v1.QueryMetricsResponse.series:type_name -> servicebridge.v1.MetricSeries
	4,  // 26: servicebridge.v1.Telemetry.Report:input_type -> servicebridge.v1.TelemetryBatch
	14, // 27: servicebridge.v1.Telemetry.ListTraces:input_type -> servicebridge.v1.ListTracesRequest
	17, // 28: servicebridge.v1.Telemetry.GetTrace:input_type -> servicebridge.v1.GetTraceRequest
	20, // 29: servicebridge.v1.Telemetry.GetOperation:input_type -> servicebridge.v1.GetOperationRequest
	22, // 30: servicebridge.v1.Telemetry.GetPayload:input_type -> servicebridge.v1.GetPayloadRequest
	24, // 31: servicebridge.v1.Telemetry.QueryLogs:input_type -> servicebridge.v1.QueryLogsRequest
	26, // 32: servicebridge.v1.Telemetry.QueryMetrics:input_type -> servicebridge.v1.QueryMetricsRequest
	13, // 33: servicebridge.v1.Telemetry.Report:output_type -> servicebridge.v1.TelemetryAck
	16, // 34: servicebridge.v1.Telemetry.ListTraces:output_type -> servicebridge.v1.ListTracesResponse
	19, // 35: servicebridge.v1.Telemetry.GetTrace:output_type -> servicebridge.v1.GetTraceResponse
	21, // 36: servicebridge.v1.Telemetry.GetOperation:output_type -> servicebridge.v1.GetOperationResponse
	23, // 37: servicebridge.v1.Telemetry.GetPayload:output_type -> servicebridge.v1.GetPayloadResponse
	25, // 38: servicebridge.v1.Telemetry.QueryLogs:output_type -> servicebridge.v1.QueryLogsResponse
	28, // 39: servicebridge.v1.Telemetry.QueryMetrics:output_type -> servicebridge.v1.QueryMetricsResponse
	33, // [33:40] is the sub-list for method output_type
	26, // [26:33] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_servicebridge_v1_telemetry_proto_init() }
func file_servicebridge_v1_telemetry_proto_init() {
	if File_servicebridge_v1_telemetry_proto != nil {
		return
	}
	file_servicebridge_v1_telemetry_proto_msgTypes[0].OneofWrappers = []any{
		(*TelemetryBatch_Ops)(nil),
		(*TelemetryBatch_Logs)(nil),
		(*TelemetryBatch_Metrics)(nil),
		(*TelemetryBatch_Payloads)(nil),
	}
	file_servicebridge_v1_telemetry_proto_msgTypes[5].OneofWrappers = []any{}
	file_servicebridge_v1_telemetry_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servicebridge_v1_telemetry_proto_rawDesc), len(file_servicebridge_v1_telemetry_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicebridge_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_servicebridge_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_servicebridge_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_servicebridge_v1_telemetry_proto_msgTypes,
	}.Build()
	File_servicebridge_v1_telemetry_proto = out.File
	file_servicebridge_v1_telemetry_proto_goTypes = nil
	file_servicebridge_v1_telemetry_proto_depIdxs = nil
}
