// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: servicebridge/v1/ui.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServiceGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceGraphRequest) Reset() {
	*x = GetServiceGraphRequest{}
	mi := &file_servicebridge_v1_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceGraphRequest) ProtoMessage() {}

func (x *GetServiceGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceGraphRequest.ProtoReflect.Descriptor instead.
func (*GetServiceGraphRequest) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_ui_proto_rawDescGZIP(), []int{0}
}

type ServiceGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceNode         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceGraph) Reset() {
	*x = ServiceGraph{}
	mi := &file_servicebridge_v1_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGraph) ProtoMessage() {}

func (x *ServiceGraph) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGraph.ProtoReflect.Descriptor instead.
func (*ServiceGraph) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_ui_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceGraph) GetServices() []*ServiceNode {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceStatus string                 `protobuf:"bytes,3,opt,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"` // 'active' | 'revoked'
	// Capability flags (TRUE means service may register that handler type).
	CapRpcHandle      bool `protobuf:"varint,4,opt,name=cap_rpc_handle,json=capRpcHandle,proto3" json:"cap_rpc_handle,omitempty"`
	CapEventHandle    bool `protobuf:"varint,5,opt,name=cap_event_handle,json=capEventHandle,proto3" json:"cap_event_handle,omitempty"`
	CapWorkflowHandle bool `protobuf:"varint,6,opt,name=cap_workflow_handle,json=capWorkflowHandle,proto3" json:"cap_workflow_handle,omitempty"`
	CapJobHandle      bool `protobuf:"varint,7,opt,name=cap_job_handle,json=capJobHandle,proto3" json:"cap_job_handle,omitempty"`
	// Registered handlers.
	Methods []*UIMethod `protobuf:"bytes,8,rep,name=methods,proto3" json:"methods,omitempty"`
	// Live instances.
	Instances []*UIInstance `protobuf:"bytes,9,rep,name=instances,proto3" json:"instances,omitempty"`
	// Outgoing calls declared by this service (sb.service deps).
	OutgoingCalls []*UIOutgoing `protobuf:"bytes,10,rep,name=outgoing_calls,json=outgoingCalls,proto3" json:"outgoing_calls,omitempty"`
	// Durable event subscriptions of this service (may include wildcards).
	EventSubscriptions []*UIEventSubscription `protobuf:"bytes,11,rep,name=event_subscriptions,json=eventSubscriptions,proto3" json:"event_subscriptions,omitempty"`
	// Policy rules attached to this service. Direction is 'E' or 'A'.
	PolicyRules   []*UIPolicyRule `protobuf:"bytes,12,rep,name=policy_rules,json=policyRules,proto3" json:"policy_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceNode) Reset() {
	*x = ServiceNode{}
	mi := &file_servicebridge_v1_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNode) ProtoMessage() {}

func (x *ServiceNode) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNode.ProtoReflect.Descriptor instead.
func (*ServiceNode) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_ui_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceNode) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceNode) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceNode) GetServiceStatus() string {
	if x != nil {
		return x.ServiceStatus
	}
	return ""
}

func (x *ServiceNode) GetCapRpcHandle() bool {
	if x != nil {
		return x.CapRpcHandle
	}
	return false
}

func (x *ServiceNode) GetCapEventHandle() bool {
	if x != nil {
		return x.CapEventHandle
	}
	return false
}

func (x *ServiceNode) GetCapWorkflowHandle() bool {
	if x != nil {
		return x.CapWorkflowHandle
	}
	return false
}

func (x *ServiceNode) GetCapJobHandle() bool {
	if x != nil {
		return x.CapJobHandle
	}
	return false
}

func (x *ServiceNode) GetMethods() []*UIMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *ServiceNode) GetInstances() []*UIInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ServiceNode) GetOutgoingCalls() []*UIOutgoing {
	if x != nil {
		return x.OutgoingCalls
	}
	return nil
}

func (x *ServiceNode) GetEventSubscriptions() []*UIEventSubscription {
	if x != nil {
		return x.EventSubscriptions
	}
	return nil
}

func (x *ServiceNode) GetPolicyRules() []*UIPolicyRule {
	if x != nil {
		return x.PolicyRules
	}
	return nil
}

type UIMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // 'rpc' | 'event' | 'workflow' | 'job' | 'http'
	ContractHash  string                 `protobuf:"bytes,3,opt,name=contract_hash,json=contractHash,proto3" json:"contract_hash,omitempty"`
	Streaming     bool                   `protobuf:"varint,4,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Published     bool                   `protobuf:"varint,5,opt,name=published,proto3" json:"published,omitempty"` // true for events declared as publisher
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIMethod) Reset() {
	*x = UIMethod{}
	mi := &file_servicebridge_v1_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIMethod) ProtoMessage() {}

func (x *UIMethod) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIMethod.ProtoReflect.Descriptor instead.
func (*UIMethod) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_ui_proto_rawDescGZIP(), []int{3}
}

func (x *UIMethod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UIMethod) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UIMethod) GetContractHash() string {
	if x != nil {
		return x.ContractHash
	}
	return ""
}

func (x *UIMethod) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *UIMethod) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

type UIInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CallEndpoint  string                 `protobuf:"bytes,3,opt,name=call_endpoint,json=callEndpoint,proto3" json:"call_endpoint,omitempty"`
	HttpEndpoint  string                 `protobuf:"bytes,4,opt,name=http_endpoint,json=httpEndpoint,proto3" json:"http_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIInstance) Reset() {
	*x = UIInstance{}
	mi := &file_servicebridge_v1_ui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIInstance) ProtoMessage() {}

func (x *UIInstance) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_ui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIInstance.ProtoReflect.Descriptor instead.
func (*UIInstance) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_ui_proto_rawDescGZIP(), []int{4}
}

func (x *UIInstance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UIInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UIInstance) GetCallEndpoint() string {
	if x != nil {
		return x.CallEndpoint
	}
	return ""
}

func (x *UIInstance) GetHttpEndpoint() string {
	if x != nil {
		return x.HttpEndpoint
	}
	return ""
}

type UIOutgoing struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetServiceId string                 `protobuf:"bytes,1,opt,name=target_service_id,json=targetServiceId,proto3" json:"target_service_id,omitempty"`
	TargetMethod    string                 `protobuf:"bytes,2,opt,name=target_method,json=targetMethod,proto3" json:"target_method,omitempty"`
	TargetType      string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 'rpc' | 'workflow' | 'http'
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UIOutgoing) Reset() {
	*x = UIOutgoing{}
	mi := &file_servicebridge_v1_ui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIOutgoing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIOutgoing) ProtoMessage() {}

func (x *UIOutgoing) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_ui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIOutgoing.ProtoReflect.Descriptor instead.
func (*UIOutgoing) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_ui_proto_rawDescGZIP(), []int{5}
}

func (x *UIOutgoing) GetTargetServiceId() string {
	if x != nil {
		return x.TargetServiceId
	}
	return ""
}

func (x *UIOutgoing) GetTargetMethod() string {
	if x != nil {
		return x.TargetMethod
	}
	return ""
}

func (x *UIOutgoing) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

type UIEventSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Durable       bool                   `protobuf:"varint,2,opt,name=durable,proto3" json:"durable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIEventSubscription) Reset() {
	*x = UIEventSubscription{}
	mi := &file_servicebridge_v1_ui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIEventSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIEventSubscription) ProtoMessage() {}

func (x *UIEventSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_ui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIEventSubscription.ProtoReflect.Descriptor instead.
func (*UIEventSubscription) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_ui_proto_rawDescGZIP(), []int{6}
}

func (x *UIEventSubscription) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *UIEventSubscription) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

type UIPolicyRule struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Direction              string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`                                                             // 'E' | 'A'
	Action                 string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`                                                                   // rpc.call | rpc.handle | event.publish | ...
	AnalyticsPeerServiceId string                 `protobuf:"bytes,3,opt,name=analytics_peer_service_id,json=analyticsPeerServiceId,proto3" json:"analytics_peer_service_id,omitempty"` // empty for event.* (no per-service routing)
	TargetName             string                 `protobuf:"bytes,4,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UIPolicyRule) Reset() {
	*x = UIPolicyRule{}
	mi := &file_servicebridge_v1_ui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIPolicyRule) ProtoMessage() {}

func (x *UIPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_servicebridge_v1_ui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIPolicyRule.ProtoReflect.Descriptor instead.
func (*UIPolicyRule) Descriptor() ([]byte, []int) {
	return file_servicebridge_v1_ui_proto_rawDescGZIP(), []int{7}
}

func (x *UIPolicyRule) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *UIPolicyRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UIPolicyRule) GetAnalyticsPeerServiceId() string {
	if x != nil {
		return x.AnalyticsPeerServiceId
	}
	return ""
}

func (x *UIPolicyRule) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

var File_servicebridge_v1_ui_proto protoreflect.FileDescriptor

const file_servicebridge_v1_ui_proto_rawDesc = "" +
	"\n" +
	"\x19servicebridge/v1/ui.proto\x12\x10servicebridge.v1\"\x18\n" +
	"\x16GetServiceGraphRequest\"I\n" +
	"\fServiceGraph\x129\n" +
	"\bservices\x18\x01 \x03(\v2\x1d.servicebridge.v1.ServiceNodeR\bservices\"\xee\x04\n" +
	"\vServiceNode\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12%\n" +
	"\x0eservice_status\x18\x03 \x01(\tR\rserviceStatus\x12$\n" +
	"\x0ecap_rpc_handle\x18\x04 \x01(\bR\fcapRpcHandle\x12(\n" +
	"\x10cap_event_handle\x18\x05 \x01(\bR\x0ecapEventHandle\x12.\n" +
	"\x13cap_workflow_handle\x18\x06 \x01(\bR\x11capWorkflowHandle\x12$\n" +
	"\x0ecap_job_handle\x18\a \x01(\bR\fcapJobHandle\x124\n" +
	"\amethods\x18\b \x03(\v2\x1a.servicebridge.v1.UIMethodR\amethods\x12:\n" +
	"\tinstances\x18\t \x03(\v2\x1c.servicebridge.v1.UIInstanceR\tinstances\x12C\n" +
	"\x0eoutgoing_calls\x18\n" +
	" \x03(\v2\x1c.servicebridge.v1.UIOutgoingR\routgoingCalls\x12V\n" +
	"\x13event_subscriptions\x18\v \x03(\v2%.servicebridge.v1.UIEventSubscriptionR\x12eventSubscriptions\x12A\n" +
	"\fpolicy_rules\x18\f \x03(\v2\x1e.servicebridge.v1.UIPolicyRuleR\vpolicyRules\"\x93\x01\n" +
	"\bUIMethod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rcontract_hash\x18\x03 \x01(\tR\fcontractHash\x12\x1c\n" +
	"\tstreaming\x18\x04 \x01(\bR\tstreaming\x12\x1c\n" +
	"\tpublished\x18\x05 \x01(\bR\tpublished\"\x8f\x01\n" +
	"\n" +
	"UIInstance\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcall_endpoint\x18\x03 \x01(\tR\fcallEndpoint\x12#\n" +
	"\rhttp_endpoint\x18\x04 \x01(\tR\fhttpEndpoint\"~\n" +
	"\n" +
	"UIOutgoing\x12*\n" +
	"\x11target_service_id\x18\x01 \x01(\tR\x0ftargetServiceId\x12#\n" +
	"\rtarget_method\x18\x02 \x01(\tR\ftargetMethod\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\"I\n" +
	"\x13UIEventSubscription\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x18\n" +
	"\adurable\x18\x02 \x01(\bR\adurable\"\xa0\x01\n" +
	"\fUIPolicyRule\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x129\n" +
	"\x19analytics_peer_service_id\x18\x03 \x01(\tR\x16analyticsPeerServiceId\x12\x1f\n" +
	"\vtarget_name\x18\x04 \x01(\tR\n" +
	"targetName2a\n" +
	"\x02UI\x12[\n" +
	"\x0fGetServiceGraph\x12(.servicebridge.v1.GetServiceGraphRequest\x1a\x1e.servicebridge.v1.ServiceGraphBCZAgithub.com/service-bridge/runtime/internal/pb/servicebridge/v1;pbb\x06proto3"

var (
	file_servicebridge_v1_ui_proto_rawDescOnce sync.Once
	file_servicebridge_v1_ui_proto_rawDescData []byte
)

func file_servicebridge_v1_ui_proto_rawDescGZIP() []byte {
	file_servicebridge_v1_ui_proto_rawDescOnce.Do(func() {
		file_servicebridge_v1_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servicebridge_v1_ui_proto_rawDesc), len(file_servicebridge_v1_ui_proto_rawDesc)))
	})
	return file_servicebridge_v1_ui_proto_rawDescData
}

var file_servicebridge_v1_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_servicebridge_v1_ui_proto_goTypes = []any{
	(*GetServiceGraphRequest)(nil), // 0: servicebridge.v1.GetServiceGraphRequest
	(*ServiceGraph)(nil),           // 1: servicebridge.v1.ServiceGraph
	(*ServiceNode)(nil),            // 2: servicebridge.v1.ServiceNode
	(*UIMethod)(nil),               // 3: servicebridge.v1.UIMethod
	(*UIInstance)(nil),             // 4: servicebridge.v1.UIInstance
	(*UIOutgoing)(nil),             // 5: servicebridge.v1.UIOutgoing
	(*UIEventSubscription)(nil),    // 6: servicebridge.v1.UIEventSubscription
	(*UIPolicyRule)(nil),           // 7: servicebridge.v1.UIPolicyRule
}
var file_servicebridge_v1_ui_proto_depIdxs = []int32{
	2, // 0: servicebridge.v1.ServiceGraph.services:type_name -> servicebridge.v1.ServiceNode
	3, // 1: servicebridge.v1.ServiceNode.methods:type_name -> servicebridge.v1.UIMethod
	4, // 2: servicebridge.v1.ServiceNode.instances:type_name -> servicebridge.v1.UIInstance
	5, // 3: servicebridge.v1.ServiceNode.outgoing_calls:type_name -> servicebridge.v1.UIOutgoing
	6, // 4: servicebridge.v1.ServiceNode.event_subscriptions:type_name -> servicebridge.v1.UIEventSubscription
	7, // 5: servicebridge.v1.ServiceNode.policy_rules:type_name -> servicebridge.v1.UIPolicyRule
	0, // 6: servicebridge.v1.UI.GetServiceGraph:input_type -> servicebridge.v1.GetServiceGraphRequest
	1, // 7: servicebridge.v1.UI.GetServiceGraph:output_type -> servicebridge.v1.ServiceGraph
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_servicebridge_v1_ui_proto_init() }
func file_servicebridge_v1_ui_proto_init() {
	if File_servicebridge_v1_ui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servicebridge_v1_ui_proto_rawDesc), len(file_servicebridge_v1_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicebridge_v1_ui_proto_goTypes,
		DependencyIndexes: file_servicebridge_v1_ui_proto_depIdxs,
		MessageInfos:      file_servicebridge_v1_ui_proto_msgTypes,
	}.Build()
	File_servicebridge_v1_ui_proto = out.File
	file_servicebridge_v1_ui_proto_goTypes = nil
	file_servicebridge_v1_ui_proto_depIdxs = nil
}
